# Batch 5: the Community tab, playback/score screens and the vocal-range test.
from trbase import T

# --- Community ---
T("Users", "Nutzer", "Usuarios", "Utilisateurs", "Utenti", "Usuários", "Gebruikers", "Пользователи", "Użytkownicy", "Kullanıcılar", "Användare", "ユーザー", "사용자", "用户")
T("Users, Exercises, Descriptions", "Nutzer, Übungen, Beschreibungen", "Usuarios, ejercicios, descripciones", "Utilisateurs, exercices, descriptions", "Utenti, esercizi, descrizioni", "Usuários, exercícios, descrições", "Gebruikers, oefeningen, beschrijvingen", "Пользователи, упражнения, описания", "Użytkownicy, ćwiczenia, opisy", "Kullanıcılar, egzersizler, açıklamalar", "Användare, övningar, beskrivningar", "ユーザー、エクササイズ、説明", "사용자, 연습, 설명", "用户、练习、说明")
T("Likes", "Likes", "Me gusta", "J’aime", "Mi piace", "Curtidas", "Likes", "Отметки «Нравится»", "Polubienia", "Beğeniler", "Gillanden", "いいね", "좋아요", "点赞")
T("Liked", "Geliked", "Con me gusta", "Aimés", "Con Mi piace", "Curtidos", "Geliket", "С отметкой «Нравится»", "Polubione", "Beğenilenler", "Gillade", "いいね済み", "좋아요한 항목", "已点赞")
T("Not Liked", "Nicht geliked", "Sin me gusta", "Non aimés", "Senza Mi piace", "Não curtidos", "Niet geliket", "Без отметки «Нравится»", "Niepolubione", "Beğenilmeyenler", "Ej gillade", "いいねしていない", "좋아요하지 않은 항목", "未点赞")
T("Sort", "Sortieren", "Ordenar", "Trier", "Ordina", "Ordenar", "Sorteren", "Сортировка", "Sortuj", "Sırala", "Sortera", "並べ替え", "정렬", "排序")
T("Sort By", "Sortieren nach", "Ordenar por", "Trier par", "Ordina per", "Ordenar por", "Sorteren op", "Сортировать по", "Sortuj według", "Şuna göre sırala", "Sortera efter", "並べ替えの基準", "정렬 기준", "排序方式")
T("Hot", "Angesagt", "Tendencias", "Tendances", "Di tendenza", "Em alta", "Populair", "Популярное", "Na czasie", "Popüler", "Populärt", "人気", "인기", "热门")
T("Newest First", "Neueste zuerst", "Más recientes primero", "Les plus récents d’abord", "Prima i più recenti", "Mais recentes primeiro", "Nieuwste eerst", "Сначала новые", "Najpierw najnowsze", "Önce en yeniler", "Nyast först", "新しい順", "최신순", "最新优先")
T("Recently Updated", "Kürzlich aktualisiert", "Actualizados recientemente", "Récemment mis à jour", "Aggiornati di recente", "Atualizados recentemente", "Onlangs bijgewerkt", "Недавно обновлённые", "Ostatnio zaktualizowane", "Son güncellenenler", "Nyligen uppdaterade", "更新が新しい順", "최근 업데이트순", "最近更新")
T("Most Liked", "Meiste Likes", "Con más me gusta", "Les plus aimés", "Più apprezzati", "Mais curtidos", "Meeste likes", "Больше всего «Нравится»", "Najczęściej polubione", "En çok beğenilen", "Mest gillade", "いいねが多い順", "좋아요순", "点赞最多")
T("Most Played", "Meiste Wiedergaben", "Más reproducidos", "Les plus joués", "Più riprodotti", "Mais reproduzidos", "Meest afgespeeld", "Больше всего воспроизведений", "Najczęściej odtwarzane", "En çok oynatılan", "Mest spelade", "再生が多い順", "재생순", "播放最多")
T("Most Downloaded", "Meiste Downloads", "Más descargados", "Les plus téléchargés", "Più scaricati", "Mais baixados", "Meest gedownload", "Больше всего загрузок", "Najczęściej pobierane", "En çok indirilen", "Mest nedladdade", "ダウンロードが多い順", "내려받기순", "下载最多")
T("Reverse Order", "Umgekehrte Reihenfolge", "Orden inverso", "Ordre inversé", "Ordine inverso", "Ordem inversa", "Omgekeerde volgorde", "Обратный порядок", "Odwrotna kolejność", "Ters sıra", "Omvänd ordning", "逆順", "역순", "倒序")
T("Alphabetical", "Alphabetisch", "Alfabético", "Alphabétique", "Alfabetico", "Alfabético", "Alfabetisch", "По алфавиту", "Alfabetycznie", "Alfabetik", "Alfabetiskt", "アルファベット順", "가나다순", "按字母顺序")
T("No Community Exercises", "Keine Community-Übungen", "No hay ejercicios de la comunidad", "Aucun exercice de la communauté", "Nessun esercizio della comunità", "Nenhum exercício da comunidade", "Geen community-oefeningen", "Нет упражнений сообщества", "Brak ćwiczeń społeczności", "Topluluk egzersizi yok", "Inga community-övningar", "コミュニティのエクササイズがありません", "커뮤니티 연습이 없습니다", "暂无社区练习")
T("Public exercises shared by all users appear here. Pull down to refresh.", "Hier erscheinen die öffentlichen Übungen aller Nutzer. Zum Aktualisieren nach unten ziehen.", "Aquí aparecen los ejercicios públicos compartidos por todos los usuarios. Desliza hacia abajo para actualizar.", "Les exercices publics partagés par tous les utilisateurs apparaissent ici. Tirez vers le bas pour actualiser.", "Qui compaiono gli esercizi pubblici condivisi da tutti gli utenti. Trascina verso il basso per aggiornare.", "Os exercícios públicos compartilhados por todos os usuários aparecem aqui. Puxe para baixo para atualizar.", "Hier verschijnen de openbare oefeningen die alle gebruikers delen. Trek omlaag om te vernieuwen.", "Здесь появляются публичные упражнения всех пользователей. Потяните вниз, чтобы обновить.", "Tutaj pojawiają się publiczne ćwiczenia udostępnione przez wszystkich użytkowników. Pociągnij w dół, aby odświeżyć.", "Tüm kullanıcıların paylaştığı herkese açık egzersizler burada görünür. Yenilemek için aşağı çekin.", "Här visas offentliga övningar som delats av alla användare. Dra nedåt för att uppdatera.", "すべてのユーザーが共有した公開エクササイズがここに表示されます。下に引いて更新します。", "모든 사용자가 공유한 공개 연습이 여기에 표시됩니다. 아래로 당겨 새로 고치세요.", "所有用户分享的公开练习会显示在这里。下拉可刷新。")
T("No public exercise matches the selected filters.", "Keine öffentliche Übung entspricht den gewählten Filtern.", "Ningún ejercicio público coincide con los filtros seleccionados.", "Aucun exercice public ne correspond aux filtres sélectionnés.", "Nessun esercizio pubblico corrisponde ai filtri selezionati.", "Nenhum exercício público corresponde aos filtros selecionados.", "Geen enkele openbare oefening voldoet aan de gekozen filters.", "Ни одно публичное упражнение не соответствует выбранным фильтрам.", "Żadne publiczne ćwiczenie nie pasuje do wybranych filtrów.", "Seçili filtrelerle eşleşen herkese açık egzersiz yok.", "Ingen offentlig övning matchar de valda filtren.", "選択したフィルタに一致する公開エクササイズはありません。", "선택한 필터와 일치하는 공개 연습이 없습니다.", "没有公开练习符合所选筛选条件。")
T("No Public Exercises", "Keine öffentlichen Übungen", "Sin ejercicios públicos", "Aucun exercice public", "Nessun esercizio pubblico", "Nenhum exercício público", "Geen openbare oefeningen", "Нет публичных упражнений", "Brak publicznych ćwiczeń", "Herkese açık egzersiz yok", "Inga offentliga övningar", "公開エクササイズがありません", "공개 연습이 없습니다", "暂无公开练习")
T("%@ has no public exercises right now.", "%@ hat derzeit keine öffentlichen Übungen.", "%@ no tiene ejercicios públicos por ahora.", "%@ n’a aucun exercice public pour le moment.", "%@ al momento non ha esercizi pubblici.", "%@ não tem exercícios públicos no momento.", "%@ heeft op dit moment geen openbare oefeningen.", "Сейчас у %@ нет публичных упражнений.", "%@ nie ma teraz żadnych publicznych ćwiczeń.", "%@ şu anda herkese açık egzersize sahip değil.", "%@ har inga offentliga övningar just nu.", "%@さんの公開エクササイズは現在ありません。", "%@님의 공개 연습이 현재 없습니다.", "%@ 目前没有公开的练习。")
T("Joined %@", "Beigetreten %@", "Se unió %@", "Inscrit %@", "Iscritto %@", "Entrou %@", "Lid geworden %@", "Присоединился %@", "Dołączył %@", "Katıldı: %@", "Gick med %@", "参加: %@", "가입: %@", "加入于 %@")

# --- Playback / score ---
T("Score", "Punktzahl", "Puntuación", "Note", "Punteggio", "Pontuação", "Score", "Оценка", "Wynik", "Puan", "Poäng", "スコア", "점수", "得分")
T("Play Again", "Nochmal spielen", "Repetir", "Rejouer", "Riprova", "Jogar de novo", "Opnieuw spelen", "Ещё раз", "Zagraj ponownie", "Tekrar oyna", "Spela igen", "もう一度", "다시 하기", "再来一次")
T("Review", "Auswerten", "Revisar", "Revoir", "Rivedi", "Revisar", "Terugkijken", "Разбор", "Przejrzyj", "İncele", "Granska", "振り返り", "다시 보기", "回看")
T("No scores in this period", "Keine Punktzahlen in diesem Zeitraum", "No hay puntuaciones en este periodo", "Aucune note sur cette période", "Nessun punteggio in questo periodo", "Nenhuma pontuação neste período", "Geen scores in deze periode", "За этот период оценок нет", "Brak wyników w tym okresie", "Bu dönemde puan yok", "Inga poäng under den här perioden", "この期間のスコアはありません", "이 기간의 점수가 없습니다", "此期间没有得分")
T("All", "Alle", "Todo", "Tout", "Tutto", "Tudo", "Alles", "Всё", "Wszystko", "Tümü", "Allt", "全期間", "전체", "全部")
T("24h", "24 Std.", "24 h", "24 h", "24 h", "24 h", "24 u", "24 ч", "24 godz.", "24 sa", "24 tim", "24時間", "24시간", "24小时")
T("7d", "7 Tage", "7 d", "7 j", "7 gg", "7 d", "7 d", "7 дн.", "7 dni", "7 gün", "7 dgr", "7日", "7일", "7天")
T("30d", "30 Tage", "30 d", "30 j", "30 gg", "30 d", "30 d", "30 дн.", "30 dni", "30 gün", "30 dgr", "30日", "30일", "30天")
T("6m", "6 Mon.", "6 m", "6 m", "6 m", "6 m", "6 mnd", "6 мес.", "6 mies.", "6 ay", "6 mån", "6か月", "6개월", "6个月")
T("1y", "1 Jahr", "1 a", "1 an", "1 anno", "1 ano", "1 jr", "1 год", "1 rok", "1 yıl", "1 år", "1年", "1년", "1年")

T("Microphone Delay", "Mikrofonverzögerung", "Retardo del micrófono", "Retard du micro", "Ritardo del microfono", "Atraso do microfone", "Microfoonvertraging", "Задержка микрофона", "Opóźnienie mikrofonu", "Mikrofon gecikmesi", "Mikrofonfördröjning", "マイク遅延", "마이크 지연", "麦克风延迟")
T("%d ms", "%d ms", "%d ms", "%d ms", "%d ms", "%d ms", "%d ms", "%d мс", "%d ms", "%d ms", "%d ms", "%d ミリ秒", "%d밀리초", "%d 毫秒")
T("Your microphone delay setting has been updated.", "Deine Einstellung für die Mikrofonverzögerung wurde aktualisiert.", "Se ha actualizado tu ajuste de retardo del micrófono.", "Votre réglage de retard du micro a été mis à jour.", "L’impostazione del ritardo del microfono è stata aggiornata.", "Sua configuração de atraso do microfone foi atualizada.", "Je instelling voor microfoonvertraging is bijgewerkt.", "Настройка задержки микрофона обновлена.", "Twoje ustawienie opóźnienia mikrofonu zostało zaktualizowane.", "Mikrofon gecikmesi ayarınız güncellendi.", "Din inställning för mikrofonfördröjning har uppdaterats.", "マイク遅延の設定を更新しました。", "마이크 지연 설정이 업데이트되었습니다.", "你的麦克风延迟设置已更新。")

# The alert over the calibration the first run a singer scores anything on ends on
# (the screen itself reuses the sung delay test's strings above).
T("Slide your singing until it lines up with the notes. The delay this sets only affects how your score is worked out, and you can redo it any time in Settings under Audio.",
  "Verschiebe deinen Gesang, bis er zu den Noten passt. Die so eingestellte Verzögerung wirkt sich nur darauf aus, wie deine Punktzahl berechnet wird, und du kannst das jederzeit in den Einstellungen unter „Audio“ wiederholen.",
  "Desplaza tu canto hasta que coincida con las notas. El retardo que se ajusta así solo afecta a cómo se calcula tu puntuación, y puedes repetirlo cuando quieras en Ajustes, en «Audio».",
  "Décalez votre chant jusqu’à ce qu’il coïncide avec les notes. Le retard ainsi réglé ne joue que sur le calcul de votre note, et vous pouvez recommencer à tout moment dans Réglages, sous « Audio ».",
  "Sposta il tuo canto finché non combacia con le note. Il ritardo così impostato incide solo su come viene calcolato il punteggio, e puoi rifarlo quando vuoi in Impostazioni, sotto “Audio”.",
  "Desloque seu canto até alinhar com as notas. O atraso definido assim só afeta como sua pontuação é calculada, e você pode refazer isso quando quiser em Ajustes, em “Áudio”.",
  "Schuif je zang tot die op de noten valt. De vertraging die je zo instelt bepaalt alleen hoe je score wordt berekend, en je kunt dit altijd opnieuw doen in Instellingen onder ‘Audio’.",
  "Сдвиньте своё пение так, чтобы оно совпало с нотами. Заданная так задержка влияет только на расчёт оценки, и вы можете повторить это в любое время в Настройках, в разделе «Аудио».",
  "Przesuwaj swój śpiew, aż pokryje się z nutami. Ustawione w ten sposób opóźnienie wpływa tylko na sposób obliczania wyniku i możesz to powtórzyć w dowolnej chwili w Ustawieniach, w sekcji „Dźwięk”.",
  "Şarkınızı notalarla hizalanana kadar kaydırın. Böylece ayarlanan gecikme yalnızca puanınızın nasıl hesaplandığını etkiler ve bunu istediğiniz zaman Ayarlar’da “Ses” bölümünden yineleyebilirsiniz.",
  "Skjut din sång tills den ligger i linje med noterna. Fördröjningen du ställer in påverkar bara hur din poäng räknas ut, och du kan göra om det när som helst i Inställningar under ”Ljud”.",
  "歌がノーツに合うまでずらしてください。ここで設定される遅延はスコアの計算にだけ使われ、設定の「オーディオ」でいつでもやり直せます。",
  "노래가 음표에 맞을 때까지 옆으로 옮기세요. 이렇게 설정된 지연은 점수를 계산하는 데만 쓰이며, 설정의 ‘오디오’에서 언제든 다시 할 수 있습니다.",
  "移动你的歌声，直到与音符对齐。这里设定的延迟只影响得分的计算方式，你随时可以在“设置”的“音频”中重新设置。")
T("Microphone Delay Test", "Mikrofonverzögerungstest", "Prueba de retardo del micrófono", "Test de retard du micro", "Test del ritardo del microfono", "Teste de atraso do microfone", "Microfoonvertragingstest", "Тест задержки микрофона", "Test opóźnienia mikrofonu", "Mikrofon gecikme testi", "Test av mikrofonfördröjning", "マイク遅延テスト", "마이크 지연 테스트", "麦克风延迟测试")
T("*clap*", "*klatschen*", "*palmada*", "*clap*", "*batti*", "*palma*", "*klap*", "*хлопок*", "*klaśnij*", "*alkış*", "*klapp*", "*手拍子*", "*박수*", "*拍手*")
T("This test measures how long it takes your microphone to pick up sound, so the app can line your singing up with the notes when scoring.\n\nA steady metronome will tick along with short markers labelled “clap”. Clap your hands once on every tick. The first four ticks are just to help you settle into the beat and aren't counted — keep clapping through the rest, sixteen in all.\n\nWhen it finishes, the delay between your claps and the ticks is measured and your microphone delay setting is updated automatically.\n\nFor the most accurate result, use headphones so the metronome isn't picked up by the microphone, and clap firmly.",
  "Dieser Test misst, wie lange dein Mikrofon braucht, um Schall aufzunehmen, damit die App deinen Gesang beim Bewerten richtig auf die Noten legen kann.\n\nEin gleichmäßiges Metronom tickt mit kurzen Markierungen namens „klatschen“. Klatsche bei jedem Tick einmal in die Hände. Die ersten vier Ticks helfen dir nur, in den Takt zu kommen, und zählen nicht – klatsche bei den restlichen weiter, insgesamt sechzehn Mal.\n\nAm Ende wird die Verzögerung zwischen deinem Klatschen und den Ticks gemessen und deine Einstellung für die Mikrofonverzögerung automatisch aktualisiert.\n\nFür das genaueste Ergebnis nutze Kopfhörer, damit das Metronom nicht vom Mikrofon aufgenommen wird, und klatsche kräftig.",
  "Esta prueba mide cuánto tarda tu micrófono en captar el sonido, para que la app pueda alinear tu canto con las notas al puntuar.\n\nUn metrónomo constante marcará el pulso junto a unas marcas cortas llamadas «palmada». Da una palmada en cada pulso. Los cuatro primeros solo sirven para que cojas el ritmo y no cuentan: sigue dando palmadas en el resto, dieciséis en total.\n\nAl terminar, se mide el desfase entre tus palmadas y los pulsos y se actualiza automáticamente tu ajuste de retardo del micrófono.\n\nPara obtener el resultado más preciso, usa auriculares para que el micrófono no capte el metrónomo, y da palmadas firmes.",
  "Ce test mesure le temps que met votre micro à capter le son, afin que l’app puisse aligner votre chant sur les notes lors de la notation.\n\nUn métronome régulier bat la mesure, accompagné de courts repères intitulés « clap ». Tapez dans vos mains une fois à chaque battement. Les quatre premiers battements servent seulement à vous caler dans le tempo et ne comptent pas — continuez sur les suivants, seize en tout.\n\nÀ la fin, le décalage entre vos claps et les battements est mesuré et votre réglage de retard du micro est mis à jour automatiquement.\n\nPour un résultat optimal, utilisez un casque pour que le métronome ne soit pas capté par le micro, et frappez fermement.",
  "Questo test misura quanto tempo impiega il microfono a captare il suono, così l’app può allineare il tuo canto alle note durante il punteggio.\n\nUn metronomo costante scandirà il tempo insieme a brevi indicazioni con la scritta “batti”. Batti le mani una volta a ogni battito. I primi quattro battiti servono solo per entrare nel tempo e non vengono conteggiati: continua a battere per i restanti, sedici in tutto.\n\nAlla fine viene misurato il ritardo tra i tuoi colpi e i battiti e la tua impostazione del ritardo del microfono viene aggiornata automaticamente.\n\nPer il risultato più preciso usa le cuffie, così il metronomo non viene captato dal microfono, e batti le mani con decisione.",
  "Este teste mede quanto tempo o microfone leva para captar o som, para que o app possa alinhar seu canto com as notas ao pontuar.\n\nUm metrônomo constante marcará o tempo junto com marcações curtas escritas “palma”. Bata palma uma vez a cada batida. As quatro primeiras servem apenas para você entrar no ritmo e não contam — continue batendo nas demais, dezesseis no total.\n\nAo terminar, o atraso entre suas palmas e as batidas é medido e sua configuração de atraso do microfone é atualizada automaticamente.\n\nPara o resultado mais preciso, use fones para que o metrônomo não seja captado pelo microfone, e bata palma com firmeza.",
  "Deze test meet hoe lang je microfoon erover doet om geluid op te pikken, zodat de app je zang bij het scoren goed op de noten kan leggen.\n\nEen gelijkmatige metronoom tikt mee, met korte markeringen met het woord ‘klap’. Klap één keer bij elke tik. De eerste vier tikken helpen je alleen in de maat te komen en tellen niet mee — klap door bij de rest, zestien in totaal.\n\nAan het eind wordt de vertraging tussen je klappen en de tikken gemeten en wordt je instelling voor microfoonvertraging automatisch bijgewerkt.\n\nGebruik voor het nauwkeurigste resultaat een koptelefoon, zodat de metronoom niet door de microfoon wordt opgepikt, en klap stevig.",
  "Этот тест измеряет, сколько времени микрофону нужно, чтобы уловить звук, чтобы приложение могло правильно совмещать ваше пение с нотами при оценке.\n\nРовный метроном будет отсчитывать такт вместе с короткими метками «хлопок». Хлопайте в ладоши по каждому щелчку. Первые четыре щелчка нужны только для того, чтобы поймать темп, и не учитываются — продолжайте хлопать на остальных, всего шестнадцать раз.\n\nПо окончании измеряется задержка между вашими хлопками и щелчками, и настройка задержки микрофона обновляется автоматически.\n\nДля самого точного результата используйте наушники, чтобы микрофон не улавливал метроном, и хлопайте энергично.",
  "Ten test mierzy, ile czasu potrzebuje mikrofon, aby uchwycić dźwięk, dzięki czemu aplikacja może dopasować twój śpiew do nut podczas oceniania.\n\nRówny metronom będzie wybijał takt wraz z krótkimi oznaczeniami „klaśnij”. Klaśnij raz przy każdym uderzeniu. Pierwsze cztery pomagają tylko wejść w rytm i nie są liczone — klaszcz dalej przy pozostałych, łącznie szesnaście razy.\n\nPo zakończeniu mierzone jest opóźnienie między twoimi klaśnięciami a uderzeniami, a ustawienie opóźnienia mikrofonu jest aktualizowane automatycznie.\n\nDla najdokładniejszego wyniku użyj słuchawek, aby mikrofon nie zbierał metronomu, i klaszcz zdecydowanie.",
  "Bu test, mikrofonunuzun sesi almasının ne kadar sürdüğünü ölçer; böylece uygulama puanlama sırasında şarkınızı notalarla hizalayabilir.\n\nDüzenli bir metronom, “alkış” yazan kısa işaretlerle birlikte tempo tutar. Her vuruşta bir kez el çırpın. İlk dört vuruş yalnızca tempoya alışmanız içindir ve sayılmaz; kalanlarda çırpmayı sürdürün, toplam on altı.\n\nBittiğinde alkışlarınızla vuruşlar arasındaki gecikme ölçülür ve mikrofon gecikmesi ayarınız otomatik olarak güncellenir.\n\nEn doğru sonuç için kulaklık kullanın, böylece metronom mikrofona karışmaz, ve elinizi güçlü çırpın.",
  "Det här testet mäter hur lång tid din mikrofon behöver för att fånga upp ljud, så att appen kan matcha din sång mot noterna vid poängsättning.\n\nEn jämn metronom tickar tillsammans med korta markeringar märkta ”klapp”. Klappa händerna en gång vid varje tick. De fyra första ticken hjälper dig bara att komma in i takten och räknas inte – fortsätt klappa på resten, sexton totalt.\n\nNär det är klart mäts fördröjningen mellan dina klappar och ticken, och din inställning för mikrofonfördröjning uppdateras automatiskt.\n\nFör bästa resultat, använd hörlurar så att metronomen inte fångas upp av mikrofonen, och klappa bestämt.",
  "このテストは、マイクが音を拾うまでにかかる時間を測定します。これにより、採点時にあなたの歌声と音符を正しく合わせられます。\n\n一定のテンポでメトロノームが鳴り、「手拍子」と書かれた短いマーカーが表示されます。各拍で1回手をたたいてください。最初の4拍はテンポに慣れるためのもので、カウントされません。残りも続けてたたき、全部で16回です。\n\n終了すると、あなたの手拍子とクリックの差が測定され、マイク遅延の設定が自動的に更新されます。\n\n最も正確な結果を得るには、メトロノームがマイクに入らないようヘッドフォンを使い、しっかり手をたたいてください。",
  "이 테스트는 마이크가 소리를 인식하는 데 걸리는 시간을 측정합니다. 그러면 앱이 점수를 매길 때 노래와 음표를 정확히 맞출 수 있습니다.\n\n일정한 메트로놈이 “박수”라고 표시된 짧은 마커와 함께 울립니다. 매 박마다 한 번씩 손뼉을 치세요. 처음 네 박은 박자에 적응하기 위한 것으로 계산되지 않습니다. 나머지도 계속 치며, 모두 열여섯 번입니다.\n\n끝나면 손뼉과 클릭 사이의 지연이 측정되어 마이크 지연 설정이 자동으로 업데이트됩니다.\n\n가장 정확한 결과를 얻으려면 메트로놈이 마이크에 들어가지 않도록 헤드폰을 사용하고, 손뼉을 세게 치세요.",
  "该测试用于测量麦克风拾取声音所需的时间，以便应用在评分时将你的演唱与音符对齐。\n\n节拍器会稳定地打拍，并配有标注为“拍手”的短标记。每一拍拍一次手。前四拍只是帮助你进入节奏，不计入统计——其余的继续拍，共十六次。\n\n结束后，会测量你的拍手与节拍之间的延迟，并自动更新你的麦克风延迟设置。\n\n为获得最准确的结果，请使用耳机以免节拍器被麦克风拾取，并用力拍手。")

# --- Vocal range test ---
T("Vocal Range Test", "Stimmumfangstest", "Prueba de tesitura", "Test de tessiture", "Test dell’estensione vocale", "Teste de extensão vocal", "Stembereiktest", "Тест диапазона голоса", "Test skali głosu", "Ses aralığı testi", "Röstomfångstest", "声域テスト", "음역대 테스트", "音域测试")
T("Lowest Note", "Tiefster Ton", "Nota más grave", "Note la plus grave", "Nota più bassa", "Nota mais grave", "Laagste noot", "Самая низкая нота", "Najniższy dźwięk", "En pes nota", "Lägsta ton", "最低音", "최저음", "最低音")
T("Highest Note", "Höchster Ton", "Nota más aguda", "Note la plus aiguë", "Nota più alta", "Nota mais aguda", "Hoogste noot", "Самая высокая нота", "Najwyższy dźwięk", "En tiz nota", "Högsta ton", "最高音", "최고음", "最高音")
T("When you’re ready, sing the lowest note you can and hold it steadily for 2 seconds.", "Wenn du bereit bist, singe den tiefsten Ton, den du kannst, und halte ihn 2 Sekunden lang gleichmäßig.", "Cuando estés listo, canta la nota más grave que puedas y mantenla de forma estable durante 2 segundos.", "Quand vous êtes prêt, chantez la note la plus grave possible et tenez-la de façon stable pendant 2 secondes.", "Quando sei pronto, canta la nota più bassa che riesci e tienila ferma per 2 secondi.", "Quando estiver pronto, cante a nota mais grave que conseguir e sustente-a por 2 segundos.", "Zing wanneer je klaar bent de laagste noot die je kunt en houd die 2 seconden stabiel aan.", "Когда будете готовы, спойте самую низкую ноту, которую можете, и держите её ровно 2 секунды.", "Gdy będziesz gotów, zaśpiewaj najniższy dźwięk, jaki potrafisz, i utrzymaj go równo przez 2 sekundy.", "Hazır olduğunuzda, çıkarabildiğiniz en pes notayı söyleyin ve 2 saniye boyunca sabit tutun.", "Sjung din lägsta möjliga ton när du är redo och håll den stadigt i 2 sekunder.", "準備ができたら、出せる限り低い音を歌い、2秒間まっすぐ伸ばしてください。", "준비되면 낼 수 있는 가장 낮은 음을 2초 동안 안정적으로 유지하며 부르세요.", "准备好后，唱出你能发出的最低音，并稳定保持 2 秒。")
T("Now sing the highest note you can and hold it steadily for 2 seconds.", "Singe nun den höchsten Ton, den du kannst, und halte ihn 2 Sekunden lang gleichmäßig.", "Ahora canta la nota más aguda que puedas y mantenla de forma estable durante 2 segundos.", "Chantez maintenant la note la plus aiguë possible et tenez-la de façon stable pendant 2 secondes.", "Ora canta la nota più alta che riesci e tienila ferma per 2 secondi.", "Agora cante a nota mais aguda que conseguir e sustente-a por 2 segundos.", "Zing nu de hoogste noot die je kunt en houd die 2 seconden stabiel aan.", "Теперь спойте самую высокую ноту, которую можете, и держите её ровно 2 секунды.", "Teraz zaśpiewaj najwyższy dźwięk, jaki potrafisz, i utrzymaj go równo przez 2 sekundy.", "Şimdi çıkarabildiğiniz en tiz notayı söyleyin ve 2 saniye boyunca sabit tutun.", "Sjung nu din högsta möjliga ton och håll den stadigt i 2 sekunder.", "次に、出せる限り高い音を歌い、2秒間まっすぐ伸ばしてください。", "이제 낼 수 있는 가장 높은 음을 2초 동안 안정적으로 유지하며 부르세요.", "现在唱出你能发出的最高音，并稳定保持 2 秒。")
T("Sing your lowest note", "Singe deinen tiefsten Ton", "Canta tu nota más grave", "Chantez votre note la plus grave", "Canta la tua nota più bassa", "Cante sua nota mais grave", "Zing je laagste noot", "Спойте самую низкую ноту", "Zaśpiewaj najniższy dźwięk", "En pes notanızı söyleyin", "Sjung din lägsta ton", "最低音を歌ってください", "최저음을 부르세요", "唱出你的最低音")
T("Sing your highest note", "Singe deinen höchsten Ton", "Canta tu nota más aguda", "Chantez votre note la plus aiguë", "Canta la tua nota più alta", "Cante sua nota mais aguda", "Zing je hoogste noot", "Спойте самую высокую ноту", "Zaśpiewaj najwyższy dźwięk", "En tiz notanızı söyleyin", "Sjung din högsta ton", "最高音を歌ってください", "최고음을 부르세요", "唱出你的最高音")
T("Listening…", "Höre zu …", "Escuchando…", "Écoute…", "In ascolto…", "Ouvindo…", "Luisteren…", "Слушаю…", "Słucham…", "Dinleniyor…", "Lyssnar…", "聞き取り中…", "듣는 중…", "正在聆听…")
T("Hold it", "Halten", "Mantenla", "Tenez", "Tienila", "Sustente", "Vasthouden", "Держите", "Trzymaj", "Tutun", "Håll kvar", "そのまま伸ばして", "유지하세요", "保持住")
T("Keep singing until the ring fills.", "Singe weiter, bis der Ring gefüllt ist.", "Sigue cantando hasta que el círculo se complete.", "Continuez à chanter jusqu’à ce que l’anneau soit rempli.", "Continua a cantare finché l’anello non si riempie.", "Continue cantando até o anel se completar.", "Blijf zingen tot de ring vol is.", "Пойте, пока кольцо не заполнится.", "Śpiewaj, aż pierścień się wypełni.", "Halka dolana kadar söylemeye devam edin.", "Fortsätt sjunga tills ringen fylls.", "リングが満ちるまで歌い続けてください。", "링이 가득 찰 때까지 계속 부르세요.", "持续演唱，直到圆环填满。")
T("Your Vocal Range", "Dein Stimmumfang", "Tu tesitura", "Votre tessiture", "La tua estensione vocale", "Sua extensão vocal", "Je stembereik", "Ваш диапазон голоса", "Twoja skala głosu", "Ses aralığınız", "Ditt röstomfång", "あなたの声域", "나의 음역대", "你的音域")
T("Try Again", "Nochmal versuchen", "Volver a intentar", "Réessayer", "Riprova", "Tentar de novo", "Opnieuw proberen", "Попробовать снова", "Spróbuj ponownie", "Yeniden dene", "Försök igen", "もう一度", "다시 시도", "重试")

# --- Voice types ---
T("Bass", "Bass", "Bajo", "Basse", "Basso", "Baixo", "Bas", "Бас", "Bas", "Bas", "Bas", "バス", "베이스", "男低音")
T("Baritone", "Bariton", "Barítono", "Baryton", "Baritono", "Barítono", "Bariton", "Баритон", "Baryton", "Bariton", "Baryton", "バリトン", "바리톤", "男中音")
T("Tenor", "Tenor", "Tenor", "Ténor", "Tenore", "Tenor", "Tenor", "Тенор", "Tenor", "Tenor", "Tenor", "テノール", "테너", "男高音")
T("Alto", "Alt", "Contralto", "Alto", "Contralto", "Contralto", "Alt", "Альт", "Alt", "Alto", "Alt", "アルト", "알토", "女低音")
T("Mezzo", "Mezzo", "Mezzo", "Mezzo", "Mezzo", "Mezzo", "Mezzo", "Меццо", "Mezzo", "Mezzo", "Mezzo", "メゾ", "메조", "女中音")
T("Soprano", "Sopran", "Soprano", "Soprano", "Soprano", "Soprano", "Sopraan", "Сопрано", "Sopran", "Soprano", "Sopran", "ソプラノ", "소프라노", "女高音")

# --- Instruments ---
T("Piano", "Klavier", "Piano", "Piano", "Pianoforte", "Piano", "Piano", "Фортепиано", "Fortepian", "Piyano", "Piano", "ピアノ", "피아노", "钢琴")
T("Sin Wave", "Sinuswelle", "Onda senoidal", "Onde sinusoïdale", "Onda sinusoidale", "Onda senoidal", "Sinusgolf", "Синусоида", "Fala sinusoidalna", "Sinüs dalgası", "Sinusvåg", "サイン波", "사인파", "正弦波")
T("Guitar", "Gitarre", "Guitarra", "Guitare", "Chitarra", "Violão", "Gitaar", "Гитара", "Gitara", "Gitar", "Gitarr", "ギター", "기타", "吉他")
