# Batch 12d: the paragraphs of the book lessons about vocal health (topic
# "Vocal Health" in BookLessons.json). Medical wording follows what the NIDCD
# pages say and no further: where they say "see a doctor", so do these.
from trbase import T

# --- Stay Hydrated ---
T("Staying hydrated is one of the simplest ways to look after your voice. Drink plenty of water, especially when you exercise. If you drink caffeinated drinks or alcohol, balance them with plenty of water.",
  "Genug zu trinken ist eine der einfachsten Möglichkeiten, deine Stimme zu pflegen. Trink viel Wasser, besonders wenn du Sport treibst. Wenn du koffeinhaltige Getränke oder Alkohol trinkst, gleiche das mit reichlich Wasser aus.",
  "Mantenerte hidratado es una de las formas más sencillas de cuidar tu voz. Bebe mucha agua, sobre todo cuando hagas ejercicio. Si tomas bebidas con cafeína o alcohol, compénsalas con abundante agua.",
  "Bien vous hydrater est l’un des moyens les plus simples de prendre soin de votre voix. Buvez beaucoup d’eau, surtout quand vous faites du sport. Si vous buvez des boissons caféinées ou de l’alcool, compensez avec beaucoup d’eau.",
  "Restare idratati è uno dei modi più semplici per prendersi cura della voce. Bevi molta acqua, soprattutto quando fai attività fisica. Se bevi bevande con caffeina o alcolici, compensali con molta acqua.",
  "Manter-se hidratado é uma das formas mais simples de cuidar da voz. Beba bastante água, principalmente quando se exercitar. Se você toma bebidas com cafeína ou álcool, compense com bastante água.",
  "Genoeg drinken is een van de eenvoudigste manieren om voor je stem te zorgen. Drink veel water, vooral als je sport. Drink je cafeïnehoudende dranken of alcohol, compenseer dat dan met veel water.",
  "Достаточное количество воды относится к самым простым способам заботы о голосе. Пейте много воды, особенно во время физических нагрузок. Если вы пьёте напитки с кофеином или алкоголь, восполняйте их большим количеством воды.",
  "Odpowiednie nawodnienie to jeden z najprostszych sposobów dbania o głos. Pij dużo wody, zwłaszcza podczas ćwiczeń fizycznych. Jeśli pijesz napoje z kofeiną lub alkohol, równoważ je dużą ilością wody.",
  "Yeterince sıvı almak, sesinize bakmanın en basit yollarından biridir. Özellikle egzersiz yaparken bol su için. Kafeinli içecekler ya da alkol tüketiyorsanız bunu bol suyla dengeleyin.",
  "Att dricka tillräckligt är ett av de enklaste sätten att ta hand om rösten. Drick mycket vatten, särskilt när du tränar. Om du dricker koffeinhaltiga drycker eller alkohol, balansera dem med rikligt med vatten.",
  "十分に水分をとることは、声をいたわるいちばん簡単な方法のひとつです。特に運動するときは、水をたっぷり飲みましょう。カフェイン入りの飲み物やお酒を飲むときは、そのぶん水もたっぷり飲むようにします。",
  "수분을 충분히 섭취하는 것은 목소리를 돌보는 가장 간단한 방법 중 하나입니다. 특히 운동할 때는 물을 충분히 마시세요. 카페인 음료나 술을 마신다면 물을 넉넉히 마셔 균형을 맞추세요.",
  "保持水分充足是保护嗓音最简单的方法之一。多喝水，尤其是在运动时。如果你喝含咖啡因的饮料或酒，要多喝水来平衡。",
  "الحفاظ على ترطيب جسمك من أبسط الطرق للعناية بصوتك. اشرب الكثير من الماء، خاصة عند ممارسة الرياضة. وإذا كنت تشرب مشروبات تحتوي على الكافيين أو الكحول، فوازنها بكمية وافرة من الماء.")
T("Give your voice “vocal naps”: short breaks to rest it throughout the day.",
  "Gönn deiner Stimme „Stimmpausen“: kurze Ruhephasen über den Tag verteilt.",
  "Dale a tu voz «siestas vocales»: descansos breves a lo largo del día.",
  "Accordez à votre voix des « siestes vocales » : de courtes pauses pour la reposer au fil de la journée.",
  "Concedi alla voce dei “sonnellini vocali”: brevi pause per farla riposare durante la giornata.",
  "Dê à sua voz “cochilos vocais”: pausas curtas para descansá-la ao longo do dia.",
  "Geef je stem ‘stemdutjes’: korte pauzes om hem gedurende de dag rust te geven.",
  "Устраивайте голосу «тихий час»: короткие перерывы для отдыха в течение дня.",
  "Dawaj głosowi „drzemki”: krótkie przerwy na odpoczynek w ciągu dnia.",
  "Sesinize “ses molaları” verin: gün içinde onu dinlendirmek için kısa aralar.",
  "Ge rösten ”röstvilor”: korta pauser under dagen då den får vila.",
  "声に「お昼寝」をさせましょう。1日の中でこまめに声を休ませる短い休憩のことです。",
  "목소리에 “낮잠”을 주세요. 하루 중 틈틈이 목소리를 쉬게 하는 짧은 휴식입니다.",
  "给嗓子来点“声音小憩”：一天中不时短暂地让它休息。",
  "امنح صوتك «قيلولات صوتية»: فترات راحة قصيرة على مدار اليوم.")
T("Use a humidifier at home, especially in winter or if you live in a dry climate. A humidity of about 30 percent is recommended.",
  "Nutze zu Hause einen Luftbefeuchter, besonders im Winter oder wenn du in einem trockenen Klima lebst. Empfohlen wird eine Luftfeuchtigkeit von etwa 30 Prozent.",
  "Usa un humidificador en casa, sobre todo en invierno o si vives en un clima seco. Se recomienda una humedad de alrededor del 30 por ciento.",
  "Utilisez un humidificateur à la maison, surtout en hiver ou si vous vivez sous un climat sec. Une humidité d’environ 30 pour cent est recommandée.",
  "Usa un umidificatore in casa, soprattutto d’inverno o se vivi in un clima secco. Si consiglia un’umidità di circa il 30 per cento.",
  "Use um umidificador em casa, principalmente no inverno ou se você mora em um lugar de clima seco. Recomenda-se uma umidade de cerca de 30 por cento.",
  "Gebruik thuis een luchtbevochtiger, vooral in de winter of als je in een droog klimaat woont. Een luchtvochtigheid van ongeveer 30 procent wordt aanbevolen.",
  "Пользуйтесь дома увлажнителем воздуха, особенно зимой или если вы живёте в сухом климате. Рекомендуется влажность около 30 процентов.",
  "Używaj w domu nawilżacza powietrza, zwłaszcza zimą lub jeśli mieszkasz w suchym klimacie. Zalecana wilgotność wynosi około 30 procent.",
  "Özellikle kışın ya da kuru bir iklimde yaşıyorsanız evde nemlendirici kullanın. Yaklaşık yüzde 30 nem önerilir.",
  "Använd en luftfuktare hemma, särskilt på vintern eller om du bor i ett torrt klimat. En luftfuktighet på omkring 30 procent rekommenderas.",
  "特に冬や乾燥した地域に住んでいる場合は、家で加湿器を使いましょう。湿度はおよそ30パーセントが推奨されています。",
  "특히 겨울이나 건조한 기후에서 산다면 집에서 가습기를 사용하세요. 습도는 약 30퍼센트가 권장됩니다.",
  "在家使用加湿器，尤其是在冬天或气候干燥的地方。建议湿度保持在 30% 左右。",
  "استخدم جهاز ترطيب في المنزل، خاصة في الشتاء أو إذا كنت تعيش في مناخ جاف. ويُنصح بنسبة رطوبة تبلغ نحو 30 بالمئة.")
T("Some medications, including some common cold and allergy medications, can dry out your vocal folds. If you have voice problems, ask your doctor which medications are safest for you.",
  "Manche Medikamente, darunter einige gängige Mittel gegen Erkältung und Allergien, können die Stimmlippen austrocknen. Wenn du Stimmprobleme hast, frag deinen Arzt, welche Medikamente für dich am sichersten sind.",
  "Algunos medicamentos, incluidos algunos de uso común para el resfriado y la alergia, pueden resecar las cuerdas vocales. Si tienes problemas de voz, pregunta a tu médico qué medicamentos son más seguros para ti.",
  "Certains médicaments, dont certains traitements courants contre le rhume et les allergies, peuvent assécher les cordes vocales. Si vous avez des problèmes de voix, demandez à votre médecin quels médicaments sont les plus sûrs pour vous.",
  "Alcuni farmaci, tra cui alcuni comuni rimedi contro raffreddore e allergie, possono seccare le corde vocali. Se hai problemi di voce, chiedi al medico quali farmaci sono più sicuri per te.",
  "Alguns medicamentos, incluindo alguns remédios comuns para resfriado e alergia, podem ressecar as pregas vocais. Se você tem problemas de voz, pergunte ao seu médico quais medicamentos são mais seguros para você.",
  "Sommige medicijnen, waaronder enkele veelgebruikte middelen tegen verkoudheid en allergie, kunnen je stembanden uitdrogen. Heb je stemproblemen, vraag dan je arts welke medicijnen het veiligst voor je zijn.",
  "Некоторые лекарства, в том числе ряд распространённых средств от простуды и аллергии, могут пересушивать голосовые складки. Если у вас проблемы с голосом, спросите врача, какие лекарства для вас безопаснее всего.",
  "Niektóre leki, w tym część popularnych leków na przeziębienie i alergię, mogą wysuszać fałdy głosowe. Jeśli masz problemy z głosem, zapytaj lekarza, które leki są dla ciebie najbezpieczniejsze.",
  "Bazı yaygın soğuk algınlığı ve alerji ilaçları da dahil olmak üzere bazı ilaçlar ses tellerinizi kurutabilir. Ses sorunlarınız varsa hangi ilaçların sizin için en güvenli olduğunu doktorunuza sorun.",
  "Vissa läkemedel, bland annat en del vanliga medel mot förkylning och allergi, kan torka ut stämbanden. Om du har röstproblem, fråga din läkare vilka läkemedel som är säkrast för dig.",
  "一般的なかぜ薬やアレルギー薬の一部を含め、声帯を乾燥させる薬があります。声のトラブルがある場合は、どの薬がいちばん安全か医師に相談しましょう。",
  "흔히 쓰는 감기약과 알레르기약 일부를 포함해, 어떤 약은 성대를 건조하게 만들 수 있습니다. 목소리에 문제가 있다면 어떤 약이 가장 안전한지 의사에게 물어보세요.",
  "有些药物，包括一些常用的感冒药和抗过敏药，可能会使声带变干。如果你有嗓音问题，请询问医生哪些药物对你最安全。",
  "بعض الأدوية، ومنها بعض أدوية الزكام والحساسية الشائعة، قد تُجفّف الطيّتين الصوتيتين. وإذا كانت لديك مشكلات في الصوت، فاسأل طبيبك عن أكثر الأدوية أمانًا لك.")

# --- Use Your Voice Wisely ---
T("Try not to overuse your voice. Avoid speaking or singing when your voice is hoarse or tired, and rest it when you are sick, since illness puts extra stress on your voice.",
  "Versuche, deine Stimme nicht zu überlasten. Vermeide Sprechen und Singen, wenn deine Stimme heiser oder müde ist, und schone sie, wenn du krank bist, denn Krankheit belastet die Stimme zusätzlich.",
  "Intenta no forzar demasiado la voz. Evita hablar o cantar cuando tengas la voz ronca o cansada, y déjala descansar cuando estés enfermo, porque la enfermedad supone un esfuerzo extra para la voz.",
  "Évitez de surmener votre voix. Ne parlez pas et ne chantez pas quand votre voix est enrouée ou fatiguée, et reposez-la quand vous êtes malade, car la maladie la sollicite davantage.",
  "Cerca di non affaticare troppo la voce. Evita di parlare o cantare quando la voce è rauca o stanca, e falla riposare quando sei malato, perché la malattia la mette ulteriormente sotto sforzo.",
  "Tente não usar demais a voz. Evite falar ou cantar quando ela estiver rouca ou cansada, e deixe-a descansar quando estiver doente, já que a doença sobrecarrega a voz.",
  "Probeer je stem niet te overbelasten. Praat of zing niet als je stem hees of moe is, en laat hem rusten als je ziek bent, want ziekte legt extra druk op je stem.",
  "Старайтесь не перегружать голос. Не говорите и не пойте, когда голос охрип или устал, и давайте ему отдохнуть во время болезни, потому что болезнь создаёт для голоса дополнительную нагрузку.",
  "Staraj się nie przeciążać głosu. Unikaj mówienia i śpiewania, gdy głos jest zachrypnięty lub zmęczony, i oszczędzaj go, gdy chorujesz, bo choroba dodatkowo go obciąża.",
  "Sesinizi aşırı kullanmamaya çalışın. Sesiniz kısık ya da yorgunken konuşmaktan ve şarkı söylemekten kaçının; hastalık sese ekstra yük bindirdiği için hastayken de sesinizi dinlendirin.",
  "Försök att inte överanstränga rösten. Undvik att prata eller sjunga när rösten är hes eller trött, och vila den när du är sjuk, eftersom sjukdom belastar rösten extra.",
  "声を使いすぎないようにしましょう。声がかれていたり疲れていたりするときは、話したり歌ったりするのを避けます。病気は声に余分な負担をかけるので、体調が悪いときも声を休ませましょう。",
  "목소리를 너무 많이 쓰지 않도록 하세요. 목이 쉬었거나 지쳤을 때는 말하거나 노래하지 말고, 아플 때는 목소리를 쉬게 하세요. 병은 목소리에 추가 부담을 주기 때문입니다.",
  "尽量不要过度用嗓。嗓子沙哑或疲劳时，避免说话或唱歌；生病时也要让嗓子休息，因为疾病会给嗓音带来额外负担。",
  "حاول ألا تُفرط في استخدام صوتك. تجنّب الكلام أو الغناء عندما يكون صوتك مبحوحًا أو متعبًا، وأرِحه عندما تمرض، لأن المرض يُلقي عبئًا إضافيًا على صوتك.")
T("Avoid the extremes of your voice, such as screaming or whispering: talking too loudly and talking too softly can both stress it. Try not to talk over loud noise, which strains your voice, and where you often need to speak to a room, a small microphone and speaker can help.",
  "Meide die Extreme deiner Stimme wie Schreien oder Flüstern: Zu lautes und zu leises Sprechen können sie beide belasten. Versuche, nicht gegen lauten Lärm anzureden, das strengt die Stimme an, und wo du oft vor einem Raum voller Leute sprechen musst, kann ein kleines Mikrofon mit Lautsprecher helfen.",
  "Evita los extremos de la voz, como gritar o susurrar: hablar demasiado alto y demasiado bajo pueden forzarla. Intenta no hablar por encima de mucho ruido, porque fuerza la voz, y si a menudo tienes que hablar ante una sala, un pequeño micrófono con altavoz puede ayudar.",
  "Évitez les extrêmes, comme crier ou chuchoter : parler trop fort et parler trop bas peuvent tous deux fatiguer la voix. Essayez de ne pas parler par-dessus un bruit fort, ce qui force la voix, et si vous devez souvent parler devant une salle, un petit micro et un haut-parleur peuvent aider.",
  "Evita gli estremi della voce, come urlare o sussurrare: parlare troppo forte e troppo piano possono entrambi affaticarla. Cerca di non parlare sopra un rumore forte, che sforza la voce, e dove devi spesso parlare davanti a una sala, un piccolo microfono con altoparlante può aiutare.",
  "Evite os extremos da voz, como gritar ou sussurrar: falar alto demais e baixo demais podem sobrecarregá-la. Tente não falar por cima de barulho alto, o que força a voz, e se você precisa falar com frequência para uma sala, um pequeno microfone com caixa de som pode ajudar.",
  "Vermijd de uitersten van je stem, zoals schreeuwen of fluisteren: te hard en te zacht praten kunnen hem allebei belasten. Probeer niet boven hard lawaai uit te praten, want dat forceert je stem, en waar je vaak voor een zaal moet spreken, kan een kleine microfoon met luidspreker helpen.",
  "Избегайте крайностей, например крика или шёпота: слишком громкая и слишком тихая речь одинаково нагружают голос. Старайтесь не перекрикивать сильный шум, это напрягает голос, а если вам часто приходится выступать перед залом, может помочь небольшой микрофон с колонкой.",
  "Unikaj skrajności, takich jak krzyk czy szept: zarówno zbyt głośne, jak i zbyt ciche mówienie obciąża głos. Staraj się nie przekrzykiwać głośnego hałasu, bo to nadwyręża głos, a jeśli często mówisz do całej sali, pomóc może mały mikrofon z głośnikiem.",
  "Bağırmak ya da fısıldamak gibi sesin uç noktalarından kaçının: çok yüksek sesle konuşmak da çok alçak sesle konuşmak da sesi zorlayabilir. Yüksek gürültünün üstüne çıkarak konuşmamaya çalışın, bu sesinizi zorlar; sık sık bir salona hitap etmeniz gerekiyorsa küçük bir mikrofon ve hoparlör yardımcı olabilir.",
  "Undvik röstens ytterligheter, som att skrika eller viska: att prata för högt och att prata för tyst kan båda anstränga den. Försök att inte prata över högt oväsen, det tar på rösten, och där du ofta behöver tala inför ett rum kan en liten mikrofon och högtalare hjälpa.",
  "叫んだりささやいたりといった、声の極端な使い方は避けましょう。大きすぎる声も小さすぎる声も、どちらも声に負担をかけます。大きな騒音に負けないように話すと声を酷使するので控えましょう。大勢の前で話す機会が多いなら、小型のマイクとスピーカーが役に立ちます。",
  "소리 지르기나 속삭이기처럼 목소리를 극단적으로 쓰는 것은 피하세요. 너무 크게 말하는 것도, 너무 작게 말하는 것도 목소리에 부담을 줍니다. 시끄러운 소음 위로 말하면 목이 무리하니 피하고, 여러 사람 앞에서 자주 말해야 한다면 작은 마이크와 스피커가 도움이 됩니다.",
  "避免极端的用嗓方式，比如尖叫或耳语：说话太大声和太小声都会给嗓子带来压力。尽量不要在很吵的环境里提高嗓门说话，那会让嗓子吃力；如果你经常需要对着满屋子的人讲话，一个小麦克风和音箱会有帮助。",
  "تجنّب الحدود القصوى لصوتك، مثل الصراخ أو الهمس: فالكلام بصوت مرتفع جدًا أو منخفض جدًا كلاهما يُجهده. وحاول ألا تتكلم فوق ضجيج عالٍ لأن ذلك يُرهق صوتك، وإذا كنت تحتاج كثيرًا إلى التحدث أمام قاعة، فقد يساعدك ميكروفون صغير مع مكبّر صوت.")
T("Instead of clearing your throat again and again, try taking a small sip of water or swallowing. Frequent throat clearing can itself be a sign of a voice problem, so mention it to your doctor if it keeps happening.",
  "Statt dich immer wieder zu räuspern, nimm lieber einen kleinen Schluck Wasser oder schlucke. Häufiges Räuspern kann selbst ein Zeichen für ein Stimmproblem sein, also sprich deinen Arzt darauf an, wenn es nicht aufhört.",
  "En lugar de carraspear una y otra vez, prueba a dar un pequeño sorbo de agua o a tragar saliva. Carraspear con frecuencia puede ser en sí una señal de un problema de voz, así que coméntaselo a tu médico si sigue ocurriendo.",
  "Au lieu de vous racler la gorge encore et encore, essayez de boire une petite gorgée d’eau ou de déglutir. Se racler souvent la gorge peut en soi être le signe d’un problème de voix : parlez-en à votre médecin si cela continue.",
  "Invece di schiarirti la gola in continuazione, prova a bere un piccolo sorso d’acqua o a deglutire. Schiarirsi spesso la gola può essere di per sé un segnale di un problema alla voce, quindi parlane con il medico se continua.",
  "Em vez de pigarrear várias vezes, tente tomar um pequeno gole de água ou engolir. Pigarrear com frequência pode ser, por si só, um sinal de problema de voz, então fale com seu médico se isso continuar.",
  "Probeer in plaats van steeds je keel te schrapen een klein slokje water te nemen of te slikken. Vaak je keel schrapen kan zelf een teken van een stemprobleem zijn, dus vertel het je arts als het blijft gebeuren.",
  "Вместо того чтобы снова и снова откашливаться, попробуйте сделать маленький глоток воды или просто сглотнуть. Частое откашливание само по себе может быть признаком проблемы с голосом, поэтому скажите об этом врачу, если оно не проходит.",
  "Zamiast raz po raz odchrząkiwać, spróbuj wypić mały łyk wody albo przełknąć ślinę. Częste odchrząkiwanie samo w sobie może być oznaką problemu z głosem, więc powiedz o nim lekarzowi, jeśli się powtarza.",
  "Boğazınızı tekrar tekrar temizlemek yerine küçük bir yudum su almayı ya da yutkunmayı deneyin. Sık boğaz temizleme kendi başına bir ses sorununun belirtisi olabilir; devam ederse doktorunuza söyleyin.",
  "I stället för att harkla dig om och om igen, prova att ta en liten klunk vatten eller svälja. Att ofta harkla sig kan i sig vara ett tecken på ett röstproblem, så nämn det för din läkare om det fortsätter.",
  "何度も咳ばらいをする代わりに、水を少し飲むか、つばを飲み込んでみましょう。頻繁な咳ばらいはそれ自体が声のトラブルのサインであることもあるので、続くようなら医師に伝えましょう。",
  "헛기침을 자꾸 하는 대신 물을 조금 마시거나 침을 삼켜 보세요. 잦은 헛기침 자체가 목소리 문제의 신호일 수 있으니, 계속된다면 의사에게 말하세요.",
  "与其一次又一次地清嗓子，不如小口喝点水或吞咽一下。频繁清嗓子本身就可能是嗓音问题的信号，如果一直这样，请告诉医生。",
  "بدل أن تتنحنح مرة بعد مرة، جرّب أن تأخذ رشفة صغيرة من الماء أو أن تبلع ريقك. فكثرة التنحنح قد تكون في حد ذاتها علامة على مشكلة في الصوت، لذا أخبر طبيبك إذا استمرت.")
T("Also watch your habits outside of singing. Holding a phone between your head and shoulder for a long time can cause tension in your neck. And if you rely on your voice a lot, a speech-language pathologist experienced with voice problems can teach you how to use it in a healthy way.",
  "Achte auch auf deine Gewohnheiten abseits des Singens. Wenn du ein Telefon lange zwischen Kopf und Schulter klemmst, kann das deinen Nacken verspannen. Und wenn du stark auf deine Stimme angewiesen bist, kann dir ein in Stimmproblemen erfahrener Logopäde zeigen, wie du sie gesund einsetzt.",
  "Fíjate también en tus hábitos fuera del canto. Sujetar el teléfono entre la cabeza y el hombro durante mucho tiempo puede tensar el cuello. Y si dependes mucho de tu voz, un logopeda con experiencia en problemas de voz puede enseñarte a usarla de forma saludable.",
  "Surveillez aussi vos habitudes en dehors du chant. Tenir longtemps un téléphone entre la tête et l’épaule peut créer des tensions dans la nuque. Et si vous utilisez beaucoup votre voix, un orthophoniste expérimenté dans les troubles de la voix peut vous apprendre à vous en servir sainement.",
  "Fai attenzione anche alle abitudini al di fuori del canto. Tenere a lungo il telefono tra la testa e la spalla può causare tensione al collo. E se usi molto la voce, un logopedista esperto di problemi vocali può insegnarti a usarla in modo sano.",
  "Preste atenção também aos hábitos fora do canto. Segurar o telefone entre a cabeça e o ombro por muito tempo pode causar tensão no pescoço. E se você depende muito da voz, um fonoaudiólogo com experiência em problemas de voz pode ensinar você a usá-la de forma saudável.",
  "Let ook op je gewoonten buiten het zingen. Een telefoon lang tussen je hoofd en schouder klemmen kan spanning in je nek geven. En als je veel op je stem vertrouwt, kan een logopedist met ervaring in stemproblemen je leren hem op een gezonde manier te gebruiken.",
  "Следите и за привычками вне пения. Если долго держать телефон между головой и плечом, может возникнуть напряжение в шее. А если ваш голос много работает, логопед, имеющий опыт работы с нарушениями голоса, научит пользоваться им бережно.",
  "Zwracaj też uwagę na nawyki poza śpiewem. Długie trzymanie telefonu między głową a ramieniem może wywołać napięcie karku. A jeśli dużo korzystasz z głosu, logopeda doświadczony w problemach z głosem nauczy cię, jak używać go w zdrowy sposób.",
  "Şarkı söylemenin dışındaki alışkanlıklarınıza da dikkat edin. Telefonu uzun süre başınızla omzunuz arasında tutmak boynunuzda gerginliğe yol açabilir. Sesinize çok güveniyorsanız, ses sorunlarında deneyimli bir dil ve konuşma terapisti onu sağlıklı kullanmayı size öğretebilir.",
  "Tänk också på dina vanor utanför sången. Att länge hålla en telefon mellan huvudet och axeln kan ge spänningar i nacken. Och om du använder rösten mycket kan en logoped med erfarenhet av röstproblem lära dig att använda den på ett hälsosamt sätt.",
  "歌以外の習慣にも気をつけましょう。電話を頭と肩のあいだに長くはさんでいると、首に力みが生じることがあります。また、声をよく使う人は、声のトラブルに詳しい言語聴覚士に健康的な声の使い方を教えてもらうこともできます。",
  "노래 밖의 습관도 살펴보세요. 전화기를 머리와 어깨 사이에 오래 끼고 있으면 목에 긴장이 생길 수 있습니다. 그리고 목소리를 많이 쓴다면, 음성 문제에 경험이 많은 언어치료사에게 건강하게 목소리를 쓰는 법을 배울 수 있습니다.",
  "也要注意唱歌以外的习惯。长时间把电话夹在头和肩膀之间，会让脖子紧张。如果你很依赖自己的嗓音，一位在嗓音问题方面有经验的言语治疗师可以教你健康地用嗓。",
  "انتبه أيضًا لعاداتك خارج الغناء. فإمساك الهاتف بين رأسك وكتفك مدة طويلة قد يسبب توترًا في رقبتك. وإذا كنت تعتمد على صوتك كثيرًا، فبإمكان أخصائي في علاج النطق واللغة لديه خبرة بمشكلات الصوت أن يعلّمك استخدامه بطريقة صحية.")

# --- Healthy Habits ---
T("Don't smoke, and avoid secondhand smoke. Smoke irritates the vocal folds, and cancer of the vocal folds is seen most often in people who smoke.",
  "Rauche nicht und meide Passivrauch. Rauch reizt die Stimmlippen, und Stimmlippenkrebs tritt am häufigsten bei Menschen auf, die rauchen.",
  "No fumes y evita el humo ajeno. El humo irrita las cuerdas vocales, y el cáncer de cuerdas vocales se da con más frecuencia en personas que fuman.",
  "Ne fumez pas et évitez le tabagisme passif. La fumée irrite les cordes vocales, et le cancer des cordes vocales touche le plus souvent les fumeurs.",
  "Non fumare ed evita il fumo passivo. Il fumo irrita le corde vocali, e il tumore delle corde vocali si riscontra più spesso nei fumatori.",
  "Não fume e evite o fumo passivo. A fumaça irrita as pregas vocais, e o câncer das pregas vocais é mais comum em pessoas que fumam.",
  "Rook niet en vermijd meeroken. Rook irriteert de stembanden, en stembandkanker komt het vaakst voor bij mensen die roken.",
  "Не курите и избегайте пассивного курения. Дым раздражает голосовые складки, а рак голосовых складок чаще всего встречается у курящих людей.",
  "Nie pal i unikaj biernego palenia. Dym podrażnia fałdy głosowe, a rak fałdów głosowych najczęściej występuje u osób palących.",
  "Sigara içmeyin ve pasif içicilikten kaçının. Duman ses tellerini tahriş eder ve ses teli kanseri en sık sigara içenlerde görülür.",
  "Rök inte, och undvik passiv rökning. Rök irriterar stämbanden, och cancer i stämbanden ses oftast hos personer som röker.",
  "たばこを吸わず、受動喫煙も避けましょう。煙は声帯を刺激し、声帯のがんは喫煙者にもっとも多く見られます。",
  "담배를 피우지 말고 간접흡연도 피하세요. 연기는 성대를 자극하며, 성대암은 흡연자에게서 가장 많이 나타납니다.",
  "不要吸烟，也要避免二手烟。烟雾会刺激声带，而声带癌最常见于吸烟者。",
  "لا تدخّن، وتجنّب التدخين السلبي. فالدخان يهيّج الطيّتين الصوتيتين، وسرطان الطيّتين الصوتيتين أكثر ما يُرى لدى المدخنين.")
T("Eat plenty of whole grains, fruits and vegetables. They contain vitamins A, E and C and help keep the mucous membranes that line your throat healthy.",
  "Iss reichlich Vollkornprodukte, Obst und Gemüse. Sie enthalten die Vitamine A, E und C und helfen, die Schleimhäute in deinem Hals gesund zu halten.",
  "Come muchos cereales integrales, frutas y verduras. Contienen vitaminas A, E y C y ayudan a mantener sanas las mucosas que recubren la garganta.",
  "Mangez beaucoup de céréales complètes, de fruits et de légumes. Ils contiennent des vitamines A, E et C et aident à garder en bonne santé les muqueuses qui tapissent la gorge.",
  "Mangia molti cereali integrali, frutta e verdura. Contengono le vitamine A, E e C e aiutano a mantenere sane le mucose che rivestono la gola.",
  "Coma bastante grãos integrais, frutas e legumes. Eles contêm vitaminas A, E e C e ajudam a manter saudáveis as mucosas que revestem a garganta.",
  "Eet veel volkorenproducten, fruit en groente. Ze bevatten de vitaminen A, E en C en helpen de slijmvliezen in je keel gezond te houden.",
  "Ешьте побольше цельнозерновых продуктов, фруктов и овощей. Они содержат витамины A, E и C и помогают сохранять здоровыми слизистые оболочки горла.",
  "Jedz dużo produktów pełnoziarnistych, owoców i warzyw. Zawierają witaminy A, E i C i pomagają utrzymać w zdrowiu błony śluzowe wyściełające gardło.",
  "Bol bol tam tahıl, meyve ve sebze yiyin. Bunlar A, E ve C vitaminleri içerir ve boğazınızı kaplayan mukozanın sağlıklı kalmasına yardımcı olur.",
  "Ät gott om fullkorn, frukt och grönsaker. De innehåller vitamin A, E och C och hjälper till att hålla slemhinnorna i halsen friska.",
  "全粒穀物、果物、野菜をたっぷりとりましょう。これらにはビタミンA、E、Cが含まれ、のどの内側をおおう粘膜を健康に保つ助けになります。",
  "통곡물, 과일, 채소를 충분히 드세요. 여기에는 비타민 A, E, C가 들어 있어 목 안쪽을 덮고 있는 점막을 건강하게 유지하는 데 도움이 됩니다.",
  "多吃全谷物、水果和蔬菜。它们含有维生素 A、E 和 C，有助于保持喉咙黏膜的健康。",
  "أكثِر من الحبوب الكاملة والفواكه والخضراوات. فهي تحتوي على فيتامينات A وE وC، وتساعد على الحفاظ على صحة الأغشية المخاطية المبطِّنة لحلقك.")
T("Stomach acid that rises into your throat can irritate your vocal folds and make you hoarse. If spicy foods give you heartburn, cut back on them, and if you have heartburn often, talk to your doctor about changes to your diet or medications that can help.",
  "Magensäure, die bis in den Hals aufsteigt, kann die Stimmlippen reizen und dich heiser machen. Wenn scharfes Essen dir Sodbrennen bereitet, iss weniger davon, und wenn du oft Sodbrennen hast, sprich mit deinem Arzt über eine Ernährungsumstellung oder Medikamente, die helfen können.",
  "El ácido del estómago que sube hasta la garganta puede irritar las cuerdas vocales y dejarte ronco. Si las comidas picantes te producen acidez, redúcelas, y si tienes acidez a menudo, habla con tu médico sobre cambios en la dieta o medicamentos que puedan ayudar.",
  "L’acide gastrique qui remonte dans la gorge peut irriter les cordes vocales et vous enrouer. Si les plats épicés vous donnent des brûlures d’estomac, réduisez-les, et si vous en avez souvent, parlez à votre médecin de changements alimentaires ou de médicaments qui peuvent aider.",
  "L’acido dello stomaco che risale fino alla gola può irritare le corde vocali e renderti rauco. Se i cibi piccanti ti danno bruciore di stomaco, riducili, e se hai spesso bruciore, parla con il medico di cambiamenti nella dieta o di farmaci che possono aiutare.",
  "O ácido do estômago que sobe até a garganta pode irritar as pregas vocais e deixar você rouco. Se comidas apimentadas causam azia, diminua-as, e se você tem azia com frequência, converse com seu médico sobre mudanças na alimentação ou medicamentos que podem ajudar.",
  "Maagzuur dat tot in je keel omhoogkomt, kan je stembanden irriteren en je hees maken. Krijg je van pittig eten brandend maagzuur, eet er dan minder van, en heb je vaak last van brandend maagzuur, praat dan met je arts over aanpassingen in je voeding of medicijnen die kunnen helpen.",
  "Желудочная кислота, поднимающаяся в горло, может раздражать голосовые складки и вызывать осиплость. Если от острой еды у вас изжога, ешьте её меньше, а если изжога бывает часто, поговорите с врачом об изменениях в питании или о лекарствах, которые могут помочь.",
  "Kwas żołądkowy, który cofa się do gardła, może podrażniać fałdy głosowe i powodować chrypkę. Jeśli po ostrych potrawach masz zgagę, ogranicz je, a jeśli zgaga zdarza się często, porozmawiaj z lekarzem o zmianach w diecie lub lekach, które mogą pomóc.",
  "Boğazınıza kadar çıkan mide asidi ses tellerinizi tahriş edip sesinizi kısabilir. Acılı yiyecekler size yanma yapıyorsa onları azaltın; sık sık mide yanması yaşıyorsanız, beslenmenizde yapabileceğiniz değişiklikleri ya da işe yarayabilecek ilaçları doktorunuzla konuşun.",
  "Magsyra som stiger upp i halsen kan irritera stämbanden och göra dig hes. Om stark mat ger dig halsbränna, ät mindre av den, och om du ofta har halsbränna, prata med din läkare om ändrade matvanor eller läkemedel som kan hjälpa.",
  "胃酸がのどまで上がってくると、声帯が刺激されて声がかれることがあります。辛い食べ物で胸やけが起きるなら控えめにし、胸やけがよく起きる場合は、食事の見直しや役立つ薬について医師に相談しましょう。",
  "목까지 올라오는 위산은 성대를 자극해 목이 쉬게 할 수 있습니다. 매운 음식을 먹으면 속이 타는 듯하다면 줄이고, 속쓰림이 잦다면 식단 변화나 도움이 되는 약에 대해 의사와 상담하세요.",
  "反流到喉咙的胃酸会刺激声带，让声音沙哑。如果辛辣食物会让你烧心，就少吃一些；如果经常烧心，请和医生谈谈调整饮食或可以帮助缓解的药物。",
  "قد يهيّج حمض المعدة الذي يصعد إلى حلقك الطيّتين الصوتيتين ويسبب بحّة الصوت. إذا كانت الأطعمة الحارة تسبب لك حرقة المعدة فقلّل منها، وإذا كانت الحرقة تتكرر كثيرًا فتحدّث مع طبيبك عن تغييرات في نظامك الغذائي أو أدوية قد تساعد.")
T("Get enough rest, since physical tiredness has a negative effect on your voice. Exercise regularly: it builds stamina and muscle tone, which help with good posture and breathing. Wash your hands often to avoid colds and flu, and skip mouthwashes and gargles that contain alcohol or irritating chemicals.",
  "Sorge für ausreichend Ruhe, denn körperliche Müdigkeit wirkt sich negativ auf die Stimme aus. Bewege dich regelmäßig: Das stärkt Ausdauer und Muskelspannung, was einer guten Haltung und Atmung zugutekommt. Wasch dir oft die Hände, um Erkältungen und Grippe vorzubeugen, und verzichte auf Mundspülungen und Gurgelmittel mit Alkohol oder reizenden Chemikalien.",
  "Descansa lo suficiente, ya que el cansancio físico afecta negativamente a la voz. Haz ejercicio con regularidad: aumenta la resistencia y el tono muscular, que ayudan a mantener una buena postura y respiración. Lávate las manos a menudo para evitar resfriados y gripe, y evita los enjuagues bucales y gárgaras que contengan alcohol o sustancias químicas irritantes.",
  "Reposez-vous suffisamment, car la fatigue physique a un effet négatif sur la voix. Faites de l’exercice régulièrement : cela développe l’endurance et le tonus musculaire, qui favorisent une bonne posture et une bonne respiration. Lavez-vous souvent les mains pour éviter rhumes et grippe, et évitez les bains de bouche et gargarismes contenant de l’alcool ou des produits chimiques irritants.",
  "Riposa a sufficienza, perché la stanchezza fisica ha un effetto negativo sulla voce. Fai attività fisica con regolarità: aumenta resistenza e tono muscolare, che aiutano una buona postura e una buona respirazione. Lavati spesso le mani per evitare raffreddori e influenza, e rinuncia a collutori e gargarismi che contengono alcol o sostanze chimiche irritanti.",
  "Descanse o suficiente, já que o cansaço físico tem efeito negativo na voz. Faça exercícios com regularidade: eles aumentam a resistência e o tônus muscular, que ajudam na boa postura e na respiração. Lave as mãos com frequência para evitar resfriados e gripe, e dispense enxaguantes bucais e gargarejos com álcool ou substâncias químicas irritantes.",
  "Neem genoeg rust, want lichamelijke vermoeidheid heeft een negatief effect op je stem. Beweeg regelmatig: dat bouwt uithoudingsvermogen en spierspanning op, wat helpt bij een goede houding en ademhaling. Was vaak je handen om verkoudheid en griep te voorkomen, en sla mondspoelingen en gorgelmiddelen met alcohol of irriterende chemicaliën over.",
  "Хорошо отдыхайте, ведь физическая усталость плохо сказывается на голосе. Регулярно занимайтесь спортом: это развивает выносливость и мышечный тонус, которые помогают держать осанку и правильно дышать. Чаще мойте руки, чтобы не заболеть простудой или гриппом, и не пользуйтесь ополаскивателями и полосканиями со спиртом или раздражающими веществами.",
  "Wysypiaj się i odpoczywaj, bo zmęczenie fizyczne źle wpływa na głos. Ćwicz regularnie: to buduje wytrzymałość i napięcie mięśni, które pomagają w dobrej postawie i oddychaniu. Często myj ręce, żeby uniknąć przeziębienia i grypy, i nie używaj płynów do płukania ust ani płukanek zawierających alkohol lub drażniące substancje.",
  "Yeterince dinlenin; fiziksel yorgunluk sesinizi olumsuz etkiler. Düzenli egzersiz yapın: dayanıklılığı ve kas tonusunu artırır, bu da iyi duruş ve nefese yardımcı olur. Soğuk algınlığı ve gripten korunmak için ellerinizi sık yıkayın; alkol ya da tahriş edici kimyasallar içeren ağız gargaralarını kullanmayın.",
  "Vila tillräckligt, eftersom fysisk trötthet påverkar rösten negativt. Motionera regelbundet: det bygger upp uthållighet och muskeltonus, som hjälper till med god hållning och andning. Tvätta händerna ofta för att undvika förkylning och influensa, och hoppa över munskölj och gurgelvatten som innehåller alkohol eller irriterande kemikalier.",
  "体の疲れは声に悪影響を与えるので、しっかり休息をとりましょう。定期的に運動すると、持久力や筋肉の張りがつき、よい姿勢と呼吸の助けになります。かぜやインフルエンザを防ぐために手をこまめに洗い、アルコールや刺激の強い化学物質を含むマウスウォッシュやうがい薬は避けましょう。",
  "몸이 피곤하면 목소리에 나쁜 영향을 주므로 충분히 쉬세요. 규칙적으로 운동하세요. 운동은 지구력과 근육의 탄력을 길러 좋은 자세와 호흡에 도움이 됩니다. 감기와 독감을 피하려면 손을 자주 씻고, 알코올이나 자극적인 화학 물질이 든 구강청결제와 가글은 쓰지 마세요.",
  "保证充足的休息，因为身体疲劳会对嗓音产生不良影响。规律锻炼：锻炼能增强耐力和肌肉张力，有助于保持良好的姿势和呼吸。经常洗手以预防感冒和流感，并且不要使用含酒精或刺激性化学物质的漱口水。",
  "احصل على قسط كافٍ من الراحة، لأن التعب الجسدي يؤثر سلبًا في صوتك. ومارس الرياضة بانتظام: فهي تبني القدرة على التحمل وتوتر العضلات، مما يساعد على الوقفة الجيدة والتنفس الجيد. واغسل يديك كثيرًا لتتجنب الزكام والإنفلونزا، وتجنّب غسولات الفم والغرغرة التي تحتوي على الكحول أو مواد كيميائية مهيّجة.")

# --- When to See a Doctor ---
T("A hoarse voice sounds breathy, raspy or strained, or is softer or lower than usual, and your throat may feel scratchy. Hoarseness is often a sign of a problem with the vocal folds.",
  "Eine heisere Stimme klingt behaucht, rau oder angestrengt oder ist leiser oder tiefer als sonst, und dein Hals kann sich kratzig anfühlen. Heiserkeit ist oft ein Zeichen für ein Problem mit den Stimmlippen.",
  "Una voz ronca suena aireada, áspera o forzada, o es más débil o más grave de lo habitual, y la garganta puede notarse irritada. La ronquera suele ser señal de un problema en las cuerdas vocales.",
  "Une voix enrouée paraît voilée, rauque ou forcée, ou plus faible ou plus grave que d’habitude, et la gorge peut gratter. L’enrouement est souvent le signe d’un problème au niveau des cordes vocales.",
  "Una voce rauca suona soffiata, ruvida o forzata, oppure è più debole o più grave del solito, e la gola può pizzicare. La raucedine è spesso il segnale di un problema alle corde vocali.",
  "Uma voz rouca soa soprosa, áspera ou forçada, ou fica mais fraca ou mais grave que o normal, e a garganta pode arranhar. A rouquidão costuma ser sinal de um problema nas pregas vocais.",
  "Een hese stem klinkt ademig, schor of geforceerd, of is zachter of lager dan normaal, en je keel kan kriebelen. Heesheid is vaak een teken van een probleem met de stembanden.",
  "Охрипший голос звучит с придыханием, сипло или натужно, либо тише или ниже обычного, а в горле может першить. Осиплость часто указывает на проблему с голосовыми складками.",
  "Zachrypnięty głos brzmi na wydechu, szorstko lub z wysiłkiem albo jest cichszy lub niższy niż zwykle, a w gardle może drapać. Chrypka jest często oznaką problemu z fałdami głosowymi.",
  "Kısık bir ses nefesli, hırıltılı ya da zorlanmış çıkar veya her zamankinden daha kısık ya da daha kalın olur; boğazınız da kaşınıyor gibi hissedebilir. Ses kısıklığı çoğu zaman ses tellerindeki bir sorunun belirtisidir.",
  "En hes röst låter luftig, sträv eller ansträngd, eller är svagare eller mörkare än vanligt, och halsen kan kännas skrovlig. Heshet är ofta ett tecken på ett problem med stämbanden.",
  "声がかれていると、息がもれたような声、ガサガサした声、苦しそうな声になったり、いつもより小さく低い声になったりし、のどがイガイガすることもあります。声がれは、声帯のトラブルのサインであることが多くあります。",
  "쉰 목소리는 바람 새는 소리, 거친 소리, 힘겨운 소리가 나거나 평소보다 작고 낮아지며, 목이 따끔거릴 수 있습니다. 목쉼은 흔히 성대에 문제가 있다는 신호입니다.",
  "嗓音沙哑时，声音听起来会发虚、粗糙或吃力，或者比平时更弱、更低，喉咙也可能感觉发痒。声音嘶哑往往是声带出问题的信号。",
  "الصوت المبحوح يبدو مشوبًا بالنَّفَس أو خشنًا أو مُجهَدًا، أو أضعف أو أخفض من المعتاد، وقد تشعر بخدش في حلقك. وكثيرًا ما تكون بحّة الصوت علامة على مشكلة في الطيّتين الصوتيتين.")
T("Other signs that your voice may not be healthy: you have lost the ability to hit some high notes, your voice suddenly sounds deeper, your throat often feels raw, achy or strained, talking has become an effort, or you keep clearing your throat.",
  "Weitere Anzeichen, dass deine Stimme vielleicht nicht gesund ist: Du kommst an manche hohen Töne nicht mehr heran, deine Stimme klingt plötzlich tiefer, dein Hals fühlt sich oft wund, schmerzend oder angestrengt an, Sprechen ist mühsam geworden, oder du räusperst dich ständig.",
  "Otras señales de que tu voz quizá no esté sana: ya no alcanzas algunas notas agudas, tu voz suena de repente más grave, a menudo notas la garganta irritada, dolorida o tensa, hablar te cuesta esfuerzo o carraspeas continuamente.",
  "Autres signes que votre voix n’est peut-être pas en bonne santé : vous n’arrivez plus à atteindre certaines notes aiguës, votre voix paraît soudain plus grave, votre gorge est souvent irritée, douloureuse ou tendue, parler vous demande un effort, ou vous vous raclez sans cesse la gorge.",
  "Altri segnali che la voce potrebbe non essere in salute: non riesci più a raggiungere alcune note acute, la voce sembra all’improvviso più grave, la gola è spesso irritata, dolorante o tesa, parlare è diventato faticoso, oppure continui a schiarirti la gola.",
  "Outros sinais de que sua voz pode não estar saudável: você não consegue mais alcançar algumas notas agudas, sua voz de repente soa mais grave, a garganta muitas vezes fica irritada, dolorida ou tensa, falar passou a exigir esforço, ou você vive pigarreando.",
  "Andere tekenen dat je stem misschien niet gezond is: je haalt sommige hoge noten niet meer, je stem klinkt ineens lager, je keel voelt vaak rauw, pijnlijk of gespannen aan, praten kost moeite, of je blijft je keel schrapen.",
  "Другие признаки того, что с голосом может быть не всё в порядке: вы больше не можете взять некоторые высокие ноты, голос вдруг стал звучать ниже, в горле часто саднит, болит или ощущается напряжение, говорить стало трудно, или вы постоянно откашливаетесь.",
  "Inne oznaki, że twój głos może nie być zdrowy: nie sięgasz już niektórych wysokich dźwięków, głos nagle brzmi niżej, gardło często jest podrażnione, obolałe lub napięte, mówienie stało się wysiłkiem albo ciągle odchrząkujesz.",
  "Sesinizin sağlıklı olmayabileceğine dair başka işaretler: bazı tiz notalara artık çıkamıyorsunuz, sesiniz birden daha kalın çıkıyor, boğazınız sık sık tahriş olmuş, ağrılı ya da zorlanmış hissediyor, konuşmak zahmetli hale geldi ya da sürekli boğazınızı temizliyorsunuz.",
  "Andra tecken på att rösten kanske inte är frisk: du når inte längre vissa höga toner, rösten låter plötsligt mörkare, halsen känns ofta rå, öm eller ansträngd, det har blivit ansträngande att prata, eller du harklar dig hela tiden.",
  "声が健康でないかもしれないサインは、ほかにもあります。一部の高い音が出なくなった、声が急に低くなった、のどがよくヒリヒリしたり痛んだり張ったりする、話すのがつらくなった、咳ばらいばかりしている、などです。",
  "목소리가 건강하지 않을 수 있다는 다른 신호도 있습니다. 일부 높은 음이 더 이상 나지 않는다, 목소리가 갑자기 낮아졌다, 목이 자주 따갑거나 아프거나 긴장된다, 말하는 것이 힘들어졌다, 계속 헛기침을 한다 같은 경우입니다.",
  "嗓音可能不健康的其他信号还有：一些高音唱不上去了，声音突然变低，喉咙经常感到刺痛、酸痛或紧绷，说话变得费力，或者总是在清嗓子。",
  "ومن العلامات الأخرى على أن صوتك قد لا يكون سليمًا: أنك فقدت القدرة على بلوغ بعض النغمات العالية، أو أن صوتك صار فجأة أعمق، أو أن حلقك يؤلمك أو يبدو ملتهبًا أو مُجهَدًا كثيرًا، أو أن الكلام أصبح مُتعِبًا، أو أنك تتنحنح باستمرار.")
T("See a doctor if your voice has been hoarse for more than three weeks, especially if you haven't had a cold or the flu. See one as well if you cough up blood, have difficulty swallowing or breathing, feel a lump in your neck, have pain when speaking or swallowing, or lose your voice completely for more than a few days.",
  "Geh zum Arzt, wenn deine Stimme länger als drei Wochen heiser ist, besonders wenn du keine Erkältung oder Grippe hattest. Geh ebenfalls hin, wenn du Blut hustest, Schwierigkeiten beim Schlucken oder Atmen hast, einen Knoten am Hals spürst, beim Sprechen oder Schlucken Schmerzen hast oder deine Stimme für mehr als ein paar Tage ganz verlierst.",
  "Acude al médico si tu voz lleva ronca más de tres semanas, sobre todo si no has tenido un resfriado o gripe. Acude también si toses sangre, tienes dificultad para tragar o respirar, notas un bulto en el cuello, sientes dolor al hablar o tragar, o pierdes la voz por completo durante más de unos días.",
  "Consultez un médecin si votre voix est enrouée depuis plus de trois semaines, surtout si vous n’avez pas eu de rhume ni de grippe. Consultez aussi si vous crachez du sang, avez du mal à avaler ou à respirer, sentez une grosseur dans le cou, avez mal en parlant ou en avalant, ou perdez complètement la voix pendant plus de quelques jours.",
  "Rivolgiti a un medico se la voce è rauca da più di tre settimane, soprattutto se non hai avuto raffreddore o influenza. Rivolgiti a un medico anche se tossisci sangue, hai difficoltà a deglutire o a respirare, senti un nodulo al collo, provi dolore quando parli o deglutisci, oppure perdi completamente la voce per più di qualche giorno.",
  "Procure um médico se sua voz estiver rouca há mais de três semanas, principalmente se você não teve resfriado nem gripe. Procure também se tossir sangue, tiver dificuldade para engolir ou respirar, sentir um caroço no pescoço, sentir dor ao falar ou engolir, ou perder a voz completamente por mais de alguns dias.",
  "Ga naar een arts als je stem langer dan drie weken hees is, vooral als je geen verkoudheid of griep hebt gehad. Ga ook als je bloed ophoest, moeite hebt met slikken of ademen, een bult in je hals voelt, pijn hebt bij praten of slikken, of je stem langer dan een paar dagen helemaal kwijt bent.",
  "Обратитесь к врачу, если голос остаётся хриплым больше трёх недель, особенно если у вас не было простуды или гриппа. Обратитесь к нему и в том случае, если вы откашливаете кровь, вам трудно глотать или дышать, вы нащупали уплотнение на шее, вам больно говорить или глотать или голос полностью пропал больше чем на несколько дней.",
  "Idź do lekarza, jeśli chrypka trwa dłużej niż trzy tygodnie, zwłaszcza gdy nie miałeś przeziębienia ani grypy. Idź też, jeśli odkrztuszasz krew, masz trudności z przełykaniem lub oddychaniem, wyczuwasz guzek na szyi, odczuwasz ból przy mówieniu lub przełykaniu albo całkowicie tracisz głos na dłużej niż kilka dni.",
  "Sesiniz üç haftadan uzun süredir kısıksa, özellikle de soğuk algınlığı ya da grip geçirmediyseniz doktora gidin. Kan tükürüyorsanız, yutkunmakta ya da nefes almakta zorlanıyorsanız, boynunuzda bir şişlik hissediyorsanız, konuşurken ya da yutkunurken ağrınız varsa veya sesiniz birkaç günden uzun süre tamamen kaybolduysa da doktora gidin.",
  "Sök läkare om rösten har varit hes i mer än tre veckor, särskilt om du inte har haft förkylning eller influensa. Sök också läkare om du hostar upp blod, har svårt att svälja eller andas, känner en knöl på halsen, har ont när du pratar eller sväljer, eller helt förlorar rösten i mer än några dagar.",
  "声がれが3週間以上続く場合、特にかぜやインフルエンザにかかっていないのに続く場合は、医師に相談しましょう。せきをして血が出る、飲み込みにくい、息がしにくい、首にしこりがある、話したり飲み込んだりすると痛む、数日以上まったく声が出ない、といった場合も受診しましょう。",
  "목이 쉰 상태가 3주 넘게 계속되면, 특히 감기나 독감에 걸린 적이 없는데도 그렇다면 병원에 가세요. 기침할 때 피가 나오거나, 삼키기나 숨쉬기가 어렵거나, 목에 멍울이 만져지거나, 말하거나 삼킬 때 아프거나, 며칠 넘게 목소리가 완전히 나오지 않는 경우에도 병원에 가세요.",
  "如果声音嘶哑超过三周，尤其是你并没有感冒或得流感，请去看医生。如果咳出血、吞咽或呼吸困难、摸到脖子上有肿块、说话或吞咽时疼痛，或者完全失声超过几天，也要去看医生。",
  "راجع الطبيب إذا استمرت بحّة صوتك أكثر من ثلاثة أسابيع، خاصة إذا لم تكن مصابًا بالزكام أو الإنفلونزا. وراجعه أيضًا إذا سعلت دمًا، أو واجهت صعوبة في البلع أو التنفس، أو شعرت بكتلة في رقبتك، أو أحسست بألم عند الكلام أو البلع، أو فقدت صوتك تمامًا لأكثر من بضعة أيام.")
T("If you suddenly lose your voice while using it strenuously, for example while yelling, a blood vessel on a vocal fold may have burst. This needs complete voice rest and a trip to the doctor right away. Doctors who specialize in the ears, nose and throat diagnose voice problems, and a speech-language pathologist can help you improve how you use your voice.",
  "Wenn deine Stimme bei starker Beanspruchung plötzlich wegbleibt, zum Beispiel beim Schreien, ist möglicherweise ein Blutgefäß an einer Stimmlippe geplatzt. Dann brauchst du vollständige Stimmruhe und solltest sofort zum Arzt gehen. Stimmprobleme werden von Hals-Nasen-Ohren-Ärzten abgeklärt, und ein Logopäde kann dir helfen, deine Stimme besser einzusetzen.",
  "Si pierdes la voz de repente mientras la usas con mucha fuerza, por ejemplo al gritar, puede que se haya roto un vaso sanguíneo de una cuerda vocal. Eso requiere reposo vocal absoluto y acudir al médico de inmediato. Los problemas de voz los diagnostican los otorrinolaringólogos, y un logopeda puede ayudarte a mejorar cómo usas la voz.",
  "Si vous perdez soudain la voix en la sollicitant fortement, par exemple en criant, un vaisseau sanguin d’une corde vocale s’est peut-être rompu. Il faut alors un repos vocal complet et consulter un médecin sans attendre. Les problèmes de voix sont diagnostiqués par les médecins ORL, et un orthophoniste peut vous aider à mieux utiliser votre voix.",
  "Se perdi all’improvviso la voce mentre la usi con molta forza, per esempio urlando, potrebbe essersi rotto un vaso sanguigno su una corda vocale. In questo caso servono riposo vocale assoluto e una visita medica immediata. I problemi di voce vengono diagnosticati dagli otorinolaringoiatri, e un logopedista può aiutarti a usare meglio la voce.",
  "Se você perder a voz de repente enquanto a usa com muita força, por exemplo ao gritar, pode ser que um vaso sanguíneo de uma prega vocal tenha se rompido. Isso exige repouso vocal total e ida ao médico imediatamente. Problemas de voz são diagnosticados por otorrinolaringologistas, e um fonoaudiólogo pode ajudar você a usar melhor a voz.",
  "Als je je stem plotseling kwijtraakt terwijl je hem zwaar belast, bijvoorbeeld tijdens het schreeuwen, kan er een bloedvaatje op een stemband zijn geknapt. Dan heb je volledige stemrust nodig en moet je meteen naar een arts. Stemproblemen worden vastgesteld door keel-, neus- en oorartsen, en een logopedist kan je helpen je stem beter te gebruiken.",
  "Если голос внезапно пропал при сильной нагрузке, например когда вы кричали, возможно, лопнул кровеносный сосуд на голосовой складке. В этом случае нужен полный голосовой покой и немедленный визит к врачу. Проблемы с голосом диагностируют оториноларингологи (ЛОР-врачи), а логопед может помочь вам правильнее пользоваться голосом.",
  "Jeśli nagle stracisz głos podczas dużego wysiłku głosowego, na przykład krzycząc, mogło dojść do pęknięcia naczynia krwionośnego na fałdzie głosowym. Wymaga to całkowitego oszczędzania głosu i natychmiastowej wizyty u lekarza. Problemy z głosem diagnozują laryngolodzy, a logopeda może pomóc ci lepiej używać głosu.",
  "Sesinizi zorlayarak kullanırken, örneğin bağırırken, sesiniz aniden kaybolursa bir ses telindeki kan damarı patlamış olabilir. Bu durumda sesinizi tamamen dinlendirmeniz ve hemen doktora gitmeniz gerekir. Ses sorunlarını kulak burun boğaz uzmanları teşhis eder; bir dil ve konuşma terapisti de sesinizi daha iyi kullanmanıza yardımcı olabilir.",
  "Om du plötsligt förlorar rösten när du använder den kraftigt, till exempel när du skriker, kan ett blodkärl på ett stämband ha brustit. Då behöver du fullständig röstvila och bör genast söka läkare. Röstproblem utreds av öron-, näs- och halsläkare, och en logoped kan hjälpa dig att använda rösten bättre.",
  "叫んでいるときなど、声を強く使っている最中に急に声が出なくなった場合は、声帯の血管が破れた可能性があります。その場合は完全に声を休め、すぐに医師の診察を受ける必要があります。声のトラブルは耳鼻咽喉科の医師が診断し、言語聴覚士が声の使い方の改善を手伝ってくれます。",
  "소리를 지를 때처럼 목소리를 세게 쓰다가 갑자기 목소리가 나오지 않는다면 성대의 혈관이 터졌을 수 있습니다. 이때는 목소리를 완전히 쉬고 즉시 병원에 가야 합니다. 목소리 문제는 이비인후과 의사가 진단하며, 언어치료사가 목소리를 더 잘 쓰도록 도와줄 수 있습니다.",
  "如果你在用力发声时，比如大喊时，突然失声，可能是声带上的血管破裂了。这需要完全禁声休息，并立即就医。嗓音问题由耳鼻喉科医生诊断，言语治疗师则可以帮助你改进用嗓方式。",
  "إذا فقدت صوتك فجأة أثناء استخدامه بجهد كبير، كأن تكون تصرخ، فربما انفجر وعاء دموي على إحدى الطيّتين الصوتيتين. ويستلزم ذلك إراحة الصوت تمامًا وزيارة الطبيب فورًا. ويشخّص أطباء الأنف والأذن والحنجرة مشكلات الصوت، ويمكن لأخصائي علاج النطق واللغة أن يساعدك على تحسين طريقة استخدامك لصوتك.")
