# Batch 12c: the paragraphs of the book lessons about warming up (topic
# "Warming Up" in BookLessons.json).
#
# The warm-up syllables “me, may, ma, mo, moo” are spelled the way each language
# writes the same five vowels, since the English spelling would be sung wrong.
from trbase import T

# --- Why Warm Up ---
T("A vocal warm-up is a series of exercises that prepares your voice for singing. Warming up helps your voice perform at its best and can make singing feel like less effort.",
  "Ein stimmliches Aufwärmen ist eine Reihe von Übungen, die deine Stimme aufs Singen vorbereitet. Aufwärmen hilft deiner Stimme, ihr Bestes zu geben, und kann das Singen weniger anstrengend wirken lassen.",
  "Un calentamiento vocal es una serie de ejercicios que prepara tu voz para cantar. Calentar ayuda a que tu voz rinda al máximo y puede hacer que cantar cueste menos esfuerzo.",
  "Un échauffement vocal est une série d’exercices qui prépare votre voix au chant. S’échauffer aide votre voix à donner le meilleur d’elle-même et peut rendre le chant moins fatigant.",
  "Un riscaldamento vocale è una serie di esercizi che prepara la voce a cantare. Riscaldarsi aiuta la voce a dare il meglio e può far sembrare il canto meno faticoso.",
  "Um aquecimento vocal é uma série de exercícios que prepara a voz para cantar. Aquecer ajuda sua voz a render o melhor possível e pode fazer cantar parecer exigir menos esforço.",
  "Een stemopwarming is een reeks oefeningen die je stem voorbereidt op het zingen. Opwarmen helpt je stem op haar best te presteren en kan zingen minder moeite laten kosten.",
  "Распевкой называют серию упражнений, которая готовит голос к пению. Она помогает голосу работать в полную силу и может сделать пение менее трудным.",
  "Rozgrzewka głosowa to seria ćwiczeń, które przygotowują głos do śpiewu. Rozgrzewka pomaga głosowi działać najlepiej, jak potrafi, i może sprawić, że śpiew będzie wymagał mniej wysiłku.",
  "Ses ısınması, sesinizi şarkı söylemeye hazırlayan bir dizi egzersizdir. Isınmak sesinizin en iyi performansını göstermesine yardımcı olur ve şarkı söylemeyi daha az yorucu hissettirebilir.",
  "En röstuppvärmning är en serie övningar som förbereder rösten för sång. Att värma upp hjälper rösten att prestera som bäst och kan göra att sången känns mindre ansträngande.",
  "ボーカル・ウォームアップとは、歌う前に声の準備をするための一連のエクササイズです。ウォームアップをすると声が本来の力を発揮しやすくなり、歌うのが楽に感じられることもあります。",
  "발성 워밍업은 노래할 수 있도록 목소리를 준비시키는 일련의 연습입니다. 워밍업을 하면 목소리가 제 실력을 발휘하는 데 도움이 되고, 노래가 덜 힘들게 느껴질 수 있습니다.",
  "开嗓热身是一系列为唱歌做准备的练习。热身能帮助嗓音发挥出最佳状态，也能让唱歌感觉更省力。",
  "إحماء الصوت سلسلة من التمارين تهيّئ صوتك للغناء. ويساعد الإحماء صوتك على الأداء بأفضل ما لديه، وقد يجعل الغناء يبدو أقل جهدًا.")
T("A good warm-up does five things: it warms up your whole body, prepares your breath, gets your lips, tongue and resonating spaces ready, moves your voice from speaking into singing, and prepares you for the music you are about to sing.",
  "Ein gutes Aufwärmen erfüllt fünf Aufgaben: Es wärmt den ganzen Körper auf, bereitet den Atem vor, macht Lippen, Zunge und Resonanzräume bereit, führt die Stimme vom Sprechen ins Singen und bereitet dich auf die Musik vor, die du gleich singen wirst.",
  "Un buen calentamiento hace cinco cosas: calienta todo el cuerpo, prepara la respiración, pone a punto los labios, la lengua y los espacios de resonancia, lleva la voz del habla al canto y te prepara para la música que vas a cantar.",
  "Un bon échauffement remplit cinq rôles : il échauffe tout le corps, prépare le souffle, met en route les lèvres, la langue et les espaces de résonance, fait passer la voix de la parole au chant et vous prépare à la musique que vous allez chanter.",
  "Un buon riscaldamento fa cinque cose: scalda tutto il corpo, prepara il respiro, rende pronti labbra, lingua e spazi di risonanza, porta la voce dal parlato al canto e ti prepara alla musica che stai per cantare.",
  "Um bom aquecimento faz cinco coisas: aquece o corpo todo, prepara a respiração, deixa lábios, língua e espaços de ressonância prontos, leva a voz da fala para o canto e prepara você para a música que vai cantar.",
  "Een goede warming-up doet vijf dingen: hij warmt je hele lichaam op, bereidt je adem voor, maakt je lippen, tong en resonantieruimtes klaar, brengt je stem van spreken naar zingen en bereidt je voor op de muziek die je zo gaat zingen.",
  "Хорошая распевка решает пять задач: разогревает всё тело, готовит дыхание, настраивает губы, язык и резонирующие полости, переводит голос от речи к пению и готовит к музыке, которую вы собираетесь исполнять.",
  "Dobra rozgrzewka robi pięć rzeczy: rozgrzewa całe ciało, przygotowuje oddech, pobudza wargi, język i przestrzenie rezonansowe, przeprowadza głos od mówienia do śpiewu i przygotowuje cię do muzyki, którą zaraz zaśpiewasz.",
  "İyi bir ısınma beş şey yapar: tüm vücudu ısıtır, nefesi hazırlar, dudakları, dili ve rezonans boşluklarını hazır hale getirir, sesi konuşmadan şarkı söylemeye taşır ve sizi söylemek üzere olduğunuz müziğe hazırlar.",
  "En bra uppvärmning gör fem saker: den värmer upp hela kroppen, förbereder andningen, gör läppar, tunga och resonansrum redo, för rösten från tal till sång och förbereder dig för musiken du ska sjunga.",
  "よいウォームアップには5つの役割があります。全身を温めること、呼吸の準備をすること、唇や舌、共鳴する空間を整えること、声を話す状態から歌う状態へ移すこと、そしてこれから歌う曲に備えることです。",
  "좋은 워밍업은 다섯 가지 일을 합니다. 온몸을 데우고, 호흡을 준비하고, 입술과 혀와 공명 공간을 준비시키고, 목소리를 말하기에서 노래하기로 옮기고, 곧 부를 음악에 대비하게 합니다.",
  "好的热身有五个作用：让全身暖起来，为呼吸做准备，让嘴唇、舌头和共鸣空间进入状态，把声音从说话状态带到歌唱状态，并为你即将演唱的音乐做准备。",
  "الإحماء الجيد يحقق خمسة أمور: يُدفئ جسمك كله، ويهيّئ نَفَسك، ويُجهّز شفتيك ولسانك وتجاويف الرنين، وينقل صوتك من الكلام إلى الغناء، ويُعدّك للموسيقى التي توشك أن تغنيها.")
T("Moving from speaking into singing is usually the biggest part. Speaking uses a small range of pitch and loudness, while singing uses a much larger range of both, so a warm-up gradually takes your voice through more of its range. The singing exercises used for this are also called vocalises.",
  "Der Übergang vom Sprechen zum Singen ist meist der größte Teil. Beim Sprechen nutzt du nur einen kleinen Bereich an Tonhöhe und Lautstärke, beim Singen einen viel größeren, deshalb führt ein Aufwärmen deine Stimme nach und nach durch mehr von ihrem Umfang. Die Gesangsübungen dafür heißen auch Vokalisen.",
  "Pasar del habla al canto suele ser la parte más importante. Al hablar usas un rango pequeño de altura y volumen, mientras que al cantar usas uno mucho mayor de ambos, así que el calentamiento lleva tu voz poco a poco por una parte mayor de su extensión. Los ejercicios cantados que se usan para esto también se llaman vocalizaciones.",
  "Passer de la parole au chant est généralement la partie la plus importante. La parole utilise une petite plage de hauteur et de volume, le chant une plage bien plus large des deux : un échauffement fait donc parcourir progressivement à votre voix une plus grande partie de son étendue. Les exercices chantés utilisés pour cela s’appellent aussi des vocalises.",
  "Passare dal parlato al canto è di solito la parte più ampia. Parlando usi una piccola gamma di altezza e volume, mentre cantando ne usi una molto più ampia per entrambi, quindi il riscaldamento porta gradualmente la voce attraverso una parte più grande della sua estensione. Gli esercizi cantati usati a questo scopo si chiamano anche vocalizzi.",
  "Passar da fala para o canto costuma ser a maior parte. A fala usa uma faixa pequena de altura e volume, enquanto o canto usa uma faixa bem maior dos dois, então o aquecimento leva a voz aos poucos por uma parte maior da sua extensão. Os exercícios cantados usados para isso também se chamam vocalizes.",
  "De overgang van spreken naar zingen is meestal het grootste deel. Spreken gebruikt een klein bereik aan toonhoogte en volume, zingen een veel groter bereik van allebei, dus een warming-up neemt je stem geleidelijk door meer van haar bereik. De zangoefeningen die hiervoor worden gebruikt, heten ook vocalises.",
  "Переход от речи к пению обычно занимает больше всего времени. В речи используется небольшой диапазон высоты и громкости, а в пении гораздо больший, поэтому распевка постепенно проводит голос через всё большую часть его диапазона. Певческие упражнения для этого называют также вокализами.",
  "Przejście od mówienia do śpiewu to zwykle największa część. Mowa wykorzystuje niewielki zakres wysokości i głośności, a śpiew znacznie większy zakres obu, dlatego rozgrzewka stopniowo prowadzi głos przez coraz większą część jego skali. Śpiewane ćwiczenia służące temu nazywa się też wokalizami.",
  "Konuşmadan şarkı söylemeye geçiş genellikle en büyük bölümdür. Konuşurken küçük bir perde ve ses yüksekliği aralığı kullanılır, şarkı söylerken ise ikisinin de çok daha geniş bir aralığı; bu yüzden ısınma sesinizi yavaş yavaş ses aralığının daha büyük bir kısmında gezdirir. Bunun için kullanılan şarkılı egzersizlere vokaliz de denir.",
  "Övergången från tal till sång är oftast den största delen. Tal använder ett litet omfång av tonhöjd och ljudstyrka, medan sång använder ett mycket större omfång av båda, så en uppvärmning tar gradvis rösten genom mer av dess omfång. Sångövningarna som används för detta kallas också vokaliser.",
  "話す状態から歌う状態へ移ることが、ふつういちばん大きな部分です。話すときは音の高さも音量も狭い範囲しか使いませんが、歌うときはどちらもずっと広い範囲を使います。そのためウォームアップでは、声域のより広い範囲へ少しずつ声を広げていきます。そのための歌う練習はヴォカリーズとも呼ばれます。",
  "말하기에서 노래하기로 넘어가는 것이 보통 가장 큰 부분입니다. 말할 때는 음높이와 음량의 폭이 좁지만, 노래할 때는 둘 다 훨씬 넓게 쓰기 때문에 워밍업은 목소리를 음역의 더 넓은 부분으로 차츰 이끌어 줍니다. 이를 위한 노래 연습을 보칼리즈라고도 합니다.",
  "从说话过渡到唱歌通常是最主要的部分。说话只用到很小的音高和音量范围，而唱歌用到的两者范围都大得多，所以热身会逐步带着声音走过更大的音域。为此所做的歌唱练习也叫练声曲。",
  "الانتقال من الكلام إلى الغناء هو في العادة الجزء الأكبر. فالكلام يستخدم نطاقًا صغيرًا من درجات الصوت وشدّته، أما الغناء فيستخدم نطاقًا أوسع بكثير منهما، لذا يأخذ الإحماء صوتك تدريجيًا عبر جزء أكبر من مداه. وتُسمّى تمارين الغناء المستخدمة لذلك أيضًا «الفوكاليز».")
T("Finally, get ready for what you will actually sing, for example by doing a few exercises in the key of your song or by working on a difficult passage on its own.",
  "Bereite dich zum Schluss auf das vor, was du tatsächlich singen wirst, zum Beispiel mit ein paar Übungen in der Tonart deines Lieds oder indem du eine schwierige Stelle einzeln übst.",
  "Por último, prepárate para lo que vas a cantar de verdad, por ejemplo haciendo algunos ejercicios en la tonalidad de tu canción o trabajando por separado un pasaje difícil.",
  "Enfin, préparez-vous à ce que vous allez vraiment chanter, par exemple en faisant quelques exercices dans la tonalité de votre chanson ou en travaillant un passage difficile à part.",
  "Infine, preparati a ciò che canterai davvero, per esempio facendo qualche esercizio nella tonalità della tua canzone o lavorando su un passaggio difficile da solo.",
  "Por fim, prepare-se para o que você vai cantar de verdade, por exemplo fazendo alguns exercícios no tom da sua música ou trabalhando um trecho difícil separadamente.",
  "Bereid je ten slotte voor op wat je echt gaat zingen, bijvoorbeeld met een paar oefeningen in de toonsoort van je lied of door een moeilijke passage apart te oefenen.",
  "И наконец, подготовьтесь к тому, что будете петь, например сделайте несколько упражнений в тональности песни или отработайте трудный фрагмент отдельно.",
  "Na koniec przygotuj się do tego, co faktycznie zaśpiewasz, na przykład robiąc kilka ćwiczeń w tonacji swojej piosenki albo ćwicząc osobno trudny fragment.",
  "Son olarak, gerçekten söyleyeceğiniz şeye hazırlanın; örneğin şarkınızın tonunda birkaç egzersiz yapın ya da zor bir bölümü tek başına çalışın.",
  "Förbered dig till sist på det du faktiskt ska sjunga, till exempel genom att göra några övningar i sångens tonart eller öva på ett svårt parti för sig.",
  "最後に、実際に歌う曲への準備をします。たとえば曲のキーでいくつかエクササイズをしたり、難しい部分だけを取り出して練習したりします。",
  "마지막으로 실제로 부를 곡을 준비하세요. 예를 들어 곡의 키로 연습을 몇 가지 하거나, 어려운 구간만 따로 연습해 볼 수 있습니다.",
  "最后，为你真正要唱的内容做准备，比如用歌曲的调做几个练习，或者把难唱的段落单独拿出来练。",
  "وأخيرًا، استعد لما ستغنيه فعلًا، مثلًا بأداء بعض التمارين في مقام أغنيتك أو بالتدرّب على مقطع صعب منفردًا.")

# --- A Simple Warm-Up ---
T("Start with your body. Gently stretch your belly, back, neck and shoulders to release tension before you make a sound.",
  "Beginne mit dem Körper. Dehne sanft Bauch, Rücken, Nacken und Schultern, um Spannungen zu lösen, bevor du einen Ton von dir gibst.",
  "Empieza por el cuerpo. Estira suavemente el abdomen, la espalda, el cuello y los hombros para soltar la tensión antes de emitir ningún sonido.",
  "Commencez par le corps. Étirez doucement le ventre, le dos, la nuque et les épaules pour relâcher les tensions avant d’émettre un son.",
  "Comincia dal corpo. Allunga delicatamente pancia, schiena, collo e spalle per sciogliere le tensioni prima di emettere un suono.",
  "Comece pelo corpo. Alongue suavemente a barriga, as costas, o pescoço e os ombros para soltar a tensão antes de emitir qualquer som.",
  "Begin met je lichaam. Rek rustig je buik, rug, nek en schouders om spanning los te laten voordat je een geluid maakt.",
  "Начните с тела. Мягко растяните живот, спину, шею и плечи, чтобы снять напряжение, прежде чем издать первый звук.",
  "Zacznij od ciała. Delikatnie rozciągnij brzuch, plecy, kark i ramiona, aby uwolnić napięcie, zanim wydasz pierwszy dźwięk.",
  "Vücudunuzla başlayın. Ses çıkarmadan önce gerginliği atmak için karnınızı, sırtınızı, boynunuzu ve omuzlarınızı hafifçe esnetin.",
  "Börja med kroppen. Stretcha försiktigt magen, ryggen, nacken och axlarna för att släppa spänningar innan du gör ett ljud.",
  "まずは体から始めます。声を出す前に、おなか、背中、首、肩をやさしく伸ばして力みをほぐしましょう。",
  "먼저 몸부터 시작하세요. 소리를 내기 전에 배, 등, 목, 어깨를 부드럽게 늘여 긴장을 풀어 주세요.",
  "先从身体开始。在发声之前，轻柔地拉伸腹部、背部、颈部和肩部，释放紧张。",
  "ابدأ بجسمك. مدِّد برفق بطنك وظهرك ورقبتك وكتفيك لتتخلص من التوتر قبل أن تُصدر أي صوت.")
T("Next, prepare your breath. Breathe in for 4 counts and out for 8 counts. Over time, shorten the breath in and lengthen the breath out, until you can breathe in for 1 count and breathe out for as long as is comfortable.",
  "Bereite dann deinen Atem vor. Atme 4 Zählzeiten lang ein und 8 Zählzeiten lang aus. Verkürze mit der Zeit das Einatmen und verlängere das Ausatmen, bis du in 1 Zählzeit einatmen und so lange ausatmen kannst, wie es angenehm ist.",
  "Después, prepara la respiración. Inhala durante 4 tiempos y exhala durante 8. Con el tiempo, acorta la inhalación y alarga la exhalación hasta que puedas inhalar en 1 tiempo y exhalar durante todo el tiempo que te resulte cómodo.",
  "Préparez ensuite votre souffle. Inspirez sur 4 temps et expirez sur 8 temps. Au fil du temps, raccourcissez l’inspiration et allongez l’expiration, jusqu’à inspirer sur 1 temps et expirer aussi longtemps que c’est confortable.",
  "Poi prepara il respiro. Inspira contando fino a 4 ed espira contando fino a 8. Col tempo accorcia l’inspirazione e allunga l’espirazione, finché riesci a inspirare in 1 tempo ed espirare finché ti è comodo.",
  "Em seguida, prepare a respiração. Inspire contando 4 tempos e expire contando 8. Com o tempo, encurte a inspiração e alongue a expiração, até conseguir inspirar em 1 tempo e expirar pelo tempo que for confortável.",
  "Bereid daarna je adem voor. Adem in op 4 tellen en uit op 8 tellen. Maak na verloop van tijd de inademing korter en de uitademing langer, tot je op 1 tel kunt inademen en zo lang kunt uitademen als prettig is.",
  "Затем подготовьте дыхание. Вдыхайте на 4 счёта и выдыхайте на 8. Со временем сокращайте вдох и удлиняйте выдох, пока не сможете вдыхать на 1 счёт и выдыхать так долго, как вам комфортно.",
  "Następnie przygotuj oddech. Wdychaj powietrze, licząc do 4, i wydychaj, licząc do 8. Z czasem skracaj wdech i wydłużaj wydech, aż będziesz w stanie wziąć wdech na 1 i wydychać tak długo, jak jest ci wygodnie.",
  "Ardından nefesinizi hazırlayın. 4 sayıda nefes alın, 8 sayıda verin. Zamanla nefes almayı kısaltıp nefes vermeyi uzatın; ta ki 1 sayıda nefes alıp rahat olduğu sürece nefes verebilene kadar.",
  "Förbered sedan andningen. Andas in på 4 slag och ut på 8 slag. Förkorta med tiden inandningen och förläng utandningen, tills du kan andas in på 1 slag och ut så länge det känns bekvämt.",
  "次に呼吸の準備をします。4つ数えながら吸い、8つ数えながら吐きます。慣れてきたら吸う時間を短く、吐く時間を長くしていき、1つで吸って、無理なく続く限り長く吐けるようにします。",
  "다음으로 호흡을 준비하세요. 4를 세며 들이쉬고 8을 세며 내쉽니다. 점차 들이쉬는 시간은 줄이고 내쉬는 시간은 늘려서, 1에 들이쉬고 편안한 만큼 길게 내쉴 수 있을 때까지 연습하세요.",
  "接着，为呼吸做准备。数 4 拍吸气，数 8 拍呼气。逐渐缩短吸气、延长呼气，直到能用 1 拍吸气，并在舒适的范围内尽量长地呼气。",
  "بعد ذلك، هيّئ نَفَسك. خذ شهيقًا لمدة 4 عدّات وازفر لمدة 8 عدّات. ومع الوقت قصّر الشهيق وأطِل الزفير، حتى تتمكن من الشهيق في عدّة 1 والزفير لأطول مدة مريحة لك.")
T("Then wake up your lips and tongue while keeping your jaw relaxed. Tongue twisters work well, and so does the classic “me, may, ma, mo, moo”. After that, play with sounds such as whoops, wails and humming to get a feel for the spaces that shape your voice.",
  "Wecke dann Lippen und Zunge auf, während dein Kiefer locker bleibt. Zungenbrecher eignen sich gut, ebenso das klassische „mi, me, ma, mo, mu“. Probiere danach Laute wie Jauchzer, Heullaute und Summen aus, um ein Gefühl für die Räume zu bekommen, die deine Stimme formen.",
  "Luego despierta los labios y la lengua manteniendo la mandíbula relajada. Los trabalenguas funcionan bien, y también el clásico «mi, me, ma, mo, mu». Después, juega con sonidos como gritos de júbilo, lamentos y tarareos con la boca cerrada para sentir los espacios que dan forma a tu voz.",
  "Réveillez ensuite les lèvres et la langue en gardant la mâchoire détendue. Les virelangues fonctionnent bien, tout comme le classique « mi, mé, ma, mo, mou ». Ensuite, jouez avec des sons comme des cris de joie, des plaintes et des fredonnements bouche fermée pour sentir les espaces qui façonnent votre voix.",
  "Poi risveglia labbra e lingua tenendo la mandibola rilassata. Gli scioglilingua funzionano bene, così come il classico “mi, me, ma, mo, mu”. Dopo, gioca con suoni come gridolini, lamenti e canto a bocca chiusa per sentire gli spazi che danno forma alla tua voce.",
  "Depois, desperte os lábios e a língua mantendo a mandíbula relaxada. Trava-línguas funcionam bem, assim como o clássico “mi, me, ma, mo, mu”. Em seguida, brinque com sons como gritinhos, lamentos e cantarolar de boca fechada para sentir os espaços que moldam sua voz.",
  "Maak daarna je lippen en tong wakker terwijl je kaak ontspannen blijft. Tongbrekers werken goed, net als het klassieke ‘mie, mee, ma, mo, moe’. Speel vervolgens met klanken als juichkreten, jammerklanken en neuriën om de ruimtes te voelen die je stem vormen.",
  "Затем разбудите губы и язык, сохраняя челюсть расслабленной. Хорошо подходят скороговорки, а также классическое «ми, мэ, ма, мо, му». После этого поиграйте со звуками: возгласами, протяжными стонами и мычанием с закрытым ртом, чтобы почувствовать полости, которые формируют голос.",
  "Potem obudź wargi i język, utrzymując rozluźnioną żuchwę. Dobrze sprawdzają się łamańce językowe, a także klasyczne „mi, me, ma, mo, mu”. Następnie pobaw się dźwiękami, takimi jak okrzyki, zawodzenie i mruczenie z zamkniętymi ustami, żeby poczuć przestrzenie, które kształtują twój głos.",
  "Sonra çenenizi gevşek tutarak dudaklarınızı ve dilinizi uyandırın. Tekerlemeler işe yarar, klasik “mi, me, ma, mo, mu” da öyle. Ardından sesinizi şekillendiren boşlukları hissetmek için neşeli çığlıklar, uzun inlemeler ve mırıldanma gibi seslerle oynayın.",
  "Väck sedan läppar och tunga medan käken förblir avslappnad. Tungvrickare fungerar bra, och det gör även klassiska ”mi, me, ma, mo, mu”. Lek därefter med ljud som tjut, jämmer och nynnande för att få en känsla för utrymmena som formar din röst.",
  "続いて、あごをゆるめたまま唇と舌を目覚めさせます。早口言葉がよく効きますし、定番の「ミ、メ、マ、モ、ム」もおすすめです。そのあと、歓声のような声、うなるような声、ハミングなどで遊んで、声を形づくる空間の感覚をつかみます。",
  "그런 다음 턱을 편안히 둔 채 입술과 혀를 깨우세요. 잰말놀이도 좋고, 대표적인 “미, 메, 마, 모, 무”도 좋습니다. 그다음 환호성, 길게 우는 듯한 소리, 허밍 같은 소리로 놀면서 목소리를 만드는 공간을 느껴 보세요.",
  "然后在保持下巴放松的同时，唤醒嘴唇和舌头。绕口令效果很好，经典的“mi、me、ma、mo、mu”也一样。之后，用欢呼声、拖长的呜咽声和哼鸣等声音来玩一玩，感受塑造声音的那些空间。",
  "ثم أيقظ شفتيك ولسانك مع إبقاء فكّك مرتخيًا. تفيد هنا الجمل الصعبة النطق، وكذلك المقاطع الكلاسيكية «mi, me, ma, mo, mu». بعد ذلك، العب بأصوات مثل صيحات الفرح والنواح والهمهمة بفم مغلق لتشعر بالتجاويف التي تشكّل صوتك.")
T("Finally, sing a few easy exercises that move gradually through your range before you start on your actual music. Keep it easy: a warm-up should never hurt, and if a note is too high for you, don't force it.",
  "Singe zum Schluss ein paar leichte Übungen, die sich nach und nach durch deinen Umfang bewegen, bevor du mit deiner eigentlichen Musik beginnst. Bleib entspannt: Ein Aufwärmen darf nie wehtun, und wenn ein Ton zu hoch für dich ist, erzwinge ihn nicht.",
  "Por último, canta algunos ejercicios sencillos que recorran poco a poco tu extensión antes de empezar con tu música. Tómatelo con calma: un calentamiento nunca debe doler, y si una nota es demasiado aguda para ti, no la fuerces.",
  "Enfin, chantez quelques exercices faciles qui parcourent progressivement votre étendue avant d’attaquer votre véritable répertoire. Restez dans la facilité : un échauffement ne doit jamais faire mal, et si une note est trop aiguë pour vous, ne la forcez pas.",
  "Infine, canta qualche esercizio facile che percorra gradualmente la tua estensione prima di passare alla musica vera e propria. Resta leggero: un riscaldamento non deve mai fare male, e se una nota è troppo acuta per te, non forzarla.",
  "Por fim, cante alguns exercícios fáceis que percorram aos poucos a sua extensão antes de começar a música de verdade. Vá com calma: um aquecimento nunca deve doer, e se uma nota for aguda demais para você, não force.",
  "Zing tot slot een paar makkelijke oefeningen die geleidelijk door je bereik gaan voordat je aan je eigenlijke muziek begint. Houd het licht: een warming-up mag nooit pijn doen, en als een noot te hoog voor je is, forceer hem dan niet.",
  "В конце спойте несколько лёгких упражнений, постепенно проходящих по диапазону, и только потом переходите к самой музыке. Не перенапрягайтесь: распевка никогда не должна причинять боль, а если нота для вас слишком высокая, не пытайтесь взять её силой.",
  "Na koniec zaśpiewaj kilka łatwych ćwiczeń, które stopniowo przechodzą przez twoją skalę, zanim zaczniesz właściwą muzykę. Nie przesadzaj: rozgrzewka nigdy nie powinna boleć, a jeśli dźwięk jest dla ciebie za wysoki, nie wymuszaj go.",
  "Son olarak, asıl müziğinize başlamadan önce ses aralığınızda yavaş yavaş ilerleyen birkaç kolay egzersiz söyleyin. Kendinizi zorlamayın: ısınma asla acı vermemeli ve bir nota size fazla tiz geliyorsa onu zorlamayın.",
  "Sjung till sist några lätta övningar som gradvis rör sig genom ditt omfång innan du börjar med den egentliga musiken. Ta det lugnt: en uppvärmning ska aldrig göra ont, och om en ton är för hög för dig ska du inte tvinga fram den.",
  "最後に、声域を少しずつ移動していくやさしいエクササイズをいくつか歌ってから、実際の曲に取りかかります。無理はしないでください。ウォームアップで痛みが出てはいけませんし、高すぎる音は無理に出さないようにしましょう。",
  "마지막으로 실제 곡을 시작하기 전에 음역을 조금씩 오가는 쉬운 연습을 몇 가지 불러 보세요. 무리하지 마세요. 워밍업은 절대 아프면 안 되며, 너무 높은 음은 억지로 내지 마세요.",
  "最后，在开始真正的曲目之前，唱几个在音域中逐步移动的简单练习。保持轻松：热身绝不应该让你感到疼痛，如果某个音对你来说太高，不要硬唱。",
  "وأخيرًا، غنِّ بعض التمارين السهلة التي تتنقل تدريجيًا عبر مداك قبل أن تبدأ بموسيقاك الفعلية. لا تُجهد نفسك: فالإحماء لا ينبغي أن يؤلم أبدًا، وإذا كانت نغمة ما عالية جدًا عليك فلا تُجبر صوتك عليها.")

# --- Vocalises ---
T("A vocalise is a vocal exercise without words, sung on one or more vowel sounds. Vocalises train breath control, diction, blending and balance.",
  "Eine Vokalise ist eine Gesangsübung ohne Worte, gesungen auf einem oder mehreren Vokalen. Vokalisen trainieren Atemkontrolle, Aussprache, Klangverschmelzung und Ausgewogenheit.",
  "Una vocalización es un ejercicio vocal sin palabras que se canta sobre uno o varios sonidos vocálicos. Las vocalizaciones entrenan el control de la respiración, la dicción, el empaste y el equilibrio.",
  "Une vocalise est un exercice vocal sans paroles, chanté sur une ou plusieurs voyelles. Les vocalises travaillent le contrôle du souffle, la diction, la fusion des voix et l’équilibre.",
  "Un vocalizzo è un esercizio vocale senza parole, cantato su uno o più suoni vocalici. I vocalizzi allenano il controllo del respiro, la dizione, l’amalgama e l’equilibrio.",
  "Um vocalize é um exercício vocal sem palavras, cantado em um ou mais sons de vogal. Os vocalizes treinam o controle da respiração, a dicção, a fusão das vozes e o equilíbrio.",
  "Een vocalise is een zangoefening zonder woorden, gezongen op een of meer klinkers. Vocalises trainen ademcontrole, dictie, samenklank en balans.",
  "Вокализом называют вокальное упражнение без слов, которое поётся на одном или нескольких гласных. Вокализы тренируют управление дыханием, дикцию, слитность звучания и баланс.",
  "Wokaliza to ćwiczenie wokalne bez słów, śpiewane na jednej lub kilku samogłoskach. Wokalizy ćwiczą kontrolę oddechu, dykcję, stapianie się głosów i równowagę brzmienia.",
  "Vokaliz, bir ya da birkaç ünlü üzerinde söylenen, sözsüz bir ses egzersizidir. Vokalizler nefes kontrolünü, diksiyonu, seslerin kaynaşmasını ve dengeyi geliştirir.",
  "En vokalis är en sångövning utan ord, sjungen på ett eller flera vokalljud. Vokaliser tränar andningskontroll, diktion, samklang och balans.",
  "ヴォカリーズとは、歌詞のない声のエクササイズで、1つまたは複数の母音で歌います。ヴォカリーズでは、息のコントロール、ディクション、声の溶け合い、バランスが鍛えられます。",
  "보칼리즈는 가사 없이 하나 이상의 모음으로 부르는 발성 연습입니다. 보칼리즈로 호흡 조절, 딕션, 소리의 어우러짐, 균형을 훈련합니다.",
  "练声曲是一种没有歌词的发声练习，用一个或多个元音来唱。练声曲可以训练气息控制、咬字、声音融合与平衡。",
  "الفوكاليز تمرين صوتي بلا كلمات يُغنّى على حرف علة واحد أو أكثر. وتدرّب تمارين الفوكاليز على التحكم في النَّفَس ووضوح النطق وانسجام الأصوات والتوازن.")
T("Vocal exercises serve several purposes: warming up your voice, extending your range, and learning techniques such as legato (smoothly connected notes), staccato (short, separated notes), control of loudness, fast runs and singing wide leaps comfortably.",
  "Stimmübungen dienen mehreren Zwecken: die Stimme aufwärmen, den Umfang erweitern und Techniken lernen wie Legato (fließend verbundene Töne), Staccato (kurze, getrennte Töne), die Kontrolle der Lautstärke, schnelle Läufe und das mühelose Singen großer Sprünge.",
  "Los ejercicios vocales sirven para varias cosas: calentar la voz, ampliar la extensión y aprender técnicas como el legato (notas unidas con suavidad), el staccato (notas cortas y separadas), el control del volumen, las escalas rápidas y cantar saltos amplios con comodidad.",
  "Les exercices vocaux ont plusieurs buts : échauffer la voix, élargir l’étendue et apprendre des techniques comme le legato (notes liées avec souplesse), le staccato (notes courtes et détachées), le contrôle du volume, les traits rapides et les grands intervalles chantés avec aisance.",
  "Gli esercizi vocali servono a diversi scopi: riscaldare la voce, ampliare l’estensione e imparare tecniche come il legato (note unite con morbidezza), lo staccato (note brevi e separate), il controllo del volume, i passaggi veloci e i salti ampi cantati con comodità.",
  "Os exercícios vocais têm vários objetivos: aquecer a voz, ampliar a extensão e aprender técnicas como o legato (notas ligadas com suavidade), o staccato (notas curtas e separadas), o controle do volume, as passagens rápidas e cantar saltos amplos com conforto.",
  "Stemoefeningen hebben meerdere doelen: je stem opwarmen, je bereik uitbreiden en technieken leren zoals legato (soepel verbonden noten), staccato (korte, losse noten), volumebeheersing, snelle loopjes en grote sprongen comfortabel zingen.",
  "У вокальных упражнений несколько целей: разогреть голос, расширить диапазон и освоить такие приёмы, как легато (плавно связанные ноты), стаккато (короткие отрывистые ноты), управление громкостью, быстрые пассажи и удобное исполнение широких скачков.",
  "Ćwiczenia wokalne służą kilku celom: rozgrzaniu głosu, poszerzeniu skali i nauce technik takich jak legato (płynnie połączone dźwięki), staccato (krótkie, oddzielone dźwięki), panowanie nad głośnością, szybkie przebiegi i swobodne śpiewanie dużych skoków.",
  "Ses egzersizlerinin birkaç amacı vardır: sesi ısıtmak, ses aralığını genişletmek ve legato (yumuşakça bağlanan notalar), staccato (kısa, ayrık notalar), ses yüksekliği kontrolü, hızlı pasajlar ve geniş aralıkları rahatça söylemek gibi teknikleri öğrenmek.",
  "Röstövningar fyller flera syften: att värma upp rösten, att utöka omfånget och att lära sig tekniker som legato (mjukt sammanbundna toner), staccato (korta, åtskilda toner), kontroll av ljudstyrkan, snabba löpningar och att sjunga stora språng bekvämt.",
  "声のエクササイズにはいくつもの目的があります。声を温めること、声域を広げること、そしてレガート（なめらかにつなげた音）、スタッカート（短く切った音）、音量のコントロール、速いパッセージ、大きな跳躍を楽に歌うことなどのテクニックを身につけることです。",
  "발성 연습에는 여러 목적이 있습니다. 목소리를 데우고, 음역을 넓히고, 레가토(부드럽게 이어지는 음), 스타카토(짧게 끊어지는 음), 음량 조절, 빠른 패시지, 넓은 도약을 편하게 부르기 같은 기법을 익히는 것입니다.",
  "发声练习有好几个目的：让嗓子热起来、扩展音域，以及学习各种技巧，比如连音（平滑相连的音）、断音（短促分开的音）、音量控制、快速的跑动乐句，以及轻松地唱出大跳。",
  "لتمارين الصوت أغراض عدة: إحماء صوتك، وتوسيع مداك، وتعلّم تقنيات مثل اللِّيغاتو (نغمات متصلة بسلاسة) والستاكاتو (نغمات قصيرة منفصلة) والتحكم في شدة الصوت والجُمل السريعة وغناء القفزات الواسعة بارتياح.")
T("Vocalises have a long history. A collection from 1755 already used songs without words as exercises in vocal technique, and by the 19th century composers were writing vocalises especially for teaching. Some became concert pieces, such as Rachmaninoff's “Vocalise” from 1912.",
  "Vokalisen haben eine lange Geschichte. Schon eine Sammlung aus dem Jahr 1755 nutzte Lieder ohne Worte als Übungen in Gesangstechnik, und im 19. Jahrhundert schrieben Komponisten Vokalisen eigens für den Unterricht. Manche wurden zu Konzertstücken, etwa Rachmaninows „Vocalise“ von 1912.",
  "Las vocalizaciones tienen una larga historia. Ya una colección de 1755 usaba canciones sin palabras como ejercicios de técnica vocal, y en el siglo XIX los compositores escribían vocalizaciones pensadas especialmente para la enseñanza. Algunas se convirtieron en piezas de concierto, como la «Vocalise» de Rajmáninov, de 1912.",
  "Les vocalises ont une longue histoire. Un recueil de 1755 utilisait déjà des chansons sans paroles comme exercices de technique vocale, et au XIXe siècle, des compositeurs écrivaient des vocalises spécialement pour l’enseignement. Certaines sont devenues des pièces de concert, comme la « Vocalise » de Rachmaninov, de 1912.",
  "I vocalizzi hanno una lunga storia. Già una raccolta del 1755 usava canzoni senza parole come esercizi di tecnica vocale, e nell’Ottocento i compositori scrivevano vocalizzi apposta per l’insegnamento. Alcuni sono diventati brani da concerto, come la “Vocalise” di Rachmaninov del 1912.",
  "Os vocalizes têm uma longa história. Uma coletânea de 1755 já usava canções sem palavras como exercícios de técnica vocal, e no século XIX compositores escreviam vocalizes especialmente para o ensino. Alguns viraram peças de concerto, como a “Vocalise” de Rachmaninoff, de 1912.",
  "Vocalises hebben een lange geschiedenis. Al in een verzameling uit 1755 werden liederen zonder woorden gebruikt als oefeningen in zangtechniek, en in de 19e eeuw schreven componisten vocalises speciaal voor het onderwijs. Sommige werden concertstukken, zoals de ‘Vocalise’ van Rachmaninov uit 1912.",
  "У вокализов долгая история. Уже в сборнике 1755 года песни без слов использовались как упражнения по вокальной технике, а в XIX веке композиторы писали вокализы специально для обучения. Некоторые стали концертными пьесами, например «Вокализ» Рахманинова 1912 года.",
  "Wokalizy mają długą historię. Już zbiór z 1755 roku wykorzystywał pieśni bez słów jako ćwiczenia z techniki wokalnej, a w XIX wieku kompozytorzy pisali wokalizy specjalnie do nauki. Niektóre stały się utworami koncertowymi, jak „Wokaliza” Rachmaninowa z 1912 roku.",
  "Vokalizlerin uzun bir geçmişi vardır. 1755 tarihli bir derleme bile sözsüz şarkıları ses tekniği egzersizleri olarak kullanıyordu; 19. yüzyılda ise besteciler özellikle eğitim için vokalizler yazıyordu. Bazıları, Rahmaninov'un 1912 tarihli “Vokaliz”i gibi konser eserlerine dönüştü.",
  "Vokaliser har en lång historia. Redan en samling från 1755 använde sånger utan ord som övningar i sångteknik, och på 1800-talet skrev tonsättare vokaliser särskilt för undervisning. Vissa blev konsertstycken, som Rachmaninovs ”Vocalise” från 1912.",
  "ヴォカリーズには長い歴史があります。1755年の曲集ではすでに歌詞のない歌が発声技術の練習に使われており、19世紀には作曲家たちが教育のために専用のヴォカリーズを書いていました。なかには、1912年のラフマニノフの「ヴォカリーズ」のように演奏会用の作品になったものもあります。",
  "보칼리즈에는 긴 역사가 있습니다. 1755년의 한 곡집은 이미 가사 없는 노래를 발성 기술 연습으로 썼고, 19세기에는 작곡가들이 교육용으로 보칼리즈를 따로 작곡했습니다. 1912년 라흐마니노프의 “보칼리즈”처럼 연주회용 작품이 된 것도 있습니다.",
  "练声曲历史悠久。早在 1755 年的一部曲集中，无词的歌曲就被用作发声技巧练习；到了 19 世纪，作曲家们开始专门为教学创作练声曲。其中一些成了音乐会作品，比如拉赫玛尼诺夫 1912 年的《练声曲》。",
  "لتمارين الفوكاليز تاريخ طويل. فمجموعة تعود إلى عام 1755 استخدمت بالفعل أغاني بلا كلمات تمارينَ في تقنية الغناء، وبحلول القرن التاسع عشر صار المؤلفون يكتبون الفوكاليز خصيصًا للتعليم. وأصبح بعضها قطعًا تُعزف في الحفلات، مثل «فوكاليز» رحمانينوف من عام 1912.")
T("What matters most is how you practice. Voice teachers recommend practicing carefully and systematically, and paying attention the whole time to the sound you are making and to what you feel while you sing.",
  "Am wichtigsten ist, wie du übst. Gesanglehrer empfehlen, sorgfältig und systematisch zu üben und die ganze Zeit darauf zu achten, welchen Klang du erzeugst und was du beim Singen spürst.",
  "Lo más importante es cómo practicas. Los profesores de canto recomiendan practicar con cuidado y de forma sistemática, prestando atención todo el tiempo al sonido que produces y a lo que sientes mientras cantas.",
  "Le plus important, c’est la façon dont vous vous exercez. Les professeurs de chant recommandent de travailler avec soin et méthode, en restant attentif en permanence au son que vous produisez et à ce que vous ressentez en chantant.",
  "Ciò che conta di più è come ti eserciti. Gli insegnanti di canto consigliano di esercitarsi con cura e in modo sistematico, prestando sempre attenzione al suono che produci e a ciò che senti mentre canti.",
  "O que mais importa é como você pratica. Professores de canto recomendam praticar com cuidado e de forma sistemática, prestando atenção o tempo todo ao som que você produz e ao que sente enquanto canta.",
  "Het belangrijkste is hoe je oefent. Zangdocenten raden aan zorgvuldig en systematisch te oefenen en de hele tijd te letten op de klank die je maakt en op wat je voelt terwijl je zingt.",
  "Важнее всего то, как вы занимаетесь. Педагоги по вокалу советуют заниматься внимательно и систематически, всё время следя за тем, какой звук вы издаёте и что ощущаете во время пения.",
  "Najważniejsze jest to, jak ćwiczysz. Nauczyciele śpiewu zalecają ćwiczyć starannie i systematycznie, cały czas zwracając uwagę na dźwięk, który wydajesz, i na to, co czujesz podczas śpiewania.",
  "En önemlisi nasıl çalıştığınızdır. Şan eğitmenleri dikkatli ve sistemli çalışmayı, şarkı söylerken çıkardığınız sese ve hissettiklerinize sürekli dikkat etmeyi önerir.",
  "Det viktigaste är hur du övar. Sånglärare rekommenderar att öva noggrant och systematiskt och hela tiden vara uppmärksam på ljudet du skapar och på vad du känner medan du sjunger.",
  "いちばん大切なのは、どう練習するかです。歌の先生たちは、ていねいに体系立てて練習し、歌っているあいだずっと、自分が出している音と体で感じていることに注意を向けるよう勧めています。",
  "가장 중요한 것은 어떻게 연습하느냐입니다. 노래 선생님들은 신중하고 체계적으로 연습하면서, 노래하는 내내 내가 내는 소리와 몸으로 느끼는 것에 주의를 기울이라고 권합니다.",
  "最重要的是怎样练习。声乐老师建议认真、系统地练习，唱歌时始终留意自己发出的声音和身体的感受。",
  "الأهم هو طريقة تمرينك. ينصح معلمو الغناء بالتمرين بعناية وبشكل منهجي، مع الانتباه طوال الوقت إلى الصوت الذي تُصدره وإلى ما تشعر به أثناء الغناء.")
