# Batch 7: Settings ▸ Reset — the hub, its four screens and their confirmations.
from trbase import T

# --- Settings hub ---
T("Reset", "Zurücksetzen", "Restablecer", "Réinitialiser", "Ripristina", "Redefinir", "Herstellen", "Сброс", "Resetuj", "Sıfırla", "Återställ", "リセット", "초기화", "重置")
T("Delete your scores, exercises and Home tab lists, or put your settings back to how the app started out.",
  "Lösche deine Punktzahlen, Übungen und Listen im Start-Tab oder setze deine Einstellungen auf den Anfangszustand der App zurück.",
  "Elimina tus puntuaciones, ejercicios y listas de la pestaña Inicio, o restablece tus ajustes a como empezó la app.",
  "Supprimez vos notes, vos exercices et les listes de l’onglet Accueil, ou remettez vos réglages dans l’état initial de l’app.",
  "Elimina i tuoi punteggi, gli esercizi e gli elenchi della scheda Home, oppure riporta le impostazioni a com’erano all’inizio.",
  "Exclua suas pontuações, exercícios e listas da aba Início, ou volte suas configurações ao estado inicial do app.",
  "Verwijder je scores, oefeningen en lijsten op het tabblad Start, of zet je instellingen terug zoals de app begon.",
  "Удалите свои оценки, упражнения и списки на вкладке «Главная» или верните настройки к исходному состоянию приложения.",
  "Usuń swoje wyniki, ćwiczenia i listy na karcie Start albo przywróć ustawienia do stanu początkowego aplikacji.",
  "Puanlarınızı, egzersizlerinizi ve Ana Sayfa sekmesindeki listeleri silin ya da ayarlarınızı uygulamanın başlangıç durumuna döndürün.",
  "Radera dina poäng, övningar och listor på fliken Hem, eller återställ dina inställningar till hur appen började.",
  "スコア、エクササイズ、ホームタブのリストを削除するか、設定をアプリの初期状態に戻します。",
  "점수, 연습, 홈 탭 목록을 삭제하거나 설정을 앱의 초기 상태로 되돌립니다.",
  "删除你的得分、练习和“首页”标签的列表，或将设置恢复到应用最初的状态。")

# --- Reset hub ---
T("Scores", "Punktzahlen", "Puntuaciones", "Notes", "Punteggi", "Pontuações", "Scores", "Оценки", "Wyniki", "Puanlar", "Poäng", "スコア", "점수", "得分")
T("Delete the scores recorded for a single exercise, or wipe them all.",
  "Lösche die Punktzahlen einer einzelnen Übung oder alle auf einmal.",
  "Elimina las puntuaciones de un solo ejercicio, o bórralas todas.",
  "Supprimez les notes d’un seul exercice, ou effacez-les toutes.",
  "Elimina i punteggi di un singolo esercizio, oppure cancellali tutti.",
  "Exclua as pontuações de um único exercício, ou apague todas.",
  "Verwijder de scores van één oefening, of wis ze allemaal.",
  "Удалите оценки одного упражнения или сотрите их все.",
  "Usuń wyniki jednego ćwiczenia albo wymaż wszystkie.",
  "Tek bir egzersizin puanlarını silin ya da hepsini birden temizleyin.",
  "Radera poängen för en enskild övning, eller rensa alla.",
  "個々のエクササイズのスコアを削除するか、すべてを消去します。",
  "개별 연습의 점수를 삭제하거나 전체를 지웁니다.",
  "删除单个练习的得分，或清除全部得分。")
T("Put a single settings category — or every one of them — back to how the app started out.",
  "Setze eine einzelne Einstellungskategorie – oder alle – auf den Anfangszustand der App zurück.",
  "Restablece una sola categoría de ajustes —o todas— a como empezó la app.",
  "Remettez une seule catégorie de réglages — ou toutes — dans l’état initial de l’app.",
  "Riporta una singola categoria di impostazioni — o tutte — a com’era all’avvio dell’app.",
  "Volte uma única categoria de configurações — ou todas — ao estado inicial do app.",
  "Zet één instellingencategorie — of allemaal — terug zoals de app begon.",
  "Верните одну категорию настроек — или все сразу — к исходному состоянию приложения.",
  "Przywróć jedną kategorię ustawień — albo wszystkie — do stanu początkowego aplikacji.",
  "Tek bir ayar kategorisini — ya da hepsini — uygulamanın başlangıç durumuna döndürün.",
  "Återställ en enskild inställningskategori – eller alla – till hur appen började.",
  "設定カテゴリを個別に、またはすべてまとめてアプリの初期状態に戻します。",
  "설정 카테고리를 하나씩, 또는 전부 한 번에 앱의 초기 상태로 되돌립니다.",
  "将单个设置类别（或全部类别）恢复到应用最初的状态。")
T("Delete the exercises you made or downloaded, and undo your changes to the ones that came with the app.",
  "Lösche die Übungen, die du erstellt oder heruntergeladen hast, und mache deine Änderungen an den mitgelieferten rückgängig.",
  "Elimina los ejercicios que creaste o descargaste, y deshaz tus cambios en los que vienen con la app.",
  "Supprimez les exercices que vous avez créés ou téléchargés, et annulez vos modifications sur ceux fournis avec l’app.",
  "Elimina gli esercizi che hai creato o scaricato e annulla le tue modifiche a quelli inclusi nell’app.",
  "Exclua os exercícios que você criou ou baixou e desfaça suas alterações nos que vêm com o app.",
  "Verwijder de oefeningen die je zelf maakte of downloadde, en maak je wijzigingen aan de meegeleverde ongedaan.",
  "Удалите упражнения, которые вы создали или скачали, и отмените свои изменения во встроенных.",
  "Usuń ćwiczenia, które utworzyłeś lub pobrałeś, i cofnij zmiany w tych dołączonych do aplikacji.",
  "Kendi oluşturduğunuz veya indirdiğiniz egzersizleri silin ve uygulamayla gelenlerde yaptığınız değişiklikleri geri alın.",
  "Radera övningarna du skapat eller laddat ner, och ångra dina ändringar i dem som följde med appen.",
  "自分で作成またはダウンロードしたエクササイズを削除し、アプリに付属するエクササイズへの変更を元に戻します。",
  "직접 만들거나 내려받은 연습을 삭제하고, 앱에 포함된 연습에 가한 변경을 되돌립니다.",
  "删除你创建或下载的练习，并撤销你对应用自带练习所做的更改。")
T("Clear the Home tab's favourites, routines and recently played list.",
  "Leere die Favoriten, Routinen und die Liste der zuletzt gespielten Übungen im Start-Tab.",
  "Vacía los favoritos, las rutinas y la lista de recientes de la pestaña Inicio.",
  "Videz les favoris, les routines et la liste des exercices récents de l’onglet Accueil.",
  "Svuota i preferiti, le routine e l’elenco dei recenti della scheda Home.",
  "Limpe os favoritos, as rotinas e a lista de recentes da aba Início.",
  "Leeg de favorieten, routines en de lijst met recent gespeelde oefeningen op het tabblad Start.",
  "Очистите избранное, программы и список недавних на вкладке «Главная».",
  "Wyczyść ulubione, rutyny i listę ostatnio odtwarzanych na karcie Start.",
  "Ana Sayfa sekmesindeki favorileri, rutinleri ve son kullanılanlar listesini temizleyin.",
  "Rensa favoriter, rutiner och listan över senast spelade på fliken Hem.",
  "ホームタブのお気に入り、ルーティン、最近再生したリストを消去します。",
  "홈 탭의 즐겨찾기, 루틴, 최근 재생 목록을 지웁니다.",
  "清空“首页”标签的收藏、训练组和最近播放列表。")

# --- Confirmation ---
T("Revert", "Zurücksetzen", "Restaurar", "Rétablir", "Ripristina", "Restaurar", "Herstellen", "Восстановить", "Przywróć", "Geri yükle", "Återställ", "元に戻す", "되돌리기", "还原")
T("This can't be undone.", "Das lässt sich nicht rückgängig machen.", "Esto no se puede deshacer.", "Cette action est irréversible.", "L’operazione non può essere annullata.", "Isso não pode ser desfeito.", "Dit kan niet ongedaan worden gemaakt.", "Это действие нельзя отменить.", "Tej operacji nie można cofnąć.", "Bu işlem geri alınamaz.", "Det går inte att ångra.", "この操作は取り消せません。", "이 작업은 되돌릴 수 없습니다.", "此操作无法撤销。")

# --- Reset ▸ Scores ---
T("Recorded scores", "Aufgezeichnete Punktzahlen", "Puntuaciones registradas", "Notes enregistrées", "Punteggi registrati", "Pontuações registradas", "Vastgelegde scores", "Записанные оценки", "Zapisane wyniki", "Kaydedilen puanlar", "Sparade poäng", "記録されたスコア", "기록된 점수", "已记录的得分")
T("No scores have been recorded yet.", "Es wurden noch keine Punktzahlen aufgezeichnet.", "Todavía no se ha registrado ninguna puntuación.", "Aucune note n’a encore été enregistrée.", "Non è stato ancora registrato alcun punteggio.", "Nenhuma pontuação foi registrada ainda.", "Er zijn nog geen scores vastgelegd.", "Оценки ещё не записывались.", "Nie zapisano jeszcze żadnych wyników.", "Henüz hiç puan kaydedilmedi.", "Inga poäng har sparats än.", "まだスコアは記録されていません。", "아직 기록된 점수가 없습니다.", "尚未记录任何得分。")
T("Deletes the scores recorded for this exercise. The exercise itself is kept.",
  "Löscht die aufgezeichneten Punktzahlen dieser Übung. Die Übung selbst bleibt erhalten.",
  "Elimina las puntuaciones registradas de este ejercicio. El ejercicio se conserva.",
  "Supprime les notes enregistrées pour cet exercice. L’exercice lui-même est conservé.",
  "Elimina i punteggi registrati per questo esercizio. L’esercizio stesso viene mantenuto.",
  "Exclui as pontuações registradas deste exercício. O exercício em si é mantido.",
  "Verwijdert de vastgelegde scores van deze oefening. De oefening zelf blijft behouden.",
  "Удаляет записанные оценки этого упражнения. Само упражнение остаётся.",
  "Usuwa zapisane wyniki tego ćwiczenia. Samo ćwiczenie pozostaje.",
  "Bu egzersiz için kaydedilen puanları siler. Egzersizin kendisi kalır.",
  "Raderar de sparade poängen för den här övningen. Själva övningen behålls.",
  "このエクササイズの記録されたスコアを削除します。エクササイズ自体は残ります。",
  "이 연습에 기록된 점수를 삭제합니다. 연습 자체는 유지됩니다.",
  "删除该练习记录的得分。练习本身会保留。")
T("Delete All Scores", "Alle Punktzahlen löschen", "Eliminar todas las puntuaciones", "Supprimer toutes les notes", "Elimina tutti i punteggi", "Excluir todas as pontuações", "Alle scores verwijderen", "Удалить все оценки", "Usuń wszystkie wyniki", "Tüm puanları sil", "Radera alla poäng", "すべてのスコアを削除", "모든 점수 삭제", "删除所有得分")
T("Deletes the scores of every exercise, including any left behind by exercises you have since deleted. The exercises themselves are kept.",
  "Löscht die Punktzahlen aller Übungen, auch die von inzwischen gelöschten Übungen. Die Übungen selbst bleiben erhalten.",
  "Elimina las puntuaciones de todos los ejercicios, incluidas las que dejaron ejercicios que ya borraste. Los ejercicios se conservan.",
  "Supprime les notes de tous les exercices, y compris celles laissées par des exercices depuis supprimés. Les exercices eux-mêmes sont conservés.",
  "Elimina i punteggi di tutti gli esercizi, compresi quelli lasciati da esercizi che hai già eliminato. Gli esercizi stessi vengono mantenuti.",
  "Exclui as pontuações de todos os exercícios, inclusive as deixadas por exercícios que você já excluiu. Os exercícios em si são mantidos.",
  "Verwijdert de scores van alle oefeningen, ook die van inmiddels verwijderde oefeningen. De oefeningen zelf blijven behouden.",
  "Удаляет оценки всех упражнений, включая оставшиеся от уже удалённых. Сами упражнения остаются.",
  "Usuwa wyniki wszystkich ćwiczeń, w tym te pozostałe po ćwiczeniach już usuniętych. Same ćwiczenia pozostają.",
  "Tüm egzersizlerin puanlarını, bu arada sildiğiniz egzersizlerden kalanlar dahil siler. Egzersizlerin kendisi kalır.",
  "Raderar poängen för alla övningar, även sådana som lämnats kvar av övningar du sedan raderat. Själva övningarna behålls.",
  "すべてのエクササイズのスコアを、すでに削除したエクササイズの分も含めて削除します。エクササイズ自体は残ります。",
  "이미 삭제한 연습이 남긴 것까지 포함해 모든 연습의 점수를 삭제합니다. 연습 자체는 유지됩니다.",
  "删除所有练习的得分，包括你此前删除的练习遗留的记录。练习本身会保留。")
T("The scores recorded for “%@” will be deleted.",
  "Die aufgezeichneten Punktzahlen von „%@“ werden gelöscht.",
  "Se eliminarán las puntuaciones registradas de «%@».",
  "Les notes enregistrées pour « %@ » seront supprimées.",
  "I punteggi registrati per “%@” verranno eliminati.",
  "As pontuações registradas de “%@” serão excluídas.",
  "De vastgelegde scores van ‘%@’ worden verwijderd.",
  "Записанные оценки «%@» будут удалены.",
  "Zapisane wyniki „%@” zostaną usunięte.",
  "“%@” için kaydedilen puanlar silinecek.",
  "De sparade poängen för ”%@” raderas.",
  "「%@」の記録されたスコアが削除されます。",
  "“%@”에 기록된 점수가 삭제됩니다.",
  "将删除“%@”记录的得分。")
T("The scores recorded for every exercise will be deleted.",
  "Die aufgezeichneten Punktzahlen aller Übungen werden gelöscht.",
  "Se eliminarán las puntuaciones registradas de todos los ejercicios.",
  "Les notes enregistrées pour tous les exercices seront supprimées.",
  "I punteggi registrati per tutti gli esercizi verranno eliminati.",
  "As pontuações registradas de todos os exercícios serão excluídas.",
  "De vastgelegde scores van alle oefeningen worden verwijderd.",
  "Записанные оценки всех упражнений будут удалены.",
  "Zapisane wyniki wszystkich ćwiczeń zostaną usunięte.",
  "Tüm egzersizler için kaydedilen puanlar silinecek.",
  "De sparade poängen för alla övningar raderas.",
  "すべてのエクササイズの記録されたスコアが削除されます。",
  "모든 연습에 기록된 점수가 삭제됩니다.",
  "将删除所有练习记录的得分。")

# --- Reset ▸ Settings ---
T("Categories", "Kategorien", "Categorías", "Catégories", "Categorie", "Categorias", "Categorieën", "Категории", "Kategorie", "Kategoriler", "Kategorier", "カテゴリ", "카테고리", "类别")
T("Reset All Settings", "Alle Einstellungen zurücksetzen", "Restablecer todos los ajustes", "Réinitialiser tous les réglages", "Ripristina tutte le impostazioni", "Redefinir todas as configurações", "Alle instellingen herstellen", "Сбросить все настройки", "Zresetuj wszystkie ustawienia", "Tüm ayarları sıfırla", "Återställ alla inställningar", "すべての設定をリセット", "모든 설정 초기화", "重置所有设置")
T("Puts every category above back at once. Your exercises, scores and routines are untouched.",
  "Setzt alle Kategorien oben auf einmal zurück. Deine Übungen, Punktzahlen und Routinen bleiben unberührt.",
  "Restablece de una vez todas las categorías de arriba. Tus ejercicios, puntuaciones y rutinas no se tocan.",
  "Réinitialise d’un coup toutes les catégories ci-dessus. Vos exercices, vos notes et vos routines ne sont pas touchés.",
  "Ripristina in una volta tutte le categorie qui sopra. I tuoi esercizi, punteggi e routine restano intatti.",
  "Redefine de uma vez todas as categorias acima. Seus exercícios, pontuações e rotinas não são alterados.",
  "Zet alle categorieën hierboven in één keer terug. Je oefeningen, scores en routines blijven ongemoeid.",
  "Сбрасывает все категории выше сразу. Ваши упражнения, оценки и программы не затрагиваются.",
  "Resetuje naraz wszystkie kategorie powyżej. Twoje ćwiczenia, wyniki i rutyny pozostają nietknięte.",
  "Yukarıdaki tüm kategorileri tek seferde sıfırlar. Egzersizleriniz, puanlarınız ve rutinleriniz etkilenmez.",
  "Återställer alla kategorier ovan på en gång. Dina övningar, poäng och rutiner rörs inte.",
  "上のすべてのカテゴリを一度にリセットします。エクササイズ、スコア、ルーティンはそのままです。",
  "위의 모든 카테고리를 한 번에 초기화합니다. 연습, 점수, 루틴은 그대로 유지됩니다.",
  "一次性重置上面的所有类别。你的练习、得分和训练组不受影响。")
T("The settings under “%@” go back to how the app started out.",
  "Die Einstellungen unter „%@“ werden auf den Anfangszustand der App zurückgesetzt.",
  "Los ajustes de «%@» volverán a como empezó la app.",
  "Les réglages de « %@ » reviennent à l’état initial de l’app.",
  "Le impostazioni in “%@” tornano a com’erano all’avvio dell’app.",
  "As configurações em “%@” voltam ao estado inicial do app.",
  "De instellingen onder ‘%@’ gaan terug naar hoe de app begon.",
  "Настройки в разделе «%@» вернутся к исходному состоянию приложения.",
  "Ustawienia w sekcji „%@” wrócą do stanu początkowego aplikacji.",
  "“%@” altındaki ayarlar uygulamanın başlangıç durumuna döner.",
  "Inställningarna under ”%@” återgår till hur appen började.",
  "「%@」の設定がアプリの初期状態に戻ります。",
  "“%@”의 설정이 앱의 초기 상태로 돌아갑니다.",
  "“%@”下的设置将恢复到应用最初的状态。")
T("Every setting in the app goes back to how it started out.",
  "Alle Einstellungen der App werden auf den Anfangszustand zurückgesetzt.",
  "Todos los ajustes de la app volverán a como empezaron.",
  "Tous les réglages de l’app reviennent à leur état initial.",
  "Tutte le impostazioni dell’app tornano a com’erano all’inizio.",
  "Todas as configurações do app voltam ao estado inicial.",
  "Alle instellingen in de app gaan terug naar hoe ze begonnen.",
  "Все настройки приложения вернутся к исходному состоянию.",
  "Wszystkie ustawienia aplikacji wrócą do stanu początkowego.",
  "Uygulamadaki tüm ayarlar başlangıç durumuna döner.",
  "Alla inställningar i appen återgår till hur de började.",
  "アプリのすべての設定が初期状態に戻ります。",
  "앱의 모든 설정이 초기 상태로 돌아갑니다.",
  "应用的所有设置将恢复到最初的状态。")
T("Clears the username you chose. Your device ID and your exercises are kept.",
  "Löscht den von dir gewählten Benutzernamen. Deine Geräte-ID und deine Übungen bleiben erhalten.",
  "Borra el nombre de usuario que elegiste. Tu ID del dispositivo y tus ejercicios se conservan.",
  "Efface le nom d’utilisateur que vous avez choisi. Votre identifiant de l’appareil et vos exercices sont conservés.",
  "Cancella il nome utente che hai scelto. L’ID dispositivo e i tuoi esercizi vengono mantenuti.",
  "Limpa o nome de usuário que você escolheu. Seu ID do dispositivo e seus exercícios são mantidos.",
  "Wist de gebruikersnaam die je koos. Je apparaat-ID en je oefeningen blijven behouden.",
  "Очищает выбранное вами имя пользователя. Идентификатор устройства и упражнения остаются.",
  "Czyści wybraną przez ciebie nazwę użytkownika. Identyfikator urządzenia i twoje ćwiczenia pozostają.",
  "Seçtiğiniz kullanıcı adını temizler. Cihaz kimliğiniz ve egzersizleriniz kalır.",
  "Rensar användarnamnet du valde. Ditt enhets-ID och dina övningar behålls.",
  "設定したユーザー名を消去します。デバイスIDとエクササイズは残ります。",
  "직접 정한 사용자 이름을 지웁니다. 기기 ID와 연습은 유지됩니다.",
  "清除你设置的用户名。设备 ID 和练习会保留。")
T("Puts the instrument, the playback and recording devices and the microphone delay back to their starting values. Instruments you uploaded are kept.",
  "Setzt das Instrument, die Wiedergabe- und Aufnahmegeräte und die Mikrofonverzögerung auf die Anfangswerte zurück. Von dir hochgeladene Instrumente bleiben erhalten.",
  "Restablece el instrumento, los dispositivos de reproducción y grabación y el retardo del micrófono a sus valores iniciales. Los instrumentos que subiste se conservan.",
  "Remet l’instrument, les appareils de lecture et d’enregistrement et le retard du micro à leurs valeurs initiales. Les instruments que vous avez importés sont conservés.",
  "Riporta lo strumento, i dispositivi di riproduzione e registrazione e il ritardo del microfono ai valori iniziali. Gli strumenti che hai caricato vengono mantenuti.",
  "Volta o instrumento, os dispositivos de reprodução e gravação e o atraso do microfone aos valores iniciais. Os instrumentos que você enviou são mantidos.",
  "Zet het instrument, de weergave- en opnameapparaten en de microfoonvertraging terug op hun beginwaarden. Instrumenten die je hebt geüpload blijven behouden.",
  "Возвращает инструмент, устройства воспроизведения и записи и задержку микрофона к исходным значениям. Загруженные вами инструменты остаются.",
  "Przywraca instrument, urządzenia odtwarzania i nagrywania oraz opóźnienie mikrofonu do wartości początkowych. Instrumenty, które wgrałeś, pozostają.",
  "Enstrümanı, çalma ve kayıt aygıtlarını ve mikrofon gecikmesini başlangıç değerlerine döndürür. Yüklediğiniz enstrümanlar kalır.",
  "Återställer instrumentet, uppspelnings- och inspelningsenheterna och mikrofonfördröjningen till sina ursprungsvärden. Instrument du laddat upp behålls.",
  "楽器、再生・録音デバイス、マイク遅延を初期値に戻します。アップロードした楽器は残ります。",
  "악기, 재생 및 녹음 기기, 마이크 지연을 초기값으로 되돌립니다. 직접 업로드한 악기는 유지됩니다.",
  "将乐器、播放和录音设备以及麦克风延迟恢复为初始值。你上传的乐器会保留。")
T("Puts the theme, the orientation lock and the look of the menus and the playback screen back to how they started out. Templates you saved are deleted, and the app's own two come back as they started out.",
  "Setzt das Erscheinungsbild, die Ausrichtungssperre und das Aussehen der Menüs und des Wiedergabebildschirms auf den Anfangszustand zurück. Von dir gespeicherte Vorlagen werden gelöscht, und die beiden der App kommen so zurück, wie sie am Anfang waren.",
  "Restablece el tema, el bloqueo de orientación y el aspecto de los menús y de la pantalla de reproducción a como empezaron. Las plantillas que guardaste se eliminan, y las dos de la app vuelven a como empezaron.",
  "Remet le thème, le verrouillage de l’orientation et l’apparence des menus et de l’écran de lecture dans leur état initial. Les modèles que vous avez enregistrés sont supprimés, et les deux modèles de l’app reviennent à leur état initial.",
  "Riporta il tema, il blocco dell’orientamento e l’aspetto dei menu e della schermata di riproduzione a com’erano all’inizio. I modelli che hai salvato vengono eliminati e i due dell’app tornano com’erano all’inizio.",
  "Volta o tema, o bloqueio de orientação e a aparência dos menus e da tela de reprodução ao estado inicial. Os modelos que você salvou são excluídos, e os dois do app voltam como eram no início.",
  "Zet het thema, de oriëntatievergrendeling en het uiterlijk van de menu’s en het afspeelscherm terug zoals ze begonnen. Sjablonen die je hebt bewaard worden verwijderd, en de twee van de app komen terug zoals ze begonnen.",
  "Возвращает оформление, блокировку ориентации и вид меню и экрана воспроизведения к исходному состоянию. Сохранённые вами шаблоны удаляются, а два шаблона приложения возвращаются в исходном виде.",
  "Przywraca motyw, blokadę orientacji oraz wygląd menu i ekranu odtwarzania do stanu początkowego. Zapisane przez ciebie szablony zostają usunięte, a dwa szablony aplikacji wracają w stanie początkowym.",
  "Temayı, yönlendirme kilidini ve menülerle çalma ekranının görünümünü başlangıç durumuna döndürür. Kaydettiğiniz şablonlar silinir ve uygulamanın kendi iki şablonu başlangıçtaki hâliyle geri gelir.",
  "Återställer temat, orienteringslåset och utseendet på menyerna och uppspelningsskärmen till hur de började. Mallar du sparat tas bort, och appens två egna kommer tillbaka som de började.",
  "テーマ、画面の向きのロック、メニューと再生画面の見た目を初期状態に戻します。保存したテンプレートは削除され、アプリの 2 つのテンプレートは初期状態で戻ります。",
  "테마, 화면 방향 잠금, 메뉴와 재생 화면의 모양을 초기 상태로 되돌립니다. 저장한 템플릿은 삭제되고, 앱의 템플릿 두 개는 초기 상태로 돌아옵니다.",
  "将主题、方向锁定以及菜单和播放界面的外观恢复到最初的状态。你保存的模板会被删除，应用自带的两个模板会恢复到最初的状态。")
T("Clears your vocal range, including the custom lowest and highest notes, and puts the target window back to the whole note.",
  "Löscht deinen Stimmumfang samt den eigenen tiefsten und höchsten Noten und setzt das Zielfenster wieder auf die ganze Note.",
  "Borra tu tesitura, incluidas las notas más grave y más aguda personalizadas, y devuelve la ventana objetivo a la nota entera.",
  "Efface votre tessiture, y compris les notes la plus grave et la plus aiguë personnalisées, et remet la fenêtre cible sur la note entière.",
  "Cancella la tua estensione vocale, comprese le note più bassa e più alta personalizzate, e riporta la finestra target all’intera nota.",
  "Limpa sua extensão vocal, incluindo as notas mais grave e mais aguda personalizadas, e devolve a janela alvo à nota inteira.",
  "Wist je stembereik, inclusief de eigen laagste en hoogste noot, en zet het doelvenster terug op de hele noot.",
  "Очищает ваш диапазон голоса, включая собственные самую низкую и самую высокую ноты, и возвращает целевое окно ко всей ноте.",
  "Czyści twoją skalę głosu wraz z własnymi najniższą i najwyższą nutą i przywraca okno docelowe do całej nuty.",
  "Ses aralığınızı, özel en pes ve en tiz notalar dahil temizler ve hedef pencereyi tüm notaya geri döndürür.",
  "Rensar ditt röstomfång, inklusive de egna lägsta och högsta tonerna, och återställer målfönstret till hela noten.",
  "声域を、カスタムの最低音と最高音を含めて消去し、ターゲット範囲を音符全体に戻します。",
  "직접 지정한 최저음과 최고음을 포함해 음역대를 지우고, 목표 범위를 음표 전체로 되돌립니다.",
  "清除你的音域，包括自定的最低音和最高音，并将目标范围恢复为整个音符。")
T("Puts the number of recommended exercises back, and returns the whitelist to every exercise in your library, dropping the ones you ticked or unticked yourself.",
  "Setzt die Anzahl der empfohlenen Übungen zurück und lässt wieder alle Übungen deiner Bibliothek zu; selbst an- oder abgewählte Übungen werden dabei verworfen.",
  "Restablece el número de ejercicios recomendados y vuelve a permitir todos los ejercicios de tu biblioteca, descartando los que marcaste o desmarcaste tú.",
  "Rétablit le nombre d’exercices recommandés et autorise de nouveau tous les exercices de votre bibliothèque, en abandonnant ceux que vous aviez cochés ou décochés vous-même.",
  "Ripristina il numero di esercizi consigliati e riammette tutti gli esercizi della tua libreria, scartando quelli che avevi selezionato o deselezionato tu.",
  "Restaura o número de exercícios recomendados e volta a permitir todos os exercícios da sua biblioteca, descartando os que você marcou ou desmarcou.",
  "Zet het aantal aanbevolen oefeningen terug en staat weer alle oefeningen in je bibliotheek toe, waarbij de oefeningen die je zelf aan- of uitvinkte vervallen.",
  "Возвращает количество рекомендуемых упражнений и снова разрешает все упражнения в вашей библиотеке, отменяя те, что вы отметили или сняли сами.",
  "Przywraca liczbę polecanych ćwiczeń i ponownie dopuszcza wszystkie ćwiczenia w twojej bibliotece, odrzucając te, które sam zaznaczyłeś lub odznaczyłeś.",
  "Önerilen egzersiz sayısını geri getirir ve kitaplığındaki tüm egzersizlere yeniden izin verir; kendin işaretlediklerin ya da işaretini kaldırdıkların silinir.",
  "Återställer antalet rekommenderade övningar och tillåter åter alla övningar i ditt bibliotek, och släpper dem du själv kryssat i eller ur.",
  "おすすめエクササイズの数を元に戻し、ライブラリのすべてのエクササイズを再び対象にします。自分で付け外ししたチェックは破棄されます。",
  "추천 연습 개수를 되돌리고, 라이브러리의 모든 연습을 다시 허용하며 직접 선택하거나 해제한 항목은 사라집니다.",
  "恢复推荐练习的数量，并将练习库中的全部练习重新列入，同时放弃你自己勾选或取消的项。")
T("Puts the app's language back to English.",
  "Setzt die Sprache der App wieder auf Englisch.",
  "Devuelve el idioma de la app al inglés.",
  "Remet la langue de l’app en anglais.",
  "Riporta la lingua dell’app all’inglese.",
  "Volta o idioma do app para o inglês.",
  "Zet de taal van de app terug op Engels.",
  "Возвращает язык приложения на английский.",
  "Przywraca język aplikacji na angielski.",
  "Uygulamanın dilini yeniden İngilizceye ayarlar.",
  "Ställer tillbaka appens språk till engelska.",
  "アプリの言語を英語に戻します。",
  "앱의 언어를 영어로 되돌립니다.",
  "将应用语言恢复为英语。")

# --- Reset ▸ Exercises ---
T("Your exercises", "Deine Übungen", "Tus ejercicios", "Vos exercices", "I tuoi esercizi", "Seus exercícios", "Jouw oefeningen", "Ваши упражнения", "Twoje ćwiczenia", "Egzersizleriniz", "Dina övningar", "自分のエクササイズ", "내 연습", "你的练习")
T("Delete Own Exercises", "Eigene Übungen löschen", "Eliminar ejercicios propios", "Supprimer mes exercices", "Elimina esercizi personali", "Excluir meus exercícios", "Eigen oefeningen verwijderen", "Удалить свои упражнения", "Usuń własne ćwiczenia", "Kendi egzersizlerimi sil", "Radera egna övningar", "自分のエクササイズを削除", "내 연습 삭제", "删除自己的练习")
T("Deletes every exercise you created yourself, with its MIDI pattern and scores. Exercises that came with the app or from the Community tab are kept.",
  "Löscht jede Übung, die du selbst erstellt hast, samt ihrem MIDI-Muster und ihren Punktzahlen. Mitgelieferte Übungen und die aus dem Community-Tab bleiben erhalten.",
  "Elimina todos los ejercicios que creaste tú, con su patrón MIDI y sus puntuaciones. Se conservan los que vienen con la app y los de la pestaña Comunidad.",
  "Supprime chaque exercice que vous avez créé, avec son motif MIDI et ses notes. Les exercices fournis avec l’app et ceux de l’onglet Communauté sont conservés.",
  "Elimina ogni esercizio che hai creato tu, con il suo pattern MIDI e i suoi punteggi. Restano gli esercizi inclusi nell’app e quelli della scheda Community.",
  "Exclui todos os exercícios que você mesmo criou, com seu padrão MIDI e suas pontuações. Os que vêm com o app e os da aba Comunidade são mantidos.",
  "Verwijdert elke oefening die je zelf hebt gemaakt, met haar MIDI-patroon en scores. Meegeleverde oefeningen en die uit het tabblad Community blijven behouden.",
  "Удаляет каждое упражнение, созданное вами, вместе с его MIDI-рисунком и оценками. Встроенные упражнения и упражнения из вкладки «Сообщество» остаются.",
  "Usuwa każde ćwiczenie utworzone przez ciebie wraz z jego wzorem MIDI i wynikami. Ćwiczenia dołączone do aplikacji i te z karty Społeczność pozostają.",
  "Kendi oluşturduğunuz her egzersizi, MIDI deseni ve puanlarıyla birlikte siler. Uygulamayla gelenler ve Topluluk sekmesinden gelenler kalır.",
  "Raderar varje övning du själv skapat, med dess MIDI-mönster och poäng. Övningar som följde med appen och de från fliken Community behålls.",
  "自分で作成したエクササイズを、MIDIパターンとスコアも含めてすべて削除します。アプリに付属するものとコミュニティタブのものは残ります。",
  "직접 만든 모든 연습을 MIDI 패턴과 점수까지 함께 삭제합니다. 앱에 포함된 연습과 커뮤니티 탭에서 받은 연습은 유지됩니다.",
  "删除你自己创建的每个练习，连同其 MIDI 音型和得分。应用自带的练习和来自“社区”标签的练习会保留。")
T("Delete Downloaded Exercises", "Heruntergeladene Übungen löschen", "Eliminar ejercicios descargados", "Supprimer les exercices téléchargés", "Elimina gli esercizi scaricati", "Excluir exercícios baixados", "Gedownloade oefeningen verwijderen", "Удалить скачанные упражнения", "Usuń pobrane ćwiczenia", "İndirilen egzersizleri sil", "Radera nedladdade övningar", "ダウンロードしたエクササイズを削除", "내려받은 연습 삭제", "删除已下载的练习")
T("Deletes every exercise you downloaded from the Community tab, with its MIDI pattern and scores. Your own exercises and the ones that came with the app are kept.",
  "Löscht jede Übung, die du aus dem Community-Tab heruntergeladen hast, samt ihrem MIDI-Muster und ihren Punktzahlen. Deine eigenen und die mitgelieferten Übungen bleiben erhalten.",
  "Elimina todos los ejercicios que descargaste de la pestaña Comunidad, con su patrón MIDI y sus puntuaciones. Tus propios ejercicios y los que vienen con la app se conservan.",
  "Supprime chaque exercice téléchargé depuis l’onglet Communauté, avec son motif MIDI et ses notes. Vos propres exercices et ceux fournis avec l’app sont conservés.",
  "Elimina ogni esercizio scaricato dalla scheda Community, con il suo pattern MIDI e i suoi punteggi. I tuoi esercizi e quelli inclusi nell’app restano.",
  "Exclui todos os exercícios que você baixou da aba Comunidade, com seu padrão MIDI e suas pontuações. Seus próprios exercícios e os que vêm com o app são mantidos.",
  "Verwijdert elke oefening die je uit het tabblad Community hebt gedownload, met haar MIDI-patroon en scores. Je eigen oefeningen en de meegeleverde blijven behouden.",
  "Удаляет каждое упражнение, скачанное из вкладки «Сообщество», вместе с его MIDI-рисунком и оценками. Ваши собственные и встроенные упражнения остаются.",
  "Usuwa każde ćwiczenie pobrane z karty Społeczność wraz z jego wzorem MIDI i wynikami. Twoje własne ćwiczenia i te dołączone do aplikacji pozostają.",
  "Topluluk sekmesinden indirdiğiniz her egzersizi, MIDI deseni ve puanlarıyla birlikte siler. Kendi egzersizleriniz ve uygulamayla gelenler kalır.",
  "Raderar varje övning du laddat ner från fliken Community, med dess MIDI-mönster och poäng. Dina egna övningar och de som följde med appen behålls.",
  "コミュニティタブからダウンロードしたエクササイズを、MIDIパターンとスコアも含めてすべて削除します。自作のものとアプリに付属するものは残ります。",
  "커뮤니티 탭에서 내려받은 모든 연습을 MIDI 패턴과 점수까지 함께 삭제합니다. 직접 만든 연습과 앱에 포함된 연습은 유지됩니다.",
  "删除你从“社区”标签下载的每个练习，连同其 MIDI 音型和得分。你自己的练习和应用自带的练习会保留。")
T("You haven't changed any of the exercises that came with the app.",
  "Du hast keine der mitgelieferten Übungen geändert.",
  "No has cambiado ninguno de los ejercicios que vienen con la app.",
  "Vous n’avez modifié aucun des exercices fournis avec l’app.",
  "Non hai modificato nessuno degli esercizi inclusi nell’app.",
  "Você não alterou nenhum dos exercícios que vêm com o app.",
  "Je hebt geen van de meegeleverde oefeningen gewijzigd.",
  "Вы не изменяли ни одного встроенного упражнения.",
  "Nie zmieniłeś żadnego z ćwiczeń dołączonych do aplikacji.",
  "Uygulamayla gelen egzersizlerin hiçbirini değiştirmediniz.",
  "Du har inte ändrat någon av övningarna som följde med appen.",
  "アプリに付属するエクササイズはまだ変更されていません。",
  "앱에 포함된 연습을 아직 변경하지 않았습니다.",
  "你尚未更改任何应用自带的练习。")
T("Deleted", "Gelöscht", "Eliminado", "Supprimé", "Eliminato", "Excluído", "Verwijderd", "Удалено", "Usunięte", "Silindi", "Raderad", "削除済み", "삭제됨", "已删除")
T("Puts this exercise back to how it came with the app, undoing your edits to its settings and its MIDI pattern.",
  "Setzt diese Übung auf den mitgelieferten Zustand zurück und macht deine Änderungen an ihren Einstellungen und ihrem MIDI-Muster rückgängig.",
  "Devuelve este ejercicio a como venía con la app y deshace tus cambios en sus ajustes y en su patrón MIDI.",
  "Rétablit cet exercice tel qu’il était fourni avec l’app, en annulant vos modifications de ses réglages et de son motif MIDI.",
  "Riporta questo esercizio a com’era incluso nell’app, annullando le tue modifiche alle impostazioni e al pattern MIDI.",
  "Volta este exercício ao estado em que veio com o app, desfazendo suas alterações nas configurações e no padrão MIDI.",
  "Zet deze oefening terug zoals ze met de app meekwam en maakt je wijzigingen aan haar instellingen en MIDI-patroon ongedaan.",
  "Возвращает это упражнение к встроенному виду, отменяя ваши правки его настроек и MIDI-рисунка.",
  "Przywraca to ćwiczenie do postaci dołączonej do aplikacji, cofając twoje zmiany w jego ustawieniach i wzorze MIDI.",
  "Bu egzersizi uygulamayla geldiği haline döndürür; ayarlarında ve MIDI deseninde yaptığınız değişiklikleri geri alır.",
  "Återställer den här övningen till hur den följde med appen och ångrar dina ändringar av dess inställningar och MIDI-mönster.",
  "このエクササイズをアプリ付属の状態に戻し、設定とMIDIパターンへの変更を取り消します。",
  "이 연습을 앱에 포함되었던 상태로 되돌리고, 설정과 MIDI 패턴에 가한 편집을 취소합니다.",
  "将该练习恢复为应用自带时的状态，撤销你对其设置和 MIDI 音型的修改。")
T("Revert All Bundled Exercises",
  "Alle mitgelieferten Übungen zurücksetzen",
  "Restaurar todos los ejercicios incluidos",
  "Rétablir tous les exercices fournis",
  "Ripristina tutti gli esercizi inclusi",
  "Restaurar todos os exercícios incluídos",
  "Alle meegeleverde oefeningen herstellen",
  "Восстановить все встроенные упражнения",
  "Przywróć wszystkie dołączone ćwiczenia",
  "Uygulamayla gelen tüm egzersizleri geri yükle",
  "Återställ alla medföljande övningar",
  "付属のエクササイズをすべて元に戻す",
  "기본 제공 연습 모두 되돌리기",
  "还原所有自带练习")
T("Puts every exercise that came with the app back to how it shipped, bringing back any you deleted.",
  "Setzt alle mitgelieferten Übungen auf den Auslieferungszustand zurück und holt gelöschte wieder zurück.",
  "Devuelve todos los ejercicios que vienen con la app a su estado original y recupera los que hayas borrado.",
  "Rétablit tous les exercices fournis avec l’app dans leur état d’origine et récupère ceux que vous avez supprimés.",
  "Riporta tutti gli esercizi inclusi nell’app allo stato originale e recupera quelli che hai eliminato.",
  "Volta todos os exercícios que vêm com o app ao estado original e recupera os que você excluiu.",
  "Zet alle meegeleverde oefeningen terug naar hun oorspronkelijke staat en haalt verwijderde weer terug.",
  "Возвращает все встроенные упражнения к исходному виду и восстанавливает удалённые.",
  "Przywraca wszystkie ćwiczenia dołączone do aplikacji do pierwotnej postaci i odzyskuje te usunięte.",
  "Uygulamayla gelen tüm egzersizleri özgün haline döndürür ve sildiklerinizi geri getirir.",
  "Återställer alla övningar som följde med appen till sitt ursprungliga skick och tar tillbaka dem du raderat.",
  "アプリに付属するすべてのエクササイズを出荷時の状態に戻し、削除したものも復元します。",
  "앱에 포함된 모든 연습을 원래 상태로 되돌리고, 삭제한 연습도 복원합니다.",
  "将应用自带的所有练习恢复为出厂状态，并找回你删除的练习。")
T("Every exercise you created yourself will be deleted, along with its MIDI pattern and scores.",
  "Jede Übung, die du selbst erstellt hast, wird samt ihrem MIDI-Muster und ihren Punktzahlen gelöscht.",
  "Se eliminarán todos los ejercicios que creaste tú, junto con su patrón MIDI y sus puntuaciones.",
  "Chaque exercice que vous avez créé sera supprimé, avec son motif MIDI et ses notes.",
  "Ogni esercizio che hai creato tu verrà eliminato, insieme al suo pattern MIDI e ai suoi punteggi.",
  "Todos os exercícios que você mesmo criou serão excluídos, junto com seu padrão MIDI e suas pontuações.",
  "Elke oefening die je zelf hebt gemaakt wordt verwijderd, samen met haar MIDI-patroon en scores.",
  "Каждое упражнение, созданное вами, будет удалено вместе с его MIDI-рисунком и оценками.",
  "Każde ćwiczenie utworzone przez ciebie zostanie usunięte wraz z jego wzorem MIDI i wynikami.",
  "Kendi oluşturduğunuz her egzersiz, MIDI deseni ve puanlarıyla birlikte silinecek.",
  "Varje övning du själv skapat raderas, tillsammans med dess MIDI-mönster och poäng.",
  "自分で作成したすべてのエクササイズが、MIDIパターンとスコアとともに削除されます。",
  "직접 만든 모든 연습이 MIDI 패턴 및 점수와 함께 삭제됩니다.",
  "你自己创建的每个练习都将被删除，连同其 MIDI 音型和得分。")
T("Every exercise you downloaded from the Community tab will be deleted, along with its MIDI pattern and scores.",
  "Jede Übung, die du aus dem Community-Tab heruntergeladen hast, wird samt ihrem MIDI-Muster und ihren Punktzahlen gelöscht.",
  "Se eliminarán todos los ejercicios que descargaste de la pestaña Comunidad, junto con su patrón MIDI y sus puntuaciones.",
  "Chaque exercice téléchargé depuis l’onglet Communauté sera supprimé, avec son motif MIDI et ses notes.",
  "Ogni esercizio scaricato dalla scheda Community verrà eliminato, insieme al suo pattern MIDI e ai suoi punteggi.",
  "Todos os exercícios que você baixou da aba Comunidade serão excluídos, junto com seu padrão MIDI e suas pontuações.",
  "Elke oefening die je uit het tabblad Community hebt gedownload wordt verwijderd, samen met haar MIDI-patroon en scores.",
  "Каждое упражнение, скачанное из вкладки «Сообщество», будет удалено вместе с его MIDI-рисунком и оценками.",
  "Każde ćwiczenie pobrane z karty Społeczność zostanie usunięte wraz z jego wzorem MIDI i wynikami.",
  "Topluluk sekmesinden indirdiğiniz her egzersiz, MIDI deseni ve puanlarıyla birlikte silinecek.",
  "Varje övning du laddat ner från fliken Community raderas, tillsammans med dess MIDI-mönster och poäng.",
  "コミュニティタブからダウンロードしたすべてのエクササイズが、MIDIパターンとスコアとともに削除されます。",
  "커뮤니티 탭에서 내려받은 모든 연습이 MIDI 패턴 및 점수와 함께 삭제됩니다.",
  "你从“社区”标签下载的每个练习都将被删除，连同其 MIDI 音型和得分。")
T("“%@” goes back to how it came with the app.",
  "„%@“ wird auf den mitgelieferten Zustand zurückgesetzt.",
  "«%@» volverá a como venía con la app.",
  "« %@ » revient tel qu’il était fourni avec l’app.",
  "“%@” torna a com’era incluso nell’app.",
  "“%@” volta ao estado em que veio com o app.",
  "‘%@’ gaat terug naar hoe ze met de app meekwam.",
  "«%@» вернётся к встроенному виду.",
  "„%@” wróci do postaci dołączonej do aplikacji.",
  "“%@” uygulamayla geldiği haline döner.",
  "”%@” återgår till hur den följde med appen.",
  "「%@」がアプリ付属の状態に戻ります。",
  "“%@”이(가) 앱에 포함되었던 상태로 돌아갑니다.",
  "“%@”将恢复为应用自带时的状态。")
T("Every exercise that came with the app goes back to how it shipped, and any you deleted come back.",
  "Alle mitgelieferten Übungen werden auf den Auslieferungszustand zurückgesetzt, und gelöschte kommen zurück.",
  "Todos los ejercicios que vienen con la app volverán a su estado original, y los que borraste reaparecerán.",
  "Tous les exercices fournis avec l’app reviennent à leur état d’origine, et ceux que vous avez supprimés réapparaissent.",
  "Tutti gli esercizi inclusi nell’app tornano allo stato originale e quelli eliminati ricompaiono.",
  "Todos os exercícios que vêm com o app voltam ao estado original, e os que você excluiu reaparecem.",
  "Alle meegeleverde oefeningen gaan terug naar hun oorspronkelijke staat, en verwijderde komen terug.",
  "Все встроенные упражнения вернутся к исходному виду, а удалённые появятся снова.",
  "Wszystkie ćwiczenia dołączone do aplikacji wrócą do pierwotnej postaci, a usunięte pojawią się ponownie.",
  "Uygulamayla gelen tüm egzersizler özgün haline döner ve sildikleriniz geri gelir.",
  "Alla övningar som följde med appen återgår till sitt ursprungliga skick, och de du raderat kommer tillbaka.",
  "アプリに付属するすべてのエクササイズが出荷時の状態に戻り、削除したものも復元されます。",
  "앱에 포함된 모든 연습이 원래 상태로 돌아가고, 삭제한 연습도 다시 나타납니다.",
  "应用自带的所有练习将恢复为出厂状态，你删除的练习也会回来。")

# --- Reset ▸ Home ---
T("Clear Favourites", "Favoriten leeren", "Vaciar favoritos", "Vider les favoris", "Svuota i preferiti", "Limpar favoritos", "Favorieten leegmaken", "Очистить избранное", "Wyczyść ulubione", "Favorileri temizle", "Rensa favoriter", "お気に入りを空にする", "즐겨찾기 비우기", "清空收藏")
T("Empties the Home tab's “Favourites” list. The exercises in it are kept.",
  "Leert die Liste „Favoriten“ im Start-Tab. Die darin enthaltenen Übungen bleiben erhalten.",
  "Vacía la lista «Favoritos» de la pestaña Inicio. Los ejercicios que contiene se conservan.",
  "Vide la liste « Favoris » de l’onglet Accueil. Les exercices qu’elle contient sont conservés.",
  "Svuota l’elenco “Preferiti” della scheda Home. Gli esercizi al suo interno vengono mantenuti.",
  "Esvazia a lista “Favoritos” da aba Início. Os exercícios nela são mantidos.",
  "Maakt de lijst ‘Favorieten’ op het tabblad Start leeg. De oefeningen erin blijven behouden.",
  "Очищает список «Избранное» на вкладке «Главная». Упражнения в нём остаются.",
  "Opróżnia listę „Ulubione” na karcie Start. Ćwiczenia z niej pozostają.",
  "Ana Sayfa sekmesindeki “Favoriler” listesini boşaltır. İçindeki egzersizler kalır.",
  "Tömmer listan ”Favoriter” på fliken Hem. Övningarna i den behålls.",
  "ホームタブの「お気に入り」リストを空にします。その中のエクササイズは残ります。",
  "홈 탭의 “즐겨찾기” 목록을 비웁니다. 목록에 있던 연습은 유지됩니다.",
  "清空“首页”标签的“收藏”列表。其中的练习会保留。")
T("Delete Routines", "Routinen löschen", "Eliminar rutinas", "Supprimer les routines", "Elimina le routine", "Excluir rotinas", "Routines verwijderen", "Удалить программы", "Usuń rutyny", "Rutinleri sil", "Radera rutiner", "ルーティンを削除", "루틴 삭제", "删除训练组")
T("Deletes every routine you assembled. The exercises they were made of are kept.",
  "Löscht alle Routinen, die du zusammengestellt hast. Die enthaltenen Übungen bleiben erhalten.",
  "Elimina todas las rutinas que armaste. Los ejercicios que las componían se conservan.",
  "Supprime toutes les routines que vous avez composées. Les exercices qui les composaient sont conservés.",
  "Elimina tutte le routine che hai composto. Gli esercizi che le componevano vengono mantenuti.",
  "Exclui todas as rotinas que você montou. Os exercícios que as compunham são mantidos.",
  "Verwijdert elke routine die je hebt samengesteld. De oefeningen waaruit ze bestonden blijven behouden.",
  "Удаляет все составленные вами программы. Упражнения, из которых они состояли, остаются.",
  "Usuwa wszystkie rutyny, które ułożyłeś. Ćwiczenia, z których się składały, pozostają.",
  "Oluşturduğunuz tüm rutinleri siler. Onları oluşturan egzersizler kalır.",
  "Raderar alla rutiner du satt ihop. Övningarna de bestod av behålls.",
  "作成したすべてのルーティンを削除します。含まれていたエクササイズは残ります。",
  "직접 구성한 모든 루틴을 삭제합니다. 루틴에 담겼던 연습은 유지됩니다.",
  "删除你编排的所有训练组。其中的练习会保留。")
T("Clear Practice Time", "Übungszeit löschen", "Borrar tiempo de práctica", "Effacer le temps de pratique", "Cancella il tempo di esercizio", "Limpar tempo de prática", "Oefentijd wissen", "Очистить время занятий", "Wyczyść czas ćwiczeń", "Çalışma süresini temizle", "Rensa övningstid", "練習時間を消去", "연습 시간 지우기", "清除练习时长")
T("Clear Recently Played", "Zuletzt gespielt leeren", "Vaciar reproducidos recientemente", "Vider les exercices récents", "Svuota i recenti", "Limpar reproduzidos recentemente", "Recent gespeeld wissen", "Очистить недавние", "Wyczyść ostatnio odtwarzane", "Son kullanılanları temizle", "Rensa senast spelade", "最近再生した履歴を消去", "최근 재생 기록 지우기", "清除最近播放")
T("Forgets what you played and when, emptying the Home tab's “Recent” list and the order “Recommended” picks by.",
  "Vergisst, was du wann gespielt hast: Die Liste „Zuletzt“ im Start-Tab wird geleert, ebenso die Reihenfolge, nach der „Empfohlen“ auswählt.",
  "Olvida qué tocaste y cuándo: vacía la lista «Recientes» de la pestaña Inicio y el orden por el que elige «Recomendado».",
  "Oublie ce que vous avez chanté et quand : vide la liste « Récents » de l’onglet Accueil ainsi que l’ordre selon lequel « Recommandé » choisit.",
  "Dimentica cosa hai eseguito e quando: svuota l’elenco “Recenti” della scheda Home e l’ordine con cui “Consigliati” sceglie.",
  "Esquece o que você tocou e quando: esvazia a lista “Recentes” da aba Início e a ordem pela qual “Recomendado” escolhe.",
  "Vergeet wat je wanneer speelde: maakt de lijst ‘Recent’ op het tabblad Start leeg, net als de volgorde waarop ‘Aanbevolen’ kiest.",
  "Забывает, что и когда вы пели: очищает список «Недавние» на вкладке «Главная» и порядок, по которому выбирает «Рекомендуемые».",
  "Zapomina, co i kiedy ćwiczyłeś: opróżnia listę „Ostatnie” na karcie Start oraz kolejność, według której wybiera „Polecane”.",
  "Neyi ne zaman çalıştığınızı unutur: Ana Sayfa sekmesindeki “Son kullanılan” listesini ve “Önerilen”in seçim sırasını boşaltır.",
  "Glömmer vad du spelat och när: tömmer listan ”Senaste” på fliken Hem och ordningen som ”Rekommenderat” väljer efter.",
  "何をいつ再生したかを忘れます。ホームタブの「最近」リストと、「おすすめ」が選ぶ順序が空になります。",
  "무엇을 언제 재생했는지 잊습니다. 홈 탭의 “최근” 목록과 “추천”이 고르는 순서가 비워집니다.",
  "忘记你练过什么、何时练的：清空“首页”标签的“最近”列表，以及“推荐”的排序依据。")
T("The Home tab's “Favourites” list will be emptied. The exercises in it are kept.",
  "Die Liste „Favoriten“ im Start-Tab wird geleert. Die darin enthaltenen Übungen bleiben erhalten.",
  "Se vaciará la lista «Favoritos» de la pestaña Inicio. Los ejercicios que contiene se conservan.",
  "La liste « Favoris » de l’onglet Accueil sera vidée. Les exercices qu’elle contient sont conservés.",
  "L’elenco “Preferiti” della scheda Home verrà svuotato. Gli esercizi al suo interno vengono mantenuti.",
  "A lista “Favoritos” da aba Início será esvaziada. Os exercícios nela são mantidos.",
  "De lijst ‘Favorieten’ op het tabblad Start wordt leeggemaakt. De oefeningen erin blijven behouden.",
  "Список «Избранное» на вкладке «Главная» будет очищен. Упражнения в нём остаются.",
  "Lista „Ulubione” na karcie Start zostanie opróżniona. Ćwiczenia z niej pozostają.",
  "Ana Sayfa sekmesindeki “Favoriler” listesi boşaltılacak. İçindeki egzersizler kalır.",
  "Listan ”Favoriter” på fliken Hem töms. Övningarna i den behålls.",
  "ホームタブの「お気に入り」リストが空になります。その中のエクササイズは残ります。",
  "홈 탭의 “즐겨찾기” 목록이 비워집니다. 목록에 있던 연습은 유지됩니다.",
  "将清空“首页”标签的“收藏”列表。其中的练习会保留。")
T("Every routine will be deleted. The exercises they were made of are kept.",
  "Alle Routinen werden gelöscht. Die enthaltenen Übungen bleiben erhalten.",
  "Se eliminarán todas las rutinas. Los ejercicios que las componían se conservan.",
  "Toutes les routines seront supprimées. Les exercices qui les composaient sont conservés.",
  "Tutte le routine verranno eliminate. Gli esercizi che le componevano vengono mantenuti.",
  "Todas as rotinas serão excluídas. Os exercícios que as compunham são mantidos.",
  "Elke routine wordt verwijderd. De oefeningen waaruit ze bestonden blijven behouden.",
  "Все программы будут удалены. Упражнения, из которых они состояли, остаются.",
  "Wszystkie rutyny zostaną usunięte. Ćwiczenia, z których się składały, pozostają.",
  "Tüm rutinler silinecek. Onları oluşturan egzersizler kalır.",
  "Alla rutiner raderas. Övningarna de bestod av behålls.",
  "すべてのルーティンが削除されます。含まれていたエクササイズは残ります。",
  "모든 루틴이 삭제됩니다. 루틴에 담겼던 연습은 유지됩니다.",
  "将删除所有训练组。其中的练习会保留。")
T("Your play history will be forgotten, emptying the Home tab's “Recent” list.",
  "Dein Wiedergabeverlauf wird vergessen und die Liste „Zuletzt“ im Start-Tab geleert.",
  "Se olvidará tu historial de reproducción y se vaciará la lista «Recientes» de la pestaña Inicio.",
  "Votre historique de lecture sera oublié et la liste « Récents » de l’onglet Accueil sera vidée.",
  "La cronologia di riproduzione verrà dimenticata e l’elenco “Recenti” della scheda Home sarà svuotato.",
  "Seu histórico de reprodução será esquecido e a lista “Recentes” da aba Início será esvaziada.",
  "Je afspeelgeschiedenis wordt vergeten en de lijst ‘Recent’ op het tabblad Start wordt leeggemaakt.",
  "История воспроизведения будет забыта, а список «Недавние» на вкладке «Главная» очищен.",
  "Historia odtwarzania zostanie zapomniana, a lista „Ostatnie” na karcie Start opróżniona.",
  "Çalma geçmişiniz unutulacak ve Ana Sayfa sekmesindeki “Son kullanılan” listesi boşalacak.",
  "Din uppspelningshistorik glöms och listan ”Senaste” på fliken Hem töms.",
  "再生履歴が消去され、ホームタブの「最近」リストが空になります。",
  "재생 기록이 지워지고 홈 탭의 “최근” 목록이 비워집니다.",
  "将忘记你的播放历史，并清空“首页”标签的“最近”列表。")
T("Forgets how long you practised on each day, emptying the Home tab's “Time Spent Singing”.",
  "Vergisst, wie lange du an welchem Tag geübt hast: Die „Gesungene Zeit“ im Start-Tab wird geleert.",
  "Olvida cuánto practicaste cada día: vacía el «Tiempo cantado» de la pestaña Inicio.",
  "Oublie combien de temps vous avez pratiqué chaque jour : vide le « Temps de chant » de l’onglet Accueil.",
  "Dimentica quanto ti sei esercitato ogni giorno: svuota il “Tempo cantato” della scheda Home.",
  "Esquece quanto tempo você praticou em cada dia: esvazia o “Tempo cantado” da aba Início.",
  "Vergeet hoe lang je elke dag oefende: maakt de ‘Gezongen tijd’ op het tabblad Start leeg.",
  "Забывает, сколько вы занимались каждый день: очищает «Время пения» на вкладке «Главная».",
  "Zapomina, jak długo ćwiczyłeś każdego dnia: opróżnia „Czas śpiewania” na karcie Start.",
  "Her gün ne kadar çalıştığınızı unutur: Ana Sayfa sekmesindeki “Şarkı söyleme süresi”ni boşaltır.",
  "Glömmer hur länge du övat varje dag: tömmer ”Sångtid” på fliken Hem.",
  "どの日にどれだけ練習したかを忘れます。ホームタブの「歌った時間」が空になります。",
  "어느 날 얼마나 연습했는지 잊습니다. 홈 탭의 “노래한 시간”이 비워집니다.",
  "忘记你每天练了多久：清空“首页”标签的“歌唱时长”。")
T("Your practice time will be forgotten, emptying the Home tab's “Time Spent Singing”.",
  "Deine Übungszeit wird vergessen und die „Gesungene Zeit“ im Start-Tab geleert.",
  "Se olvidará tu tiempo de práctica y se vaciará el «Tiempo cantado» de la pestaña Inicio.",
  "Votre temps de pratique sera oublié et le « Temps de chant » de l’onglet Accueil sera vidé.",
  "Il tuo tempo di esercizio verrà dimenticato e il “Tempo cantato” della scheda Home sarà svuotato.",
  "Seu tempo de prática será esquecido e o “Tempo cantado” da aba Início será esvaziado.",
  "Je oefentijd wordt vergeten en de ‘Gezongen tijd’ op het tabblad Start wordt leeggemaakt.",
  "Время занятий будет забыто, а «Время пения» на вкладке «Главная» очищено.",
  "Twój czas ćwiczeń zostanie zapomniany, a „Czas śpiewania” na karcie Start opróżniony.",
  "Çalışma süreniz unutulacak ve Ana Sayfa sekmesindeki “Şarkı söyleme süresi” boşalacak.",
  "Din övningstid glöms och ”Sångtid” på fliken Hem töms.",
  "練習時間が忘れられ、ホームタブの「歌った時間」が空になります。",
  "연습 시간이 잊히고 홈 탭의 “노래한 시간”이 비워집니다.",
  "将忘记你的练习时长，并清空“首页”标签的“歌唱时长”。")
