# Batch 9: the introduction shown on the first launch — its slides, the
# buttons that move through them and the Settings row that replays it.
from trbase import T

# --- Moving through the slides ---
T("Skip",
  "Überspringen",
  "Omitir",
  "Passer",
  "Salta",
  "Pular",
  "Overslaan",
  "Пропустить",
  "Pomiń",
  "Atla",
  "Hoppa över",
  "スキップ",
  "건너뛰기",
  "跳过")
T("Continue",
  "Weiter",
  "Continuar",
  "Continuer",
  "Continua",
  "Continuar",
  "Doorgaan",
  "Продолжить",
  "Dalej",
  "Devam",
  "Fortsätt",
  "続ける",
  "계속",
  "继续")

# --- Leaving it, and finding it again ---
T("Tutorial",
  "Einführung",
  "Tutorial",
  "Tutoriel",
  "Tutorial",
  "Tutorial",
  "Rondleiding",
  "Обучение",
  "Samouczek",
  "Tanıtım",
  "Introduktion",
  "チュートリアル",
  "튜토리얼",
  "使用教程")
T("You can watch it again in Settings.",
  "Du kannst sie jederzeit in den Einstellungen erneut ansehen.",
  "Puedes volver a verlo en Ajustes.",
  "Vous pouvez le revoir dans les Réglages.",
  "Puoi rivederlo nelle Impostazioni.",
  "Você pode assistir de novo nos Ajustes.",
  "Je kunt hem opnieuw bekijken in Instellingen.",
  "Его можно посмотреть снова в настройках.",
  "Możesz obejrzeć go ponownie w Ustawieniach.",
  "Ayarlar’dan tekrar izleyebilirsiniz.",
  "Du kan se den igen under Inställningar.",
  "「設定」からいつでも見直せます。",
  "설정에서 다시 볼 수 있습니다.",
  "你可以在“设置”中再次观看。")
T("Play the introduction the app opens with on its first launch again.",
  "Spielt die Einführung erneut ab, mit der die App beim ersten Start beginnt.",
  "Vuelve a reproducir la introducción con la que la app se abre la primera vez.",
  "Relance l’introduction affichée au premier lancement de l’app.",
  "Riproduce di nuovo l’introduzione con cui l’app si apre al primo avvio.",
  "Reproduz de novo a introdução que o app mostra na primeira abertura.",
  "Speelt de introductie opnieuw af waarmee de app bij de eerste start begint.",
  "Повторно показывает вступление, с которого приложение начинается при первом запуске.",
  "Odtwarza ponownie wprowadzenie, od którego aplikacja zaczyna przy pierwszym uruchomieniu.",
  "Uygulamanın ilk açılışta gösterdiği tanıtımı yeniden oynatır.",
  "Spelar upp introduktionen som appen börjar med vid första starten igen.",
  "初回起動時に表示される紹介をもう一度再生します。",
  "앱을 처음 열 때 나오는 소개를 다시 재생합니다.",
  "重新播放应用首次启动时显示的介绍。")

# --- Slide: how long a day to practise ---
# The title is "Daily practice goal", shared with the Settings row it sets — see
# tr_settings.py.
T("How long do you want to sing?",
  "Wie lange möchtest du singen?",
  "¿Cuánto tiempo quieres cantar?",
  "Combien de temps voulez-vous chanter ?",
  "Quanto tempo vuoi cantare?",
  "Por quanto tempo você quer cantar?",
  "Hoe lang wil je zingen?",
  "Сколько времени хотите петь?",
  "Jak długo chcesz śpiewać?",
  "Ne kadar süre şarkı söylemek istiyorsunuz?",
  "Hur länge vill du sjunga?",
  "どれくらい歌いますか？",
  "얼마나 노래하고 싶으세요?",
  "你想唱多久？")

# --- Slide: light or dark ---
T("Pick a look.",
  "Wähle ein Aussehen.",
  "Elige un aspecto.",
  "Choisissez une apparence.",
  "Scegli un aspetto.",
  "Escolha uma aparência.",
  "Kies een uiterlijk.",
  "Выберите оформление.",
  "Wybierz wygląd.",
  "Bir görünüm seçin.",
  "Välj ett utseende.",
  "見た目を選んでください。",
  "원하는 모양을 고르세요.",
  "选择一种外观。")

# --- Slide: where exercises come from ---
T("Three ways to fill your library.",
  "Drei Wege, deine Bibliothek zu füllen.",
  "Tres formas de llenar tu biblioteca.",
  "Trois façons de remplir votre bibliothèque.",
  "Tre modi per riempire la tua libreria.",
  "Três maneiras de encher sua biblioteca.",
  "Drie manieren om je bibliotheek te vullen.",
  "Три способа наполнить вашу библиотеку.",
  "Trzy sposoby na wypełnienie biblioteki.",
  "Kitaplığınızı doldurmanın üç yolu.",
  "Tre sätt att fylla ditt bibliotek.",
  "ライブラリを充実させる3つの方法。",
  "라이브러리를 채우는 세 가지 방법.",
  "填充练习库的三种方式。")
T("Sing the exercises the app comes with.",
  "Sing die Übungen, die die App mitbringt.",
  "Canta los ejercicios que incluye la app.",
  "Chantez les exercices fournis avec l’app.",
  "Canta gli esercizi inclusi nell’app.",
  "Cante os exercícios que já vêm no app.",
  "Zing de oefeningen die in de app zitten.",
  "Пойте упражнения, которые есть в приложении.",
  "Śpiewaj ćwiczenia dołączone do aplikacji.",
  "Uygulamayla gelen egzersizleri söyleyin.",
  "Sjung övningarna som följer med appen.",
  "アプリに入っているエクササイズを歌う。",
  "앱에 들어 있는 연습을 불러 보세요.",
  "唱应用自带的练习。")
T("Download more from the Community tab.",
  "Lade weitere im Community-Tab herunter.",
  "Descarga más en la pestaña Comunidad.",
  "Téléchargez-en d’autres dans l’onglet Communauté.",
  "Scaricane altri dalla scheda Comunità.",
  "Baixe mais na aba Comunidade.",
  "Download er meer op het tabblad Community.",
  "Скачивайте другие на вкладке «Сообщество».",
  "Pobierz więcej na karcie Społeczność.",
  "Topluluk sekmesinden daha fazlasını indirin.",
  "Ladda ner fler på fliken Community.",
  "コミュニティタブでもっとダウンロード。",
  "커뮤니티 탭에서 더 내려받으세요.",
  "在“社区”标签下载更多。")
T("Write your own, and publish them.",
  "Schreib eigene Übungen und veröffentliche sie.",
  "Crea los tuyos y publícalos.",
  "Créez les vôtres et publiez-les.",
  "Crea i tuoi e pubblicali.",
  "Crie os seus e publique.",
  "Schrijf je eigen oefeningen en publiceer ze.",
  "Создавайте свои и публикуйте их.",
  "Twórz własne i publikuj je.",
  "Kendi egzersizlerinizi yazın ve yayınlayın.",
  "Skriv egna och publicera dem.",
  "自分で作って公開する。",
  "직접 만들어 공개해 보세요.",
  "自己创作，并发布出去。")

# --- Slide: what can be rearranged ---
T("Make it yours",
  "Ganz wie du willst",
  "A tu gusto",
  "À votre goût",
  "A modo tuo",
  "Do seu jeito",
  "Maak het je eigen",
  "Настройте под себя",
  "Po swojemu",
  "Kendinize göre",
  "Helt som du vill",
  "自分好みに",
  "내 마음대로",
  "随你定制")
T("Change what your Home tab, playback screen and more show, how they look and how they are arranged.",
  "Ändere, was dein Start-Tab, der Wiedergabebildschirm und mehr zeigen, wie sie aussehen und wie sie angeordnet sind.",
  "Cambia qué muestran tu pestaña Inicio, la pantalla de reproducción y más, cómo se ven y cómo se organizan.",
  "Changez ce qu’affichent votre onglet Accueil, l’écran de lecture et plus encore, leur apparence et leur agencement.",
  "Cambia cosa mostrano la scheda Home, la schermata di riproduzione e altro, il loro aspetto e la loro disposizione.",
  "Mude o que a aba Início, a tela de reprodução e mais mostram, como eles ficam e como são organizados.",
  "Bepaal wat het tabblad Start, het afspeelscherm en meer tonen, hoe ze eruitzien en hoe ze zijn ingedeeld.",
  "Меняйте, что показывают вкладка «Главная», экран воспроизведения и другие экраны, как они выглядят и как расположены.",
  "Zmień, co pokazują karta Start, ekran odtwarzania i nie tylko, jak wyglądają i jak są ułożone.",
  "Ana Sayfa sekmesinin, çalma ekranının ve daha fazlasının ne gösterdiğini, nasıl göründüğünü ve nasıl düzenlendiğini değiştirin.",
  "Ändra vad fliken Hem, uppspelningsskärmen och mer visar, hur de ser ut och hur de är ordnade.",
  "ホームタブや再生画面などの表示内容、見た目、並び順を変えられます。",
  "홈 탭과 재생 화면 등에서 무엇을 보여줄지, 어떻게 보일지, 어떻게 배치할지 바꿀 수 있습니다.",
  "更改首页、播放界面等显示的内容、外观和排列方式。")

# --- Slide: the press-and-hold help ---
T("Stuck?",
  "Unklar?",
  "¿Dudas?",
  "Un doute ?",
  "Dubbi?",
  "Dúvida?",
  "Vragen?",
  "Не поняли?",
  "Nie wiesz?",
  "Takıldınız mı?",
  "Osäker?",
  "わからない？",
  "궁금한가요?",
  "有疑问？")
T("Press and hold anything to see what it does.",
  "Halte etwas gedrückt, um zu sehen, was es macht.",
  "Mantén pulsado cualquier cosa para ver qué hace.",
  "Appuyez longuement sur un élément pour voir ce qu’il fait.",
  "Tieni premuto qualsiasi cosa per vedere cosa fa.",
  "Toque e segure qualquer coisa para ver o que ela faz.",
  "Houd iets ingedrukt om te zien wat het doet.",
  "Нажмите и удерживайте что угодно, чтобы узнать, что это.",
  "Przytrzymaj cokolwiek, aby zobaczyć, co robi.",
  "Ne işe yaradığını görmek için herhangi bir şeye basılı tutun.",
  "Håll in vad som helst för att se vad det gör.",
  "長押しすると、それが何をするか分かります。",
  "무엇이든 길게 누르면 설명이 나옵니다.",
  "长按任意项目即可查看它的作用。")
